FoundationDB/fdb-kubernetes-operator

- ACKNOWLEDGEMENTS
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- Dockerfile
- LICENSE
- config/test-certs/generate_secrets.bash
- foundationdb-kubernetes-sidecar/Dockerfile
- foundationdb-kubernetes-sidecar/entrypoint.bash
- foundationdb-kubernetes-sidecar/sidecar.py
- pkg/controller/add_foundationdbcluster.go
- pkg/controller/controller.go
- pkg/controller/foundationdbcluster/foundationdbcluster_admin_client.go
- pkg/controller/foundationdbcluster/foundationdbcluster_admin_client_test.go
- pkg/controller/foundationdbcluster/foundationdbcluster_controller.go
- pkg/controller/foundationdbcluster/foundationdbcluster_controller_suite_test.go
- pkg/controller/foundationdbcluster/foundationdbcluster_controller_test.go
- pkg/controller/foundationdbcluster/foundationdbcluster_pod_client.go
- pkg/webhook/webhook.go
Standardize formatting of licensing comments.
> Add missing license information

- pkg/controller/foundationdbcluster/foundationdbcluster_admin_client.go
- pkg/controller/foundationdbcluster/foundationdbcluster_controller.go
- pkg/controller/foundationdbcluster/foundationdbcluster_controller_suite_test.go
- pkg/controller/foundationdbcluster/foundationdbcluster_controller_test.go
- pkg/controller/foundationdbcluster/foundationdbcluster_pod_client.go
> Requeue reconciliation rather than running blocking or polling actions.

- pkg/controller/foundationdbcluster/foundationdbcluster_controller.go
> Skip the check on dynamic conf for processes that are pending removal.

- config/crds/apps_v1beta1_foundationdbcluster.yaml
- pkg/apis/apps/v1beta1/foundationdbcluster_types.go
- pkg/controller/foundationdbcluster/foundationdbcluster_controller.go
- pkg/controller/foundationdbcluster/foundationdbcluster_controller_test.go
- pkg/controller/foundationdbcluster/foundationdbcluster_pod_client.go
> Adds an instance ID to the locality fields.

- config/crds/apps_v1beta1_foundationdbcluster.yaml
- config/samples/local_cluster.yaml
- pkg/apis/apps/v1beta1/foundationdbcluster_types.go
- pkg/apis/apps/v1beta1/zz_generated.deepcopy.go
- pkg/controller/foundationdbcluster/foundationdbcluster_controller.go
- pkg/controller/foundationdbcluster/foundationdbcluster_controller_test.go
> Add a flag to enable or disable the automounted service account token in our pods.

- pkg/controller/foundationdbcluster/add_pods.go
- pkg/controller/foundationdbcluster/bounce_processes.go
- pkg/controller/foundationdbcluster/choose_removals.go
- pkg/controller/foundationdbcluster/controller.go
- pkg/controller/foundationdbcluster/generate_initial_cluster_file.go
- pkg/controller/foundationdbcluster/remove_pods.go
- pkg/controller/foundationdbcluster/update_config_map.go
- pkg/controller/foundationdbcluster/update_labels.go
- pkg/controller/foundationdbcluster/update_pods.go
- pkg/controller/foundationdbcluster/update_sidecar_versions.go
- pkg/controller/foundationdbcluster/update_status.go
> Ignore pods that are not owned by the cluster in reconciliation.

- README.md
If someone follows the README exactly like its written and doesnt have much background on GoLang he will face some issues. 
This change will help mitigate those issues.
> Improve installation stpes

- .gitignore
- Makefile
- README.md
- config/samples/cluster_large.yaml
- config/samples/cluster_local.yaml
- config/samples/cluster_local_tls.yaml
- config/samples/cluster_with_backup.yaml
- config/samples/deployment.yaml
- config/samples/deployment/kustomization.yaml
- config/samples/deployment/manager.yaml
- config/samples/deployment/rbac_role.yaml
- config/samples/deployment/rbac_role_binding.yaml
- docs/user_manual.md
> Add more information to the README about running the operator.

- pkg/controller/foundationdbcluster/controller.go
- pkg/controller/foundationdbcluster/update_pods.go
- pkg/controller/foundationdbcluster/update_status.go
> Use a hash of the pod spec to determine when we need to recreate pods.

- pkg/apis/apps/v1beta1/foundationdbcluster_types.go
- pkg/apis/apps/v1beta1/foundationdbcluster_types_test.go
- pkg/controller/foundationdbcluster/admin_client.go
> Add additional coordinators when the database is using multiple regions.

- pkg/apis/apps/v1beta1/foundationdbcluster_types.go
- pkg/apis/apps/v1beta1/foundationdbcluster_types_test.go
> Incorporate satellite logs into the default log counts.

- pkg/controller/foundationdbcluster/pod_client.go
- pkg/controller/foundationdbcluster/pod_client_test.go
> Use the pod's current state to determine whether we need a TLS connection to the sidecar.

- config/crds/apps_v1beta1_foundationdbcluster.yaml
- pkg/apis/apps/v1beta1/foundationdbcluster_types.go
- pkg/controller/foundationdbcluster/add_pods.go
- pkg/controller/foundationdbcluster/controller.go
- pkg/controller/foundationdbcluster/controller_test.go
- pkg/controller/foundationdbcluster/pod_client.go
- pkg/controller/foundationdbcluster/pod_models.go
- pkg/controller/foundationdbcluster/pod_models_test.go
- pkg/controller/foundationdbcluster/update_pods.go
- pkg/controller/foundationdbcluster/update_status.go
> Change the way we generate instance IDs to remove the need to track the next instance ID in the spec.

- foundationdb-kubernetes-sidecar/sidecar.py
- pkg/apis/apps/v1beta1/foundationdbcluster_types.go
- pkg/apis/apps/v1beta1/foundationdbcluster_types_test.go
- pkg/controller/foundationdbcluster/controller_test.go
- pkg/controller/foundationdbcluster/foundationdbcluster_controller_suite_test.go
- pkg/controller/foundationdbcluster/pod_models.go
- pkg/controller/foundationdbcluster/pod_models_test.go
- pkg/controller/foundationdbcluster/update_pods.go
- pkg/controller/foundationdbcluster/update_status.go
> Add more command-line flags to the sidecar to replace environment variables

- foundationdb-kubernetes-sidecar/sidecar.py
- pkg/apis/apps/v1beta1/foundationdbcluster_types.go
- pkg/controller/foundationdbcluster/controller.go
- pkg/controller/foundationdbcluster/controller_test.go
- pkg/controller/foundationdbcluster/foundationdbcluster_controller_suite_test.go
- pkg/controller/foundationdbcluster/pod_client.go
- pkg/controller/foundationdbcluster/pod_models.go
- pkg/controller/foundationdbcluster/pod_models_test.go
> Using server from the FoundationDB image when it matches the sidecar version

- pkg/apis/apps/v1beta1/foundationdbcluster_types.go
- pkg/apis/apps/v1beta1/foundationdbcluster_types_test.go
- pkg/controller/foundationdbcluster/update_database_configuration.go
- pkg/controller/foundationdbcluster/update_status.go
> Break configuration changes into multiple steps when changing region config.

- config/crds/apps_v1beta1_foundationdbcluster.yaml
- config/samples/cluster_large.yaml
- config/samples/cluster_local.yaml
- config/samples/cluster_local_tls.yaml
- config/samples/cluster_with_backup.yaml
- config/samples/deployment.yaml
- config/samples/deployment/manager.yaml
- docs/user_manual.md
- pkg/apis/apps/v1beta1/foundationdbcluster_types.go
- pkg/apis/apps/v1beta1/zz_generated.deepcopy.go
- pkg/controller/foundationdbcluster/controller.go
- pkg/controller/foundationdbcluster/controller_test.go
- pkg/controller/foundationdbcluster/pod_models.go
- pkg/controller/foundationdbcluster/pod_models_test.go
- pkg/controller/foundationdbcluster/set_default_values.go
- pkg/controller/foundationdbcluster/update_config_map.go
- pkg/controller/foundationdbcluster/update_labels.go
- pkg/controller/foundationdbcluster/update_pods.go
- pkg/controller/foundationdbcluster/update_status.go
> More customization for resources created by the operator

- docs/user_manual.md
This PR is adding some documentations about how to access a cluster from within Kubernetes.
It is using an example that is running `fdbcli --exec 'status'` as a cronjob every minute.
> Add documentation on how to access a cluster

- api/v1beta1/foundationdbcluster_types.go
- api/v1beta1/foundationdbcluster_types_test.go
- api/v1beta1/suite_test.go
- config/crd/bases/apps.foundationdb.org_foundationdbclusters.yaml
- controllers/add_pods.go
- controllers/choose_removals.go
- controllers/controller.go
- controllers/controller_test.go
- controllers/suite_test.go
- controllers/update_sidecar_versions.go
- controllers/update_status.go
> Add support for new stateless roles in FDB 6.2

- controllers/admin_client.go
- controllers/choose_removals.go
- controllers/controller.go
- controllers/controller_test.go
- controllers/exclude_instances.go
- controllers/pod_client.go
- controllers/suite_test.go
> Allow replacing pods that are failing to launch.

- README.md
- api/v1beta1/suite_test.go
- controllers/admin_client.go
- controllers/controller.go
- controllers/suite_test.go
- docs/compatibility.md
- docs/user_manual.md
> Drop support for FDB versions earlier than 6.1.12.

- controllers/controller.go
- controllers/controller_test.go
- controllers/pod_models.go
- controllers/pod_models_test.go
fix for https://github.com/FoundationDB/fdb-kubernetes-operator/issues/81
> customizing name of the configmap

- controllers/pod_models.go
- controllers/pod_models_test.go
fixes https://github.com/FoundationDB/fdb-kubernetes-operator/issues/80
> customize volume claim name

- config/samples/cluster_with_client.yaml
> Add an example of starting a client app connected to the cluster.

- controllers/bounce_processes.go
- controllers/controller.go
- controllers/update_database_configuration.go
- controllers/update_pods.go
- controllers/update_status.go
> Remove support for the HAS_STATUS_SUBRESOURCE flag.

- Dockerfile
- foundationdb-kubernetes-sidecar/Dockerfile
> Add a default user to the images for the operator and the Kubernetes sidecar.

- ACKNOWLEDGEMENTS
- Makefile
- README.md
- api/v1beta1/foundationdbcluster_types.go
- cmd/po-docgen/api.go
- cmd/po-docgen/doc.go
- cmd/po-docgen/main.go
- docs/cluster_spec.md
> Auto-generate API docs

- api/v1beta1/foundationdbcluster_types.go
- api/v1beta1/foundationdbcluster_types_test.go
- api/v1beta1/zz_generated.deepcopy.go
- config/crd/bases/apps.foundationdb.org_foundationdbclusters.yaml
- config/samples/deployment.yaml
- controllers/controller.go
- controllers/controller_test.go
- controllers/update_status.go
- docs/cluster_spec.md
> Refactor reconciliation to be based entirely on the spec and status of the cluster

- api/v1beta1/foundationdbcluster_types.go
- config/crd/bases/apps.foundationdb.org_foundationdbclusters.yaml
- config/samples/deployment.yaml
> Adds a shortname for the CRD.

- controllers/controller.go
> Improve logging when we convert a retryable error into a requeue.

- .github/workflows/pull_request.yml
- Makefile
- api/v1beta1/foundationdbcluster_types.go
- api/v1beta1/foundationdbcluster_types_test.go
- api/v1beta1/suite_test.go
- controllers/add_pods.go
- controllers/admin_client.go
- controllers/bounce_processes.go
- controllers/change_coordinators.go
- controllers/check_client_compatibility.go
- controllers/choose_removals.go
- controllers/controller.go
- controllers/controller_test.go
- controllers/exclude_instances.go
- controllers/generate_initial_cluster_file.go
- controllers/include_instances.go
- controllers/pod_client.go
- controllers/pod_models.go
- controllers/remove_pods.go
- controllers/set_default_values.go
- controllers/suite_test.go
- controllers/update_config_map.go
- controllers/update_database_configuration.go
- controllers/update_labels.go
- controllers/update_pods.go
- controllers/update_sidecar_versions.go
- controllers/update_status.go
> Fix golint issues

- config/default/kustomization.yaml
- config/manager/kustomization.yaml
- config/minio/instance.yaml
- config/minio/instance_overrides.yaml
- config/minio/kustomization.yaml
- config/minio/operator.yaml
- config/minio/service.yaml
- config/rbac/kustomization.yaml
- config/samples/cluster_with_backup.yaml
> Set up a local MinIO instance for testing backups.

- config/samples/cluster_local.yaml
- config/samples/cluster_local_tls.yaml
- controllers/controller_test.go
- controllers/suite_test.go
> Add a cluster controller process to some standard test cases.

- controllers/admin_client.go
- controllers/change_coordinators.go
> Sync coordinator changes when running across Kubernetes clusters

- config/samples/cluster_local.yaml
- config/samples/cluster_local_tls.yaml
- config/samples/cluster_with_backup.yaml
- config/samples/cluster_with_client.yaml
> Rename persistentVolumeClaim to volumeClaim in samples

- api/v1beta1/foundationdbcluster_types.go
- api/v1beta1/foundationdbcluster_types_test.go
- controllers/admin_client.go
- controllers/controller_test.go
- controllers/update_status.go
- docs/cluster_spec.md
> Check the process's version in the status in reconciliation.

- controllers/pod_client.go
Hello! Still loving this project so far, but ran into something that ate quite a bit of my time when setting up a new cluster.
When configuring the controller manager, missing TLS environment variables results in a painfully vague error:
```
2020-03-12T23:53:20.779Z        ERROR   controller      Error in reconciliation {"subReconciler": "controllers.GenerateInitialClusterFile", "namespace": "default", "cluster": "fdb-test", "error": "open : no such file or directory"}
github.com/go-logr/zapr.(*zapLogger).Error
/go/pkg/mod/github.com/go-logr/zapr@v0.1.0/zapr.go:128
github.com/FoundationDB/fdb-kubernetes-operator/controllers.(*FoundationDBClusterReconciler).Reconcile
/workspace/controllers/controller.go:127
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandle …
```
> Improve error message when TLS paths not set.

- controllers/cluster_controller_test.go
- controllers/controllers.go
- controllers/update_backup_agents.go
- controllers/update_config_map.go
- controllers/update_labels.go
> Avoid overwriting existing annotations.

- Dockerfile
> Remove unnecessary binaries from the docker image.

- controllers/add_pods.go
- controllers/cluster_controller_test.go
> Skip over instance IDs that are in the instancesToRemove list when adding new pods.

- controllers/pod_models.go
- controllers/pod_models_test.go
> Use a read-only root file system.

- api/v1beta1/foundationdbcluster_types.go
- api/v1beta1/foundationdbcluster_types_test.go
> Reduce the default log router count.

- api/v1beta1/foundationdbcluster_types.go
- controllers/pod_models.go
- controllers/pod_models_test.go
- controllers/suite_test.go
- controllers/update_status.go
- foundationdb-kubernetes-sidecar/sidecar.py
> Add option to crash the sidecar when the cluster file is empty

- controllers/add_pods.go
- controllers/cluster_controller.go
- controllers/pod_models.go
> Remove an unnecessary variant on the buildOwnerReference method.

- controllers/cluster_controller.go
- controllers/cluster_controller_test.go
- controllers/pod_models.go
- controllers/pod_models_test.go
> Omit TLS CA file when no trusted CAs are given

- api/v1beta1/foundationdbcluster_types.go
- api/v1beta1/foundationdbcluster_types_test.go
- config/crd/bases/apps.foundationdb.org_foundationdbbackups.yaml
- controllers/admin_client.go
- controllers/backup_controller.go
- controllers/backup_controller_test.go
- controllers/pod_models_test.go
- controllers/stop_backup.go
- docs/cluster_spec.md
> Adds a mechanism to stop backups.

- api/v1beta1/foundationdbcluster_types.go
- api/v1beta1/foundationdbcluster_types_test.go
- config/crd/bases/apps.foundationdb.org_foundationdbbackups.yaml
- controllers/admin_client.go
- controllers/admin_client_test.go
- controllers/backup_controller.go
- controllers/backup_controller_test.go
- controllers/toggle_backup_paused.go
- controllers/update_backup_status.go
- docs/cluster_spec.md
- go.sum
> Add an option for pausing backups.

- Makefile
- api/v1beta1/foundationdbcluster_types.go
- config/crd/bases/apps.foundationdb.org_foundationdbclusters.yaml
- controllers/cluster_controller.go
- controllers/cluster_controller_test.go
- controllers/pod_models.go
- controllers/pod_models_test.go
- controllers/replace_misconfigured_pods.go
- controllers/update_labels.go
- controllers/update_pods.go
- docs/cluster_spec.md
- docs/user_manual.md
> Resizing volumes

- controllers/cluster_controller.go
- controllers/cluster_controller_test.go
- controllers/pod_models_test.go
> Drop support for older instance ID labels.

- api/v1beta1/foundationdbcluster_types.go
- config/crd/bases/apps.foundationdb.org_foundationdbbackups.yaml
> Add print columns to the backup resource.

- api/v1beta1/foundationdbcluster_types.go
- api/v1beta1/foundationdbcluster_types_test.go
- config/crd/bases/apps.foundationdb.org_foundationdbclusters.yaml
- controllers/admin_client.go
- controllers/bounce_processes.go
- controllers/change_coordinators.go
- controllers/check_client_compatibility.go
- controllers/cluster_controller.go
- controllers/cluster_controller_test.go
- controllers/generate_initial_cluster_file.go
- controllers/pod_models.go
- controllers/restore_controller.go
- controllers/set_default_values.go
- controllers/start_restore.go
- controllers/suite_test.go
- controllers/update_database_configuration.go
- controllers/update_status.go
- docs/cluster_spec.md
> Move fields from spec to status

- api/v1beta1/foundationdbcluster_types.go
- api/v1beta1/foundationdbcluster_types_test.go
- controllers/check_client_compatibility.go
> Only check client compatibility when we are doing a protocol-incompatible upgrade.

- controllers/change_coordinators.go
- controllers/cluster_controller.go
- controllers/update_database_configuration.go
- controllers/update_pods.go
> Adds a cache for the connections from the lock client.

- controllers/update_database_configuration.go
> Avoid trying to make configuration changes when the database is unavailable.

- api/v1beta1/foundationdbcluster_types.go
- api/v1beta1/foundationdbcluster_types_test.go
- config/crd/bases/apps.foundationdb.org_foundationdbclusters.yaml
- controllers/admin_client.go
- controllers/admin_client_test.go
- controllers/change_coordinators.go
- controllers/cluster_controller.go
- controllers/cluster_controller_test.go
- controllers/generate_initial_cluster_file.go
- controllers/pod_client.go
- controllers/update_status.go
- docs/cluster_spec.md
> Ensure fault tolerance when recruiting coordinators.

- api/v1beta1/foundationdbcluster_types.go
- config/crd/bases/apps.foundationdb.org_foundationdbclusters.yaml
- controllers/cluster_controller.go
- controllers/cluster_controller_test.go
- controllers/update_status.go
- docs/cluster_spec.md
> Only include the sidecar conf in the config map when there are pods that require it.

- controllers/cluster_controller_test.go
> Add a test for replacing a pod while re-using its volume

- api/v1beta1/foundationdbcluster_types.go
- config/crd/bases/apps.foundationdb.org_foundationdbclusters.yaml
- controllers/admin_client.go
- controllers/check_client_compatibility.go
- controllers/cluster_controller_test.go
- docs/cluster_spec.md
> Add an option to disable the client compatibility check when upgrading.

- api/v1beta1/foundationdbcluster_types.go
- config/crd/bases/apps.foundationdb.org_foundationdbclusters.yaml
- config/samples/cluster_local_tls.yaml
- docs/cluster_spec.md
adding instance type fast restore
> initial commit for fast_restore

- api/v1beta1/foundationdbcluster_types.go
- api/v1beta1/zz_generated.deepcopy.go
- config/crd/bases/apps.foundationdb.org_foundationdbbackups.yaml
- controllers/backup_controller_test.go
- controllers/pod_models.go
- controllers/pod_models_test.go
- controllers/update_backup_agents.go
- controllers/update_backup_status.go
- docs/cluster_spec.md
> Allow specifying custom labels on backup deployments.

- controllers/cluster_controller_test.go
- controllers/pod_models.go
- controllers/replace_misconfigured_pods.go
> Replace any instances that have an instance ID with the wrong prefix.

- controllers/admin_client.go
- controllers/controllers.go
- main.go
> Add an option for controlling CLI timeouts.

- helm/fdb-operator/Chart.yaml
- helm/fdb-operator/crds/apps.foundationdb.org_foundationdbbackups.yaml
- helm/fdb-operator/crds/apps.foundationdb.org_foundationdbclusters.yaml
- helm/fdb-operator/crds/apps.foundationdb.org_foundationdbrestores.yaml
- helm/fdb-operator/templates/NOTES.txt
- helm/fdb-operator/templates/crds/apps.foundationdb.org_foundationdbclusters.yaml
- helm/fdb-operator/templates/manager/deployment.yaml
- helm/fdb-operator/templates/rbac/rbac_role.yaml
- helm/fdb-operator/templates/rbac/rbac_role_binding.yaml
- helm/fdb-operator/values.yaml
In this PR i moved the crds to the correct folder (https://helm.sh/docs/topics/charts/#custom-resource-definitions-crds) and added some of the missing pieces to update the helm chart to the latest fdb operator.
> Correct helm chart for helm 3

- controllers/backup_controller.go
- controllers/cluster_controller.go
> Add watch events for resources created by the operator.

- api/v1beta1/foundationdbcluster_types.go
- api/v1beta1/zz_generated.deepcopy.go
- config/crd/bases/apps.foundationdb.org_foundationdbclusters.yaml
- config/samples/cluster_local.yaml
- config/samples/cluster_local_tls.yaml
- config/samples/cluster_with_backup.yaml
- config/samples/cluster_with_client.yaml
- config/samples/multi_dc/final.yaml
- config/samples/multi_dc/stage_1.yaml
- config/samples/multi_kc/final.yaml
- config/samples/multi_kc/stage_1.yaml
- controllers/cluster_controller.go
- controllers/cluster_controller_test.go
- controllers/pod_models.go
- controllers/pod_models_test.go
- docs/cluster_spec.md
> Rename the volumeClaim field for more consistency with StatefulSet.

- foundationdb-kubernetes-sidecar/sidecar.py
Fixes: https://github.com/FoundationDB/fdb-kubernetes-operator/issues/90
> Make use of atomic copy for sidecar files

- .golangci.yml
- Makefile
- api/v1beta1/foundationdbcluster_types_test.go
- cmd/po-docgen/api.go
- controllers/add_pods.go
- controllers/add_services.go
- controllers/admin_client.go
- controllers/admin_client_test.go
- controllers/backup_controller_test.go
- controllers/bounce_processes.go
- controllers/cluster_controller.go
- controllers/cluster_controller_test.go
- controllers/generate_initial_cluster_file.go
- controllers/pod_models.go
- controllers/pod_models_test.go
- controllers/restore_controller_test.go
- controllers/update_config_map.go
- controllers/update_pods.go
- controllers/update_status.go
Removed most of the skipped files/folders and enabled some additional linters.
> Fix lint issues

- controllers/add_services.go
- controllers/cluster_controller.go
- controllers/pod_models.go
- controllers/pod_models_test.go
- controllers/remove_services.go
- controllers/update_status.go
I switched from `List` to `Get` since we only query one service.
> Simplify service reconciler

- api/v1beta1/foundationdbcluster_types.go
- controllers/admin_client.go
- controllers/check_instances_to_remove.go
- controllers/exclude_instances.go
- controllers/update_status.go
- docs/cluster_spec.md
> Get the exclusion list directly when we want to determine if processes have already been excluded.

- controllers/remove_pods.go
> Use instance IDs as the identifier when removing pods and PVCs.

- controllers/change_coordinators.go
- controllers/cluster_controller.go
- controllers/exclude_instances.go
- controllers/lock_client.go
- controllers/update_database_configuration.go
- controllers/update_pods.go
- controllers/update_status.go
This also includes some visibility improvements to the locking system based on my experience testing this.
Resolves #144
> Use locks to coordinate exclusions

- api/v1beta1/foundationdbcluster_types.go
- controllers/add_pods.go
- controllers/pod_models.go
- controllers/pod_models_test.go
- docs/cluster_spec.md
Fixes: https://github.com/FoundationDB/fdb-kubernetes-operator/issues/342
> Remove user provided tags

- config/rbac/role.yaml
- config/samples/deployment.yaml
- config/samples/deployment/rbac_role.yaml
- config/test-certs/generate_secrets.bash
- controllers/backup_controller.go
- controllers/cluster_controller.go
Add the required rules to be able to use the operator via `kustomize`.
> Update RBAC settings for role and simplify secrets labelling

- api/v1beta1/foundationdbcluster_types.go
- api/v1beta1/foundationdbcluster_types_test.go
> Use the zones and regions to infer whether locks are necessary.

- controllers/bounce_processes.go
- controllers/change_coordinators.go
- controllers/cluster_controller.go
- controllers/exclude_instances.go
- controllers/update_database_configuration.go
- controllers/update_pods.go
> Take a lock when bouncing processes.

- .github/workflows/pull_request.yml
- Dockerfile
- foundationdb-kubernetes-sidecar/Dockerfile
We want that the script fails if the curl command doesn't work otherwise the script will run in some strange issues.
> Ensure that the script ends if the curl fails

- Dockerfile
Fixes: https://github.com/FoundationDB/fdb-kubernetes-operator/issues/98 I validated that the operator still can call `fdbcli`.
> Use distroless as base image for the operator

- api/v1beta1/foundationdbcluster_types.go
- api/v1beta1/foundationdbcluster_types_test.go
- controllers/add_pods.go
- controllers/cluster_controller_test.go
- controllers/pod_models.go
Fixes: https://github.com/FoundationDB/fdb-kubernetes-operator/issues/392
> Expose all ports in a service for multi storage servers

- controllers/update_status.go
- controllers/update_status_test.go
Fixes: https://github.com/FoundationDB/fdb-kubernetes-operator/issues/389
> Add instances with missing Pod to failing Pods list

- docs/user_manual.md
Fixes: https://github.com/FoundationDB/fdb-kubernetes-operator/issues/335
> Add docs for StorageClass and multi Storage Servers per Pod

- Makefile
- kubectl-fdb/cmd/k8s_client.go
- kubectl-fdb/cmd/remove.go
- kubectl-fdb/cmd/root.go
- kubectl-fdb/cmd/version.go
- kubectl-fdb/main.go
Fixes some initial issues with the plugin and auto selects the default namespace from the current context.
> Fix initial issues with plugin

- Makefile
- kubectl-fdb/cmd/k8s_client.go
- kubectl-fdb/cmd/remove.go
- kubectl-fdb/cmd/remove_test.go
- kubectl-fdb/cmd/root.go
- kubectl-fdb/cmd/version.go
- kubectl-fdb/cmd/version_test.go
- kubectl-fdb/main.go
This work is based on https://github.com/FoundationDB/fdb-kubernetes-operator/pull/432 and add some initial unit tests for the fdb plugin.
> Add unit tests plugin

- .golangci.yml
- controllers/cluster_controller_test.go
Fixes:  https://github.com/FoundationDB/fdb-kubernetes-operator/issues/437
> Enable golint to check for shadowing

- api/v1beta1/foundationdbcluster_types.go
- api/v1beta1/foundationdbcluster_types_test.go
- controllers/add_services.go
- controllers/admin_client_test.go
- controllers/change_coordinators.go
- controllers/cluster_controller.go
- controllers/cluster_controller_test.go
- controllers/controllers.go
- controllers/generate_initial_cluster_file.go
- controllers/pod_client_test.go
- controllers/pod_models.go
- controllers/pod_models_test.go
- controllers/update_status.go
- controllers/update_status_test.go
- kubectl-fdb/cmd/remove.go
- kubectl-fdb/cmd/remove_test.go
Fixes: https://github.com/FoundationDB/fdb-kubernetes-operator/issues/421
> Use constants instead of magic strings

- api/v1beta1/foundationdbcluster_types.go
- controllers/pod_models.go
- controllers/update_status.go
- controllers/update_status_test.go
Fixes: https://github.com/FoundationDB/fdb-kubernetes-operator/issues/456
> Check if instance contains Pod before continuing

- go.sum
- kubectl-fdb/cmd/exec.go
- kubectl-fdb/cmd/exec_test.go
- kubectl-fdb/cmd/remove_test.go
- kubectl-fdb/cmd/root.go
- kubectl-fdb/main.go
> Add an exec subcommand for the kubectl plugin.

- .github/workflows/release.yaml
- Makefile
I need to check how I can tests this in my branch.
> Release the kubectl plugin with prebuilt binaries

- config/default/manager_auth_proxy_patch.yaml
- config/manager/manager.yaml
- config/samples/deployment.yaml
- config/samples/deployment/manager.yaml
- helm/fdb-operator/templates/manager/deployment.yaml
- main.go
> Enable leader election by default.

- api/v1beta1/foundationdbcluster_types.go
- controllers/admin_client.go
- controllers/admin_client_test.go
- controllers/backup_controller_test.go
- controllers/bounce_processes.go
- controllers/bounce_processes_test.go
- controllers/cluster_controller.go
- controllers/cluster_controller_test.go
- controllers/lock_client.go
- controllers/lock_client_test.go
- controllers/restore_controller_test.go
- controllers/suite_test.go
- docs/cluster_spec.md
> Coordinate upgrades across DCs

- .github/workflows/master.yml
- .github/workflows/release.yaml
Follow up to https://github.com/FoundationDB/fdb-kubernetes-operator/pull/470 to actually push the imagess.
> Enable push for docker images

- .github/workflows/pull_request.yml
- foundationdb-kubernetes-sidecar/Dockerfile
- foundationdb-kubernetes-sidecar/sidecar.py
- sample-apps/data-loader/app.py
This PR adds basic linting for our Python scripts I added https://github.com/psf/black + https://pypi.org/project/pycodestyle
> Add Python lint

- controllers/remove_pods.go
> Add locks before removing pods or including instances.

- .github/workflows/release.yaml
Fixes: https://github.com/FoundationDB/fdb-kubernetes-operator/issues/503
> Rename release job

- controllers/controllers.go
- controllers/update_labels.go
- controllers/update_labels_test.go
fixes: https://github.com/FoundationDB/fdb-kubernetes-operator/issues/458
> Prevent removing unkown labels in Pods

- api/v1beta1/foundationdbcluster_types.go
- api/v1beta1/foundationdbcluster_types_test.go
- controllers/add_process_groups_test.go
- controllers/admin_client.go
- controllers/change_coordinators.go
- controllers/choose_removals.go
- controllers/choose_removals_test.go
- controllers/cluster_controller.go
- controllers/cluster_controller_test.go
- controllers/controllers.go
> Use fault domains to determine which processes to shrink

- api/v1beta1/foundationdbcluster_types.go
- api/v1beta1/foundationdbcluster_types_test.go
- config/samples/cluster_local.yaml
- controllers/admin_client.go
- controllers/bounce_processes.go
- controllers/bounce_processes_test.go
- controllers/cluster_controller_test.go
- controllers/update_status.go
- controllers/update_status_test.go
- docs/cluster_spec.md
> Moves the management of more conditions into the process group status.

- .github/workflows/pull_request.yml
This should speed up the actions a little bit.
> Add cache to actions

- foundationdb-kubernetes-sidecar/Dockerfile
Fixes: https://github.com/FoundationDB/fdb-kubernetes-operator/issues/288
> Add tini to sidecar image

- sample-apps/data-loader/Dockerfile
- sample-apps/data-loader/app.py
- sample-apps/data-loader/job.yaml
I change the default image to the public image that we push from this repo, so user doesn't have to build the image.
> Update the data-loader example to use the public image

- config/samples/deployment.yaml
- controllers/cluster_controller.go
- controllers/replace_misconfigured_pods.go
- controllers/update_pods.go
Fixes: https://github.com/FoundationDB/fdb-kubernetes-operator/issues/502
> Log reasons for replacement

- Dockerfile
- config/samples/cluster_large.yaml
- config/samples/cluster_local.yaml
- config/samples/cluster_local_tls.yaml
- config/samples/cluster_with_backup.yaml
- config/samples/cluster_with_client.yaml
- config/samples/multi_dc/final.yaml
- config/samples/multi_dc/stage_1.yaml
- config/samples/multi_kc/final.yaml
- config/samples/multi_kc/stage_1.yaml
- docs/user_manual.md
- foundationdb-kubernetes-sidecar/Dockerfile
We should build some tooling to ensure we use the same version in the examples and the operator/sidecar.
> Update FDB version in examples

- controllers/cluster_controller.go
- controllers/pod_client.go
- controllers/update_config_map.go
- go.mod
- go.sum
Fixes: https://github.com/FoundationDB/fdb-kubernetes-operator/issues/558
Fixes: https://github.com/FoundationDB/fdb-kubernetes-operator/issues/557
> Update all ConfigMaps

- sample-apps/data-loader/Dockerfile
- sample-apps/data-loader/app.py
Make use of https://docs.python.org/3.9/library/random.html?highlight=random#functions-for-bytes in the sample app.
> Make use of random bytes lib

- .github/workflows/pull_request.yml
- Makefile
- README.md
- config/crd/bases/apps.foundationdb.org_foundationdbbackups.yaml
- config/crd/bases/apps.foundationdb.org_foundationdbclusters.yaml
- config/crd/bases/apps.foundationdb.org_foundationdbrestores.yaml
Fixes: https://github.com/FoundationDB/fdb-kubernetes-operator/issues/524
Fixes: https://github.com/FoundationDB/fdb-kubernetes-operator/issues/300
Fixes: https://github.com/FoundationDB/fdb-kubernetes-operator/issues/334
> Update to apiextensions/v1

- kubectl-fdb/cmd/exec_test.go
- kubectl-fdb/cmd/remove_instances.go
- kubectl-fdb/cmd/remove_instances_test.go
Fixes: https://github.com/FoundationDB/fdb-kubernetes-operator/issues/500
> Make use of patch instead of update

- api/v1beta1/foundationdbcluster_types.go
- config/crd/bases/apps.foundationdb.org_foundationdbclusters.yaml
- controllers/bounce_processes.go
- controllers/cluster_controller.go
- controllers/controllers.go
- controllers/pod_models.go
- controllers/suite_test.go
- docs/cluster_spec.md
Fixes: https://github.com/FoundationDB/fdb-kubernetes-operator/issues/581
> Allow to specify the minimum uptime seconds

- controllers/pod_models.go
- controllers/pod_models_test.go
Fixes: https://github.com/FoundationDB/fdb-kubernetes-operator/issues/602
> Fix ReadOnlyRootFilesystem override

- controllers/replace_misconfigured_pods.go
- controllers/replace_misconfigured_pods_test.go
This makes the replacement more robust and calculates the sum of all containers e.g. when a new sidecar is added.
> Calculate the sum of resource requirements

- .github/workflows/pull_request.yml
- Makefile
- api/v1beta1/foundationdbbackup_types_test.go
- api/v1beta1/foundationdbcluster_types_test.go
- api/v1beta1/suite_test.go
- api/v1beta1/testdata/suite_test.go
- controllers/pod_models_test.go
- e2e/Readme.md
- e2e/cluster_test.go
- e2e/suite_test.go
- kubectl-fdb/cmd/cordon_test.go
- kubectl-fdb/cmd/exec_test.go
- kubectl-fdb/cmd/remove_instances_test.go
- kubectl-fdb/cmd/root_test.go
- kubectl-fdb/cmd/suite_test.go
- kubectl-fdb/cmd/version_test.go
- mock-kubernetes-client/client/client_test.go
- mock-kubernetes-client/client/suite_test.go
> Initial add of an e2e test

- .github/workflows/release.yaml
Fixes: https://github.com/FoundationDB/fdb-kubernetes-operator/issues/622
> Make use of sha256sum instead of hashFiles and check if the final binary works

- kubectl-fdb/cmd/restart.go
The strange thing is that I can't reproduce this issue locally.
> Fix lint issue with false positive

- controllers/controllers.go
- go.mod
- go.sum
- kubectl-fdb/cmd/analyze.go
- kubectl-fdb/cmd/analyze_test.go
- kubectl-fdb/cmd/root.go
Fixes: https://github.com/FoundationDB/fdb-kubernetes-operator/issues/494
I got a few todo's in the code that I would cleanup afterwards.
> Initial support for fdb analyze command

- controllers/admin_client.go
fixes: https://github.com/FoundationDB/fdb-kubernetes-operator/issues/641
> Set the trace format in fdbcli

- api/v1beta1/foundationdbcluster_types.go
- controllers/metrics.go
- controllers/metrics_test.go
The result looks like that:
```bash
❯ curl -s localhost:8080/metrics  | ag 'fdb'
fdb_cluster_created_time{name="sample-cluster",namespace="default"} 1.619624461e+09
fdb_cluster_latest_reconciled{name="sample-cluster",namespace="default"} 1
fdb_cluster_reconciled_status{name="sample-cluster",namespace="default"} 0
fdb_cluster_status{name="sample-cluster",namespace="default",status_type="available"} 1
fdb_cluster_status{name="sample-cluster",namespace="default",status_type="datamovementpriority"} 0
fdb_cluster_status{name="sample-cluster",namespace="default",status_type="health"} 0
fdb_cluster_status{name="sample-cluster",namespace="default",status_type="replication"} 1
fdb_process_group_status{condition="IncorrectCommandLine",name="sample-cluster",namespace="default",process_class="cluster_ …
```
> Add metrics for process group and reconciled status

- docs/compatibility.md
- docs/monitoring.md
- docs/user_manual.md
- kubectl-fdb/cmd/deprecation.go
- kubectl-fdb/cmd/deprecation_test.go
I added a few sentences about the operator metrics and correct the format of the user-manual.
> Add monitoring docs and fix markdown

- kubectl-fdb/cmd/analyze.go
- kubectl-fdb/cmd/analyze_test.go
- kubectl-fdb/cmd/cordon.go
- kubectl-fdb/cmd/remove.go
- kubectl-fdb/cmd/remove_instances.go
- kubectl-fdb/cmd/restart.go
- kubectl-fdb/cmd/root.go
- kubectl-fdb/cmd/version.go
Only a small cleanup to not pass the root command always.
> Simplify root cmd handling

- controllers/update_status.go
Before we always set `IncorrectCommandLine` to true if we couldn't get a Pod client. In this case we ignore the failure and skip the Pod (we could also return the error).
> Ignore process group on error instead of setting condition

- foundationdb-kubernetes-sidecar/sidecar.py
I'll create a follow up issue to have a setting in the cluster CRD to enable HTTP ready/livenessProbes (which might be the default in the future).
This is the test result, `/ready` works and the rest is denied:
```bash
fdb@dev-cert-storage-4:/var/fdb$ curl -k https://localhost:8080/ready
OK
fdb@dev-cert-storage-4:/var/fdb$ curl -k https://localhost:8080/
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN"
"http://www.w3.org/TR/html4/strict.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=utf-8">
<title>Error response</title>
</head>
<body>
<h1>Error response</h1>
<p>Error code: 401</p>
<p>Message: Client certificate was not approved.</p>
<p>Error code explanation: 401 - No permission -- see authorization schemes.</p>
</body>
</html> …
```
> Allow to access the ready endpoint without a client cert

- controllers/cluster_controller_test.go
- controllers/update_status.go
Fixes: https://github.com/FoundationDB/fdb-kubernetes-operator/issues/701
> Fix status update

- api/v1beta1/foundationdbcluster_types.go
- controllers/add_process_groups.go
- controllers/add_process_groups_test.go
- controllers/update_status_test.go
I thought we got an issue for that.
> Set the missing conditions when creating new process groups

- docs/design/plugin_multi_fdb_support.md
- docs/manual/fault_domains.md
Initial design to support multi dc/kc FDB clusters with the plugin see: https://github.com/FoundationDB/fdb-kubernetes-operator/issues/482
> Initial design for multi dc/kc FDB clusters with the plugin

- kubectl-fdb/cmd/analyze.go
- kubectl-fdb/cmd/analyze_test.go
fixes: https://github.com/FoundationDB/fdb-kubernetes-operator/issues/708
fixes: https://github.com/FoundationDB/fdb-kubernetes-operator/issues/711
> Print message for removals in analyze

- api/v1beta1/foundationdb_status.go
- api/v1beta1/foundationdbcluster_types.go
- api/v1beta1/foundationdbcluster_types_test.go
- config/tests/base/cluster.yaml
- controllers/admin_client.go
- controllers/change_coordinators.go
- controllers/change_coordinators_test.go
- controllers/cluster_controller.go
- controllers/cluster_controller_test.go
- docs/cluster_spec.md
Fixes: https://github.com/FoundationDB/fdb-kubernetes-operator/issues/751 (at least the first part)
> Allow to downgrade from TLS to non-TLS

- controllers/cluster_controller_test.go
- controllers/remove_pods.go
Fixes: https://github.com/FoundationDB/fdb-kubernetes-operator/issues/764
> Don't block if PVC or service is in terminating state

- controllers/backup_controller.go
- controllers/cluster_controller.go
- controllers/restore_controller.go
- setup/setup.go
Fixes: https://github.com/FoundationDB/fdb-kubernetes-operator/issues/634
> Allow to set the max concurrent reconciles

- helm/fdb-operator/Chart.yaml
- helm/fdb-operator/templates/NOTES.txt
- helm/fdb-operator/templates/_helpers.tpl
- helm/fdb-operator/templates/manager/deployment.yaml
- helm/fdb-operator/templates/rbac/rbac_role.yaml
- helm/fdb-operator/templates/rbac/rbac_role_binding.yaml
- helm/fdb-operator/templates/rbac/serviceaccount.yaml
- helm/fdb-operator/values.yaml
Hello there !
Using your operator for the last year and very happy with it
Offering here a few improvements to the Helm chart
Some of these are opinionated, and I am more than welcome to have those changed
Motivation:
- Fix a few bugs and indentations
- Increase conformance to other community charts
- Have the chart more configurable for common use-cases
- BREAKING CHANGE: adapt deployment's labels to Helm's [best practices](https://helm.sh/docs/chart_best_practices/labels/)
> helm chart improvements

- .github/PULL_REQUEST_TEMPLATE.md
- docs/manual/backup.md
- docs/manual/customization.md
- docs/manual/debugging.md
- docs/manual/index.md
- docs/manual/replacements_and_deletions.md
- docs/manual/resources.md
- docs/manual/technical_design.md
- docs/manual/warnings.md
- kubectl-fdb/cmd/analyze.go
This expands the user manual to cover core technical design and debugging. 
Resolves #736
- Documentation Update
No.
Manual testing in dev environment?*
N/A
*Is there we need to perform additional testing once this is merged, or perform in a larger testing environment?*
No.
Yes
No
*Does this introduce new defaults that we should re-evaluate in the future?*
No.
> Add new sections in the user manual

- api/v1beta1/foundationdb_version.go
- api/v1beta1/suite_test.go
- config/tests/base/cluster.yaml
- controllers/bounce_processes_test.go
- controllers/cluster_controller_test.go
- controllers/lock_client_test.go
- controllers/pod_models_test.go
- controllers/suite_test.go
- internal/deprecations.go
- internal/deprecations_test.go
- kubectl-fdb/cmd/deprecation_test.go
Resolves #501 
This is marked to only take effect in the future. This prepares us to make us the default as part of the 1.0 release.
> Enable automatic replacement by default.

- controllers/remove_pods.go
Fixes: https://github.com/FoundationDB/fdb-kubernetes-operator/issues/799 this change will allow to set the excluded field for process groups. There is no need to block the next reconciler if not all process groups are removed.
Locally. I'll add later a test case with a Pod stuck in terminating.
Nothing.
No
> Don't skip update status after process group removal

- controllers/change_coordinators.go
- controllers/pod_models.go
- controllers/pod_models_test.go
Fixes: https://github.com/FoundationDB/fdb-kubernetes-operator/issues/298
> Merge affinities instead of replacing it

- controllers/cluster_controller.go
- controllers/fdb_client.go
- fdbclient/common.go
So far we've seen more issues with the cache then it solved and I'm not sure if actually helps that much.
> Remove the cache for the database

- docs/manual/index.md
This updates the user manual's index page to match the flow between the pages.
No
N/A
Yes
No
> Update the index page in the user manual

- api/v1beta1/foundationdbbackup_types_test.go
- 
Remove the need for the explicit import.
Unit tests.
No
No
> Remove the use of the explicit gomega import

- go.mod
- setup/setup.go
implemented log rotation as part of this PR. Is solved the issue #664
[x]New feature (non-breaking change which adds functionality)
- Other
NO
*If this change is …
> Enabling log file rotation

- api/v1beta1/foundationdbcluster_types.go
- controllers/add_pvcs.go
- controllers/bounce_processes.go
- controllers/check_client_compatibility.go
- controllers/choose_removals.go
- controllers/cluster_controller.go
- controllers/delete_pods_for_buggification.go
- controllers/pod_client.go
- controllers/remove_process_groups.go
- controllers/replace_failed_pods.go
- controllers/replace_misconfigured_pods.go
- controllers/update_pods.go
- controllers/update_status.go
Fix some log messages.
No.
Unit testing.
No.
No.
> Correct cluster key for logging

- setup/setup.go
Since our operator is not expecting any arguments we should report if the operator has any args.
*If this change is adding new safety checks or new …
> Check for unexpected arguments

- setup/setup.go
Reverts: https://github.com/FoundationDB/fdb-kubernetes-operator/pull/850
- Bug fix 
*If this change is adding new safety checks or new potential failure modes, have we documented and how to debug potential …
> Revert unexpected args

- api/v1beta1/foundationdbcluster_types.go
- controllers/cluster_controller.go
- controllers/controllers.go
- controllers/pod_client.go
- controllers/update_pod_config.go
- controllers/update_status.go
- controllers/update_status_test.go
- internal/error_helper.go
- internal/error_helper_test.go
Fixes: https://github.com/FoundationDB/fdb-kubernetes-operator/issues/716
Locally and e2e.
None
None.
> Add condition for sidecar unreachable

- api/v1beta1/foundationdb_status_test.go
- api/v1beta1/foundationdbcluster_types.go
- api/v1beta1/foundationdbcluster_types_test.go
- controllers/admin_client_test.go
- controllers/cluster_controller_test.go
- docs/cluster_spec.md
- e2e/cluster_test.go
1. Refactor DesiredFaultTolerance() so that it can be leveraged by chaos testing framework;
2. Refactor MinimumFaultDomains() too;
3. Make RedundancyMode an enum type.
- Minor refactor
*If this change is adding new safety checks or new potential failure …
> A few minor refactors.

- api/v1beta1/foundationdbcluster_types.go
- api/v1beta1/foundationdbcluster_types_test.go
- docs/manual/replacements_and_deletions.md
This replaces pods when they have been marked as failing for 30 minutes.
Resolves #882
No
I added unit tests for the NeedsReplacement method. I also tested in my local environment by putting the sidecar container for a pod in a crash loop state and waiting for the automatic replacement to kick in.
*Do we need to perform additional testing once this is merged, or perform in …
> Replace pods with the PodFailing condition.

- controllers/cluster_controller_test.go
- controllers/exclude_instances.go
- controllers/exclude_instances_test.go
- docs/manual/debugging.md
This adds a more permissive safety check on missing processes before we start an exclusion.
Resolves #806 
I put in hardcoded limits here, instead of adding new settings. I don't know if this is something people really need to tweak, and I'm not sure if it's worth the complexity of adding new fields to the spec.
I added unit tests for the core logic, and I ran manual tests in my dev environment.
No.
*Did you update …
> Allow exclusions when another process is missing.

- api/v1beta1/foundationdb_version.go
This disables non-blocking excludes because of concerns that missing processes can be permanently deleted before their data is re-replicated.
There are ways that we could modify the design to be safe with the current exclude behavior, but I think that will take more time and we're better off doing a patch release to protect durability.
I ran a test in my local environment of …
> Disable non-blocking excludes due to concerns about the handling of missing processes.

- .github/workflows/pull_request.yml
- .github/workflows/release.yaml
- Dockerfile
- Makefile
- setup/setup.go
Fixes: https://github.com/FoundationDB/fdb-kubernetes-operator/issues/712
- 
Unit + local 
-
-
> Add support for printing the operator version

- .github/workflows/pull_request.yml
- .golangci.yml
- controllers/suite_test.go
> link: replace golint with revive and fix a revive error

- docs/manual/debugging.md
Fixes: https://github.com/FoundationDB/fdb-kubernetes-operator/issues/935
-
-
-
-
> Fix plugin link in docs

- api/v1beta1/foundationdbcluster_types.go
- config/crd/bases/apps.foundationdb.org_foundationdbclusters.yaml
This adds additional validations to our CRD. This is part of an upcoming effort to add more validations across the board.
No.
I tested this manually in my local environment.
No.
No.
*Does this introduce new defaults that we should re-evaluate in the future?*
No.
> Add additional validations to new lists in the CRD.

- controllers/update_pod_config.go
Corrects the log level to error for all error in `UpdatePodConfig`.
-
local setup
-
-
> Correct log level in UpdatePodConfig

- api/v1beta1/foundationdbcluster_types.go
- api/v1beta1/foundationdbcluster_types_test.go
- controllers/change_coordinators_test.go
- controllers/cluster_controller.go
- controllers/cluster_controller_test.go
Fixes: https://github.com/FoundationDB/fdb-kubernetes-operator/issues/922
-
local + unit
-
-
> Make DatabaseConfiguration explicit

- Makefile
A Makefile level macro to fetch needed go dependencies during the code process. As long as a sane version of go/gmake are installed in the path, this will fetch needed dependencies. 
If the files already exist, the makefile will skip those targets completely.
I have also modified the default make goal to `all` (it was previously unset so it was picking up the first target defined in the file).
- Other
After upgrading to go 1.17 we should change `go get` to `go install`
Local testing.
Not needed but it does improve on the local development process.
- After upgrading to go 1.17 we should change `go get` to `go install`
> makefile: add a deps target to fetch all needed Go binaries

- controllers/bounce_processes.go
- controllers/update_pods.go
- internal/replacements/replacements.go
Fixes: https://github.com/FoundationDB/fdb-kubernetes-operator/issues/819
-
Unit + local tests
-
-
> Make use of the pointer util

- controllers/cluster_controller.go
- internal/monitor_conf.go
- internal/pod_client.go
- pkg/podclient/pod_client.go
Moving the interface from `internal` to `pkg` module so that it can be referenced from other scopes as well. 
- Other
not needed
no
not needed 
no …
> moving FdbPodClient from internal to pkg

- controllers/metrics.go
- controllers/metrics_test.go
Fixes: https://github.com/FoundationDB/fdb-kubernetes-operator/issues/953
-
Unit + local,
-
-
> Add metrics for excluded and removed process groups

- .github/workflows/pull_request.yml
- Makefile
- README.md
Adjust the Makefile and add some docs for additional container CLIs like nerdctl.
-
Locally
Adjusted.
None.
> Update readme and Makefile to support different container CLIs

- Dockerfile
> Fix build for CI

- docs/manual/resources.md
- docs/manual/technical_design.md
This changes some outdated language in the docs.
No.
None.
None.
Exclusively.
We should look for other fields in the routing config that are underdocumented and add more examples …
> Change services to routing in the docs.

- docs/design/bin_pack_fault_domains.md
- docs/design/imgs/fault_domain_multi_host.svg
- docs/design/imgs/increase_fault_domain_end.svg
- docs/design/imgs/increase_fault_domain_initial.svg
- docs/design/imgs/reduce_fault_domains.svg
Design for https://github.com/FoundationDB/fdb-kubernetes-operator/issues/926
-
-
-
Implement the design once approved.
> Initial design for better fault domain distribution

- config/tests/backup/base/backup.yaml
- docs/design/backup_and_restore.md
This adds a design for doing backup and restore in the operator. Much of this work has already been done in the operator, but this proposes significant new features and alterations to the existing structures.
> Initial design on backup and restore in the operator.

- .github/workflows/pull_request.yml
- Makefile
Set the env variable at the correct place.
-
-
-
-
> Correct the env setting for race detection

- api/v1beta1/foundationdbcluster_types.go
- config/crd/bases/apps.foundationdb.org_foundationdbclusters.yaml
- controllers/cluster_controller_test.go
- docs/cluster_spec.md
Add validation to prevent errors based on typos.
The drawback of this is that the CRD must be adjusted when we want to support new redundancy modes or storage engines but I think that's a fair trade off and I don't suspect to many changes in this field (and the adjustment is trivial).
Local.
-
-
> Add validation for storage engine and redundancy mode

- docs/manual/fault_domains.md
Fixes: https://github.com/FoundationDB/fdb-kubernetes-operator/issues/839
-
-
Added.
-
> Add additional docs about coordinator selection

- controllers/update_status.go
- controllers/update_status_test.go
Fixes: https://github.com/FoundationDB/fdb-kubernetes-operator/issues/1029
I consider it a bug that we added other conditions when the process group was stuck in terminating.
local testing.
-
-
> If a process group is in terminating only add that condition

- kubectl-fdb/cmd/analyze.go
- kubectl-fdb/cmd/analyze_test.go
As part of https://github.com/FoundationDB/fdb-kubernetes-operator/issues/995 it would be useful if the plugin discovers this misbehaviour and reports it in the `analyse` command.
-
Local + unit
-
-
> Add plugin support to find Pods that are not part of the cluster status spec

- kubectl-fdb/cmd/analyze.go
- kubectl-fdb/cmd/analyze_test.go
Fixes: https://github.com/FoundationDB/fdb-kubernetes-operator/issues/883
This feature is pretty useful to find the process group that blocks an operation e.g. during upgrades.
local + unit
Added in the cli command.
-
> Allow plugin to filter and ignore conditions

- CONTRIBUTING.md
Fixing our contrib guide.
Fixes: https://github.com/FoundationDB/fdb-kubernetes-operator/issues/737
> Fix markdown issues in contrib

- controllers/add_pods.go
- controllers/generate_initial_cluster_file.go
- mock-kubernetes-client/client/client.go
Fixes: https://github.com/FoundationDB/fdb-kubernetes-operator/issues/577
-
Local.
-
-
> Don't block initial cluster file generation on pending Pods

- api/v1beta1/foundationdbcluster_types.go
- api/v1beta1/foundationdbcluster_types_test.go
- config/crd/bases/apps.foundationdb.org_foundationdbclusters.yaml
- controllers/cluster_controller_test.go
- controllers/update_pod_config.go
- controllers/update_pods.go
- controllers/update_sidecar_versions.go
- controllers/update_status.go
- docs/cluster_spec.md
- docs/manual/replacements_and_deletions.md
- docs/manual/technical_design.md
- fdbclient/common.go
- internal/deprecations.go
- internal/pod_helper.go
- internal/pod_models.go
- internal/replacements/replace_failed_process_groups.go
- internal/replacements/replacements.go
- internal/replacements/replacements_test.go
Fixes: https://github.com/FoundationDB/fdb-kubernetes-operator/issues/856
This setting will affect all PodSpec changes and not only upgrades but I think this is a more consistent behaviour.
Local testing.
Updated.
-
> Replace transaction system

- api/v1beta1/foundationdb_version.go
- api/v1beta1/foundationdb_version_test.go
- setup/setup.go
> support FDB's release candidate versioning scheme

- README.md
- docs/manual/getting_started.md
Fix references from master to main.
-
-
Updated.
-
> Fix references from master to main

- api/v1beta1/foundationdbcluster_types.go
- config/crd/bases/apps.foundationdb.org_foundationdbclusters.yaml
- config/samples/deployment.yaml
Increase the length of the prefix.
-
local
-
-
> Increase process group prefix length

- api/v1beta1/foundationdb_version.go
- api/v1beta1/foundationdb_version_test.go
- fdbclient/admin_client.go
- go.mod
- go.sum
- setup/setup.go
Backport changes for release candidates into 0.51.*
-
Local testing
-
After that I'll create a 0.51.1 release.
> Backport rc1 changes

- config/samples/deployment.yaml
- config/samples/deployment/manager.yaml
- docs/changelog/v0.51.1.md
- docs/compatibility.md
- helm/fdb-operator/values.yaml
Adding changes from `0.51.1` into main branch.
locally.
-
-
> Changes for 0.51.1

- .github/workflows/pull_request.yml
Don't run tests multiple times and ensure our samples files are valid.
-
-
-
-
> Add check for samples and don't run tests when generating files

- Dockerfile
- distrolesss.dockerfile
- main.go
Remove the copied binaries as part of the 1.0 release.
Local test run.
The documentation is already updated and also our examples.
-
> Remove copy binaries

- config/samples/backup.yaml
- config/samples/cluster.yaml
- config/samples/restore.yaml
Update the hand crafted samples to `v1beta2`.
-
Locally tested all these CRDs.
-
-
> Update samples to v1beta2

- docs/changelog/v1.0.0.md
Changelog for the `1.0.0` release.
-
-
🎉 🎉 🕺 🎉 🎉
> Add changelog for 1.0.0 release

- config/development/images.yaml
- config/development/kustomization.yaml
This fixes an issue that caused the operator to fail to start in my development environment.
No.
I tested this manually in my local environment.
No.
No.
*Are there any follow-up issues that we should pursue in …
> Add an image pull policy in the development operator config.

- Makefile
- api/v1beta2/foundationdbcluster_types.go
- cmd/po-docgen/api.go
- docs/backup_spec.md
- docs/cluster_spec.md
- docs/restore_spec.md
Fixes: https://github.com/FoundationDB/fdb-kubernetes-operator/issues/1135
We can take a look later to also generate docs for our constants.
Locally. 
-
-
> Fix doc gen

- config/deployment/manager.yaml
- config/samples/deployment.yaml
- docs/changelog/v1.1.0.md
- helm/fdb-operator/values.yaml
PR with the changes for the v1.1.0 release.
> Prepare v1.1.0 release

- api/v1beta2/foundationdb_database_configuration.go
- api/v1beta2/foundationdbcluster_types.go
- api/v1beta2/foundationdbcluster_types_test.go
- controllers/admin_client_mock.go
- controllers/admin_client_test.go
- controllers/cluster_controller_test.go
This fixes the database configuration for version that doesn't support grr and commit proxies.
-
Locally (cluster with `6.3.22`) + unit tests.
-
Create a patch release.
> Fix role counts for versions prior to 7.0

- config/deployment/manager.yaml
- docs/changelog/v1.1.1.md
- helm/fdb-operator/values.yaml
> Update version to v1.1.1

- .github/workflows/pull_request.yml
Adding `7.1.0-rc1` to our test pipeline.
I would have used 7.1.0-rc2 but there is no GitHub release 🤔 
-
-
-
> Add 7.1.0-rc3 to our CI pipeline to ensure nothing explodes

- config/deployment/manager.yaml
- config/samples/deployment.yaml
- docs/changelog/v1.2.0.md
- helm/fdb-operator/values.yaml
> Prepare v1.2.0

- kubectl-fdb/cmd/analyze.go
- kubectl-fdb/cmd/analyze_test.go
Fixes: https://github.com/FoundationDB/fdb-kubernetes-operator/issues/1116
Fixes: https://github.com/FoundationDB/fdb-kubernetes-operator/issues/1117
-
Local testing + unit
-
-
> Skip Pods that are part of a process group marked for removal

- api/v1beta2/foundationdb_status_test.go
- api/v1beta2/foundationdbcluster_types_test.go
- controllers/admin_client_test.go
- controllers/cluster_controller_test.go
make use of constants for storage engine references.
Fixes #1157 
- Other
> make use of constants for storage engine references

- api/v1beta2/foundationdb_database_configuration.go
- api/v1beta2/foundationdbcluster_types.go
- api/v1beta2/foundationdbcluster_types_test.go
- config/deployment/manager.yaml
- config/samples/deployment.yaml
- controllers/admin_client_test.go
- controllers/update_database_configuration.go
- controllers/update_status.go
- docs/changelog/v1.3.1.md
- helm/fdb-operator/values.yaml
Patch release with the log count fix to enable further 7.1 development.
> prepare release 1.3.1

- internal/pod_helper.go
- internal/pod_models.go
- internal/pod_models_test.go
Fixes: https://github.com/FoundationDB/fdb-kubernetes-operator/issues/1185
-
Local + unit test.
-
-
> Fix allowTagOverride for FDB backup

- api/v1beta2/foundationdbcluster_types.go
- api/v1beta2/foundationdbcluster_types_test.go
- config/development/debug_logs.yaml
Fixes how the desired configuration is created and takes the version into account.
-
Unit test + local test.
-
-
> Fix how the desired configuration is created

- config/deployment/manager.yaml
- config/samples/deployment.yaml
- docs/changelog/v1.4.0.md
- helm/fdb-operator/values.yaml
> Prepare release 1.4.0

- .github/workflows/pull_request.yml
- Dockerfile
- distrolesss.dockerfile
Update the primary library/build version of the operator to `7.1.4`
-
Local + unit tests.
-
-
> Update build version of the operator to 7.1.4

- api/v1beta2/foundationdbcluster_types.go
- controllers/add_pods.go
- controllers/check_client_compatibility.go
- controllers/replace_failed_process_groups.go
- docs/manual/technical_design.md
- fdbclient/lock_client.go
- internal/replacements/replace_failed_process_groups.go
> Reviewing technical design

- controllers/remove_process_groups.go
- controllers/update_pods.go
- internal/fault_tolerance.go
- internal/replacements/replace_failed_process_groups.go
- pkg/podmanager/pod_lifecycle_manager.go
Fixes: #966
- Other
no
Ran make command to verify everything is working
Not needed
No
> enabling logger in fault tolerance check

- api/v1beta2/foundationdbcluster_types.go
- api/v1beta2/foundationdbcluster_types_test.go
- controllers/delete_pods_for_buggification.go
- controllers/replace_failed_process_groups_test.go
- docs/manual/replacements_and_deletions.md
- internal/replacements/replace_failed_process_groups.go
Fixes: https://github.com/FoundationDB/fdb-kubernetes-operator/issues/1201
-
Unit tests + local testing.
-
-
> Don't replace process groups if they are set into crash loop

- api/v1beta2/foundationdb_database_configuration.go
- api/v1beta2/foundationdbcluster_types.go
- api/v1beta2/image_config.go
- config/crd/bases/apps.foundationdb.org_foundationdbbackups.yaml
- config/crd/bases/apps.foundationdb.org_foundationdbclusters.yaml
Fixing linter errors
-
Ran it manually
-
-
> fixing linter errors

- controllers/remove_process_groups.go
- controllers/remove_process_groups_test.go
Fixes: https://github.com/FoundationDB/fdb-kubernetes-operator/issues/1196
-
Unit + local.
-
-
> Don't allocate extra space for include processes method

- api/v1beta2/foundationdb_process_class.go
- api/v1beta2/foundationdbcluster_types.go
- api/v1beta2/foundationdbcluster_types_test.go
- controllers/cluster_controller.go
- docs/manual/fault_domains.md
Fixes: https://github.com/FoundationDB/fdb-kubernetes-operator/issues/1244
-
Local testing.
-
-
> Add coordinator as stateful process

- controllers/update_pod_config.go
Only update the cluster status if a process group has changed to reduce the number of calls to the Kubernetes API.
-
Dev + local.
-
-
> Only update cluster status if changes are made

- .github/workflows/on-push-lint-charts.yml
- charts/fdb-operator/Chart.yaml
- ct.yaml
Fixes: https://github.com/FoundationDB/fdb-kubernetes-operator/issues/1256
We don't use kube-score.
-
-
-
> Remove unused kube-score

- charts/fdb-operator/Chart.yaml
- charts/fdb-operator/values.yaml
- config/deployment/manager.yaml
- config/samples/deployment.yaml
- docs/changelog/v1.7.0.md
Changes for the `1.7.0` release.
> Prepare v1.7.0 release

- config/deployment/manager.yaml
- config/samples/deployment.yaml
Fixes the local setup.
We should add some tests to gather those issues earlier.
Locally.
-
-
> Fix setup of deployment

- charts/fdb-operator/Chart.yaml
- charts/fdb-operator/values.yaml
- config/deployment/manager.yaml
- config/samples/deployment.yaml
- docs/changelog/v1.8.0.md
Preparing release for v1.8.0
- Other
*Did you update relevant documentation within this …
> Prepare v1.8.0 release

- api/v1beta2/foundationdbcluster_types.go
- api/v1beta2/foundationdbcluster_types_test.go
- kubectl-fdb/cmd/buggify.go
- kubectl-fdb/cmd/buggify_crash_loop.go
- kubectl-fdb/cmd/buggify_crash_loop_test.go
- kubectl-fdb/cmd/buggify_empty-monitor_conf_test.go
- kubectl-fdb/cmd/buggify_empty_monitor_conf.go
- kubectl-fdb/cmd/buggify_no_schedule.go
- kubectl-fdb/cmd/buggify_no_schedule_test.go
- kubectl-fdb/cmd/k8s_client.go
- kubectl-fdb/cmd/remove_process_group.go
- kubectl-fdb/cmd/root.go
As part of this PR I added support for buggification in plugin. This addresses #1202 
No
Added test cases and perform testing on local cluster. 
No
Added documentation for usage in plugin. 
*If this change is adding or removing subreconcilers, have we updated the core …
> Adding support for buggify in plugin

- config/tests/unified_image/images.yaml
- config/tests/unified_image/kustomization.yaml
- config/tests/unified_image/unified_image_role.yaml
Those changes add the required RBAC settings to run the unified image.
-
Locally.
-
-
> Add changes for unified image support

- api/v1beta2/foundationdb_database_configuration.go
- config/crd/bases/apps.foundationdb.org_foundationdbclusters.yaml
> Add storage engine type.

- controllers/remove_incompatible_processes.go
We only want to run the sub reconciler for incompatible processes once the cluster was configured otherwise we end up with a possible race condition that blocks the initial creation of the cluster.
-
Locally + e2e tests.
-
-
> Ensure the remove incompatible processes subreconciler is not blocking

- .github/workflows/pull_request.yml
Fixes: https://github.com/FoundationDB/fdb-kubernetes-operator/issues/1326
-
CI pipeline:
```text
/usr/bin/docker buildx build --build-arg TAG=3bd50d56c85d50a4cda127b87a9485c759a930f5 --file ./Dockerfile --iidfile /tmp/docker-build-push-wMWPAG/iidfile --tag foundationdb/fdb-kubernetes-operator:latest --metadata-file /tmp/docker-build-push-wMWPAG/metadata-file ./
```
-
-
> Put correct syntax to get SHA

- docs/manual/customization.md
Given that the feature has remained in an experimental state for over a year, and we passed the 1.0 release without making it the default, I think it's worth changing our stance.
No.
None.
No.
Yes.
*Are there any follow-up issues that we should …
> Update the documentation on per-pod service IPs to reflect where the feature stands.

- api/v1beta2/foundationdb_version.go
- controllers/admin_client_test.go
- controllers/backup_controller_test.go
- controllers/check_client_compatibility.go
- controllers/cluster_controller.go
- controllers/cluster_controller_test.go
- controllers/update_sidecar_versions_test.go
- internal/pod_models_test.go
Fixes: https://github.com/FoundationDB/fdb-kubernetes-operator/issues/1266
-
Unit tests + local testing.
-
Creating a downgrade test in out test suite.
> Allow downgrads of compatible versions

- foundationdb-kubernetes-sidecar/Readme.md
Fix a broken link in the sidecar folder README.md
Documentation
no
N/A
No
N/A
N/A
N/A
*If this change is adding new safety checks or new potential failure modes, have we documented and how to debug potential …
> Fix broken link in sidecar README.md

- controllers/bounce_processes.go
- controllers/bounce_processes_test.go
- controllers/remove_incompatible_processes.go
- controllers/remove_incompatible_processes_test.go
- controllers/remove_process_groups.go
- internal/fault_tolerance.go
- internal/fault_tolerance_test.go
- internal/foundationdb_status.go
- internal/foundationdb_status_test.go
> Make remove incompatible processes more pessimistic

- .github/workflows/pull_request.yml
- .github/workflows/release.yaml
- Dockerfile
Fixes: https://github.com/FoundationDB/fdb-kubernetes-operator/issues/1422
-
e2e tests.
-
-
> Upgrade used go version to 1.19.3

- mock-kubernetes-client/client/client.go
- mock-kubernetes-client/client/client_test.go
Allow to define custom create hooks in mock client.
-
Local testing.
-
-
> Allow to define custom create hooks in mock client

- charts/fdb-operator/Chart.yaml
- charts/fdb-operator/values.yaml
- config/deployment/manager.yaml
- config/samples/deployment.yaml
- docs/changelog/v1.10.0.md
Create new release 1.10.0
- Other
-
Pipeline run here.
-
-
> Prepare release 1.10.0

- charts/fdb-operator/Chart.yaml
- charts/fdb-operator/values.yaml
- config/deployment/manager.yaml
- config/samples/deployment.yaml
- docs/changelog/v1.11.0.md
Releasing Operator version 1.11.0
- Other
*If this change is adding or removing subreconcilers, have …
> Prepare release 1.11.0

- config/tests/dns/client.yaml
- config/tests/dns/dns.yaml
- docs/manual/customization.md
fixes: https://github.com/FoundationDB/fdb-kubernetes-operator/issues/1419
-
Local testing
Added.
-
> Add docs for DNS setup

- controllers/update_labels.go
- controllers/update_status.go
Small code clean up when I was reading some code.
- Other
-
Locally with unit tests.
-
-
> Small clean up

- charts/fdb-operator/Chart.yaml
- charts/fdb-operator/values.yaml
- config/deployment/manager.yaml
- config/samples/deployment.yaml
- docs/changelog/v1.12.0.md
> prepare release v1.12.0

- controllers/backup_controller_test.go
- controllers/bounce_processes_test.go
- controllers/change_coordinators_test.go
- controllers/cluster_controller.go
- controllers/cluster_controller_test.go
- controllers/maintenance_mode_checker.go
- controllers/remove_process_groups.go
- controllers/remove_process_groups_test.go
- controllers/restore_controller_test.go
- fdbclient/admin_client.go
- fdbclient/admin_client_test.go
- internal/foundationdb_status.go
- internal/foundationdb_status_test.go
- pkg/fdbadminclient/admin_client.go
- pkg/fdbadminclient/mock/admin_client_mock.go
This is testing the waters for doing this in a broader way throughout the codebase
No (intended) functional change.
- Other
The unit tests still pass.  No further testing should be needed.
N/A
The sets-stored-as-arrays pattern is fairly common in this code base, and makes it difficult to read (and verbose).  We should consider modifying more logic in the same way.  (The runtime performance impact should be negligible).
> Convert some lists in admin_client_mock to sets.  

- scripts/setup_e2e.sh
This reverts commit edd0fa0a9bf9a9ab7a36f2f693ebf20324e9063f.
I made a stupid mistake that I accidentally pushed the commit to main branch. 
This PR reverts the commit.
- Other
*Do we need to perform …
> Revert "Add recommended running env for setup_e2e.sh"

- controllers/bounce_processes.go
- controllers/bounce_processes_test.go
Fixes an issue with the buggify restart option.
-
Unit test and e2e test.
-
-
> Fix bug in ignore restart logic

- controllers/delete_pods_for_buggification.go
- controllers/delete_pods_for_buggification_test.go
- controllers/replace_failed_process_groups_test.go
- internal/deprecations.go
- internal/pod_models.go
- internal/pod_models_test.go
- internal/replacements/replace_failed_process_groups.go
Follow up for https://github.com/FoundationDB/fdb-kubernetes-operator/pull/1472
> Migrate old CrashLoop to new Spec

- charts/fdb-operator/Chart.yaml
- charts/fdb-operator/values.yaml
- config/deployment/manager.yaml
- config/samples/deployment.yaml
- docs/changelog/v1.13.0.md
prepare the next release
- Other
*If this change is adding or removing subreconcilers, have we …
> prepare release v1.13.0

- charts/fdb-operator/Chart.yaml
- charts/fdb-operator/values.yaml
- config/deployment/manager.yaml
- config/samples/deployment.yaml
- docs/changelog/v1.14.0.md
Prepare next release
- Other
*If this change is adding or removing subreconcilers, have we updated …
> prepare release v1.14.0

- internal/replacements/replace_failed_process_groups.go
Fixes: https://github.com/FoundationDB/fdb-kubernetes-operator/issues/1315
Current tests already capture everything.
-
-
> Log replacements that the operator would do if the replacement limit would not be blocking it

- README.md
Fixes: https://github.com/FoundationDB/fdb-kubernetes-operator/issues/1357
-
-
-
-
> Document DoK talk

- docs/manual/imgs/upgrade_mechanism.svg
- docs/manual/index.md
- docs/manual/technical_design.md
- docs/manual/upgrades.md
- kubectl-fdb/cmd/remove_process_group.go
Fixes: https://github.com/FoundationDB/fdb-kubernetes-operator/issues/1473
-
-
Updated.
-
> Initial round of documenting the upgrade process

- controllers/remove_incompatible_processes.go
There is no benefit in waiting until the cluster is up for a certain amount of time. Waiting for a specific uptime brings the risk that the cluster might be in a degraded state for a longer time. We initially added this check when we were experimenting with this new subreonciler. Now we have a check to ensure we only replace Pods that are part of the cluster and are not reporting to the cluster (the assumption here is that if they are missing they probably run on the incompatible version).
-
Unit tests and e2e tests will be running.
-
-
> Remove the minimum uptime check in the replace incompatible connections subreconciler

- charts/fdb-operator/Chart.yaml
- charts/fdb-operator/values.yaml
- config/deployment/manager.yaml
- config/samples/deployment.yaml
- docs/changelog/v1.14.0.md
- docs/changelog/v1.15.0.md
prepare release v1.15.0
- Other
*If this change is adding or removing subreconcilers, have we …
> prepare release v1.15.0

- api/v1beta2/foundationdbcluster_types.go
- controllers/bounce_processes.go
- controllers/bounce_processes_test.go
Fixes: https://github.com/FoundationDB/fdb-kubernetes-operator/issues/1535
-
Unit test, we should also add a e2e test for this.
-
-
> Fix upgrade logic for multiple storage server per Pod

- api/v1beta2/foundationdbcluster_types.go
- config/crd/bases/apps.foundationdb.org_foundationdbclusters.yaml
Add kubebuilder validations for a couple of entries
- Other
Used kubectl --dry-run to apply the new crd's
*If this …
> Add kube builder validation checks for a couple of entries.

- charts/fdb-operator/Chart.yaml
- charts/fdb-operator/values.yaml
- config/deployment/manager.yaml
- config/samples/deployment.yaml
- docs/changelog/v1.16.0.md
> prepare release v1.16.0

- kubectl-fdb/Readme.md
Fixes: https://github.com/FoundationDB/fdb-kubernetes-operator/issues/1504
-
I ran the commands locally.
Added.
-
> Install checksum step for kubectl fdb plugin

- .github/workflows/pull_request.yml
- .github/workflows/release.yaml
- Dockerfile
Fixes: https://github.com/FoundationDB/fdb-kubernetes-operator/issues/1540
release notes for 1.19.8 https://go.dev/doc/devel/release#go1.19.8 (contains multiple bug and security fixes).
- Other
Unit tests + e2e tests.
-
-
> Update to go 1.19.8

- kubectl-fdb/cmd/k8s_client.go
This fixes a bug where we would have a bunch of blank entries in the node list before the real nodes.
No.
I ran the command from my local build.
No.
No.
*Are there any follow-up issues that we should pursue in …
> Fix the way we build the node list in the getNodes function.

- docs/manual/warnings.md
Fixes: https://github.com/FoundationDB/fdb-kubernetes-operator/issues/956
-
-
Added.
-
> Correct statement about setting affinities

- kubectl-fdb/Readme.md
Add details of required tools for installing plugin.
-
Manual test run.
-
-
> Correct plugin installation steps

- docs/manual/technical_design.md
Fixes: https://github.com/FoundationDB/fdb-kubernetes-operator/issues/1549
-
-
Added.
-
> Add docs for exclusion handling in the operator

- docs/manual/upgrades.md
Documentation for the possible issue that some fdbserver processes are not joining the FDB cluster during an upgrade.
-
-
Added.
-
> Document the case during an upgrade where the fdbserver is not joining the cluster

- api/v1beta2/foundationdb_status.go
- api/v1beta2/foundationdbcluster_types.go
- api/v1beta2/zz_generated.deepcopy.go
- config/crd/bases/apps.foundationdb.org_foundationdbclusters.yaml
- controllers/check_client_compatibility.go
- controllers/check_client_compatibility_test.go
- controllers/cluster_controller_test.go
- docs/cluster_spec.md
- e2e/fixtures/fdb_cluster_specs.go
- pkg/fdbadminclient/mock/admin_client_mock.go
Fixes: https://github.com/FoundationDB/fdb-kubernetes-operator/issues/1542
-
Unit tests + e2e tests.
-
-
> Add LogGroup type with specific check

- fdbclient/admin_client.go
If we exclude a stateful process, the exclusion can take longer than the timeout, resulting in a timeout error. If we run the exclude command with the backoff we potentially trigger multiple exclusions for the same set of addresses, since the operator cannot differentiate between the exclude command timing out (exclusion is not started) and the exclusion is started but the processes still have data and it's not safe to delete them. One workaround would be to check the cluster status after the exclusion commands but this would be a rather expensive check compared to running with the highest timeout.
-
Unit tests + e2e tests that will run.
I'm planning to work on …
> Run the exclude command with the highest timeout

- docs/manual/fault_domains.md
- docs/manual/operations.md
- internal/pod_models.go
Fixes: https://github.com/FoundationDB/fdb-kubernetes-operator/issues/1110
-
-
Added.
-
> Document localities used and set by the operator

- e2e/test_operator_ha_upgrades/operator_ha_upgrade_test.go
- e2e/test_operator_upgrades/operator_upgrades_test.go
This PR tests the following upgrade scenarios:
- Upgrading a cluster when no remote storage processes are restarted
- Upgrading a cluster with a pending pod
- Other (testing related)
No.
Manual testing (ran the tests locally).
These tests will need to be run as part of regression testing.
*If this change is adding or removing subreconcilers, have we updated the core …
> Test more upgrade scenarios

- e2e/README.md
There was a typo in the e2e README for one of the commands.
- Other
*If this change is adding or …
> Fix e2e docs typo

- pkg/fdbadminclient/mock/admin_client_mock.go
- pkg/fdbadminclient/mock/admin_client_mock_test.go
This is a small bug fix to add the additional processes only once. The logic was working before, because we use a map, so we added the same process multiple times into the map with the same key.
-
Unit test.
-
-
> Add the additional processes only once and not multiple times

- api/v1beta2/foundationdb_status.go
- api/v1beta2/foundationdbcluster_types.go
- config/crd/bases/apps.foundationdb.org_foundationdbclusters.yaml
- controllers/maintenance_mode_checker_test.go
- controllers/update_status.go
- controllers/update_status_test.go
- docs/cluster_spec.md
- fdbclient/admin_client.go
- pkg/fdbadminclient/mock/admin_client_mock.go
Adding CRD validation for the fault domain type.
-
Unit tests.
-
-
> Add FaultDomain as a typed string

- api/v1beta2/foundationdbcluster_types.go
- api/v1beta2/foundationdbcluster_types_test.go
- config/crd/bases/apps.foundationdb.org_foundationdbclusters.yaml
- controllers/add_pods.go
- controllers/add_process_groups.go
- controllers/add_pvcs.go
- controllers/add_services.go
- controllers/cluster_controller_test.go
- controllers/update_pods.go
- controllers/update_status.go
- internal/pod_helper.go
- internal/replacements/replacements.go
- internal/replacements/replacements_test.go
- pkg/podmanager/fdb_process_group.go
Fixes: https://github.com/FoundationDB/fdb-kubernetes-operator/issues/1619
This is a breaking change if someone is consuming the PodManager
-
Unit tests.
-
-
> Simplify the parsing of the ID number for the process group ID

- e2e/Makefile
- e2e/README.md
- e2e/fixtures/cluster_config.go
- e2e/fixtures/cluster_config_test.go
- e2e/fixtures/factory.go
- e2e/fixtures/fdb_cluster_specs.go
- e2e/fixtures/fdb_operator_client.go
- e2e/fixtures/options.go
- e2e/scripts/setup_e2e.sh
- e2e/scripts/start_kind_cluster.sh
- e2e/test_operator_upgrades/operator_upgrades_test.go
Fixes: https://github.com/FoundationDB/fdb-kubernetes-operator/issues/1631
Install helm if missing to let CI pipeline succeed.
-
Ci tests will be running.
-
Update the CI image to include helm and remove this step.
> Fix kind e2e tests.

- .github/workflows/release.yaml
- Dockerfile
Updating to bookworm to match the new gaoling.1.19.10 base image.
-
Did a manual run + build.
-
-
> Update base image for operator

- controllers/update_status.go
There is no reason to put all processes into the map.
-
We should wait for https://github.com/FoundationDB/fdb-kubernetes-operator/pull/1676 to be merged.
-
We should verify all other places where we iterate over all processes.
> Reduce the size of the process map by selecting only processes in the right DC

- e2e/fixtures/ha_fdb_cluster.go
- e2e/test_operator_ha_upgrades/operator_ha_upgrade_test.go
Adding the same checks as we did here: https://github.com/FoundationDB/fdb-kubernetes-operator/pull/1672 for HA clusters.
- Other
-
-
-
> Extend HA upgrade test to check that process groups are only replaced once

- Makefile
- e2e/fixtures/certificate_generator.go
- e2e/fixtures/chaos_common.go
- e2e/fixtures/chaos_network.go
- e2e/fixtures/cluster_config.go
- e2e/fixtures/factory.go
- e2e/fixtures/fdb_operator_fixtures.go
- e2e/fixtures/ha_fdb_cluster.go
- e2e/fixtures/kubernetes_fixtures.go
- e2e/fixtures/options.go
- e2e/fixtures/pods.go
- e2e/fixtures/status.go
- e2e/fixtures/test_runner.go
- e2e/fixtures/upgrade_test_configuration.go
- e2e/test_operator_ha_upgrades/operator_ha_upgrade_test.go
- e2e/test_operator_upgrades/operator_upgrades_test.go
Allow a small buffer for automatic replacements during an upgrade.
-
Manual run.
-
-
> Add a small buffer for the expected process counts for automatic replacements

- e2e/test_operator_ha_upgrades/operator_ha_upgrade_test.go
The unstable network link can make the cluster go unavailable for some time. This can lead to some test failures which are not introduced by the operator code but the test setup.
-
Did a manual run.
-
-
> Disable availability check for unstable network test

- pkg/fdbadminclient/mock/admin_client_mock.go
- pkg/fdbadminclient/mock/admin_client_mock_test.go
- pkg/fdbadminclient/mock/suite_test.go
Fixes: https://github.com/FoundationDB/fdb-kubernetes-operator/issues/1698
- Other
-
Unit tests.
-
-
> Allow to mock an error in the mock client

- internal/removals/remove.go
- pkg/fdbstatus/status_checks.go
- pkg/fdbstatus/status_checks_test.go
Add logging for exclusion skip if active generations are more than 1.
- Other
-
Verified in unit test.
-
-
> Add some more logging if exclusions check is skipped

- docs/design/node_taint_eviction.md
- docs/manual/replacements_and_deletions.md
Update design doc for the taint feature, because we changed the design during the implementation;
Update the user manual to add the taint feature. 
None
I compiled it locally to ensure document is compiled with the right format.
> Update taint feature design doc and user manual

- e2e/fixtures/factory.go
Fixes: https://github.com/FoundationDB/fdb-kubernetes-operator/issues/1707 (the actual ask of exposing the CoreV1() client is not required with this change).
-
unit tests and e2e test run.
-
-
> Add a method to the e2e factory to collect logs for a Pod

- api/v1beta2/foundationdbcluster_types.go
- config/crd/bases/apps.foundationdb.org_foundationdbclusters.yaml
Adds CRD maxItems validation.
-
Local testing.
N/A
-
> Fix linting for status fields that are lists

- docs/manual/warnings.md
Fixes: https://github.com/FoundationDB/fdb-kubernetes-operator/issues/1679
-
N/A
Added.
-
> Document used FDB ports

- docs/changelog/v1.21.0.md
> prepare release v1.21.0

- controllers/update_status.go
- controllers/update_status_test.go
- e2e/test_operator/operator_test.go
Fixes: https://github.com/FoundationDB/fdb-kubernetes-operator/issues/1747
-
Added unit and e2e tests.
-
-
> Update fault domain detection for multiple processes in a single Pod

- docs/changelog/v1.22.0.md
> prepare release v1.22.0

- e2e/fixtures/kubernetes_fixtures.go
- e2e/fixtures/singleton.go
Allow to create a new controller runtime client from the test framework.
-
-
In code.
-
> Allow to create controller runtime from different context

- e2e/fixtures/fdb_cluster.go
- e2e/test_operator/operator_test.go
-
e2e tests will be running.
-
-
> Add namespace parameter for PVC query and move process count validation into common method

- charts/fdb-operator/Chart.yaml
- charts/fdb-operator/values.yaml
- config/deployment/manager.yaml
- config/samples/deployment.yaml
- docs/changelog/v1.23.0.md
- docs/manual/customization.md
- e2e/README.md
- e2e/scripts/setup_e2e.sh
- sample-apps/fdb-profile-analyzer/Dockerfile
- scripts/setup_e2e.sh
> prepare release v1.23.0

- e2e/fixtures/factory.go
Exposing context
- Other
No
N/A
*If this change is adding new safety checks or new potential failure modes, have we documented and how to debug potential issues?*
N/A
*Are there any follow-up issues that we …
> exposing context

- charts/fdb-operator/Chart.yaml
- charts/fdb-operator/values.yaml
- config/deployment/manager.yaml
- config/samples/deployment.yaml
- docs/changelog/v1.24.0.md
> prepare release v1.24.0

- api/v1beta2/foundationdbcluster_types.go
- api/v1beta2/foundationdbcluster_types_test.go
- e2e/test_operator_ha_upgrades/operator_ha_upgrade_test.go
- fdbclient/lock_client.go
Fixes: https://github.com/FoundationDB/fdb-kubernetes-operator/issues/1795
This bug was introduced in the migration from `v1beta1` to `v1beta2`.
e2e test will be running and I will add additional unit tests.
-
-
> Fix the lock ID to return the correct value

- e2e/test_operator/operator_test.go
Use the correct value used during test.
-
Ran e2e tests manually.
-
-
> Correct the value used for testing

- controllers/choose_removals.go
- e2e/test_operator/operator_test.go
- e2e/test_operator_ha_upgrades/operator_ha_upgrade_test.go
Fixes: https://github.com/FoundationDB/fdb-kubernetes-operator/issues/1816
-
Running e2e tests.
-
-
> Investigate HA test failures

- charts/fdb-operator/Chart.yaml
- charts/fdb-operator/values.yaml
- config/deployment/manager.yaml
- config/samples/deployment.yaml
- docs/changelog/v1.26.0.md
> prepare release v1.26.0

- docs/manual/fault_domains.md
Fixes: https://github.com/FoundationDB/fdb-kubernetes-operator/issues/1819
-
-
Updated.
-
> Update docs on fault domain and coordinators

- e2e/test_operator_velocity/operator_velocity_test.go
Increase the knob rollout time to take the release of the lock into account.
-
Manual test.
-
-
> Increase knob rollout time

- docs/design/replacement_buckets.md
Fixes: https://github.com/FoundationDB/fdb-kubernetes-operator/issues/1316
-
-
-
I will write another design doc for allowing replacements on a fault domain basis.
> Initial doc for replacement buckets

- e2e/test_operator_upgrades_variations/operator_upgrades_variations_test.go
Fixes: https://github.com/FoundationDB/fdb-kubernetes-operator/issues/1836
-
Ran e2e test.
-
-
> Add more logging for upgrade test failure

- docs/manual/customization.md
- docs/manual/warnings.md
- internal/deprecations.go
- internal/deprecations_test.go
- internal/pod_models_test.go
Fixes: https://github.com/FoundationDB/fdb-kubernetes-operator/issues/627
- Other
-
-
Updated.
-
> Update docs about resource limits and update defaults to 4GB for a minimal cluster

- e2e/test_operator/operator_test.go
Fixes: https://github.com/FoundationDB/fdb-kubernetes-operator/issues/1775
- Other
-
Ran test manually:
```text
[AfterSuite]
/Users/jscheuermann/go/src/github.com/FoundationDB/fdb-kubernetes-operator/e2e/test_operator/operator_test.go:92
2023/10/17 16:05:30 start cleaning up chaos mesh client with 2 experiment(s)
2023/10/17 16:05:30 Start deleting gx7w92g4t6xwqrup6hrh4jep7q7piybc
2023/10/17 16:05:30 Start deleting zglvc2otbx1xwigasufzw5zyatqvsge2
2023/10/17 16:05:31 Chaos zglvc2otbx1xwigasufzw5zyatqvsge2 is deleted.
2023/10/17 16:05:31 finished all tests, start deleting namespace jscheuermann-kh6meurn
[AfterSuite] PASSED [16.015 seconds]
[ReportAfterSuite] Autogenerated ReportAfterSuite …
```
> Add e2e test to make sure processes in maintenance zone are ignored

- charts/fdb-operator/Chart.yaml
- charts/fdb-operator/values.yaml
- config/deployment/manager.yaml
- config/samples/deployment.yaml
- docs/changelog/v1.27.0.md
> prepare release v1.27.0

- e2e/fixtures/fdb_cluster_specs.go
- e2e/test_operator_upgrades/operator_upgrades_test.go
Correct the way the test framework handles limits and requests for containers.
-
Manual e2e test run.
-
-
> Fix resources limits for non performance tests

- controllers/exclude_processes.go
- controllers/exclude_processes_test.go
- internal/removals/remove.go
Otherwise we might hit a case where the exclusion is blocked by one missing process.
Unit tests.
-
We have to add a dedicated e2e tests for such a scenario.
> Add some buffer for the exclusion logic to mitigate dead locks

- api/v1beta1/foundationdb_database_configuration.go
- api/v1beta2/foundationdb_database_configuration.go
- api/v1beta2/foundationdb_version.go
- config/crd/bases/apps.foundationdb.org_foundationdbclusters.yaml
fixes #1856 
Added redwood-1
Not sure of the impact of adding a new value to the spec
*If this change is adding new safety checks or new potential failure modes, have we documented and how to debug potential issues?*
*Are there any follow-up issues that …
> Add support for redwood storage engine

- controllers/update_status_test.go
Remove some steps in the test setup for update status.
- Other
-
Unit test.
-
-
> Simplify test setup

- api/v1beta2/foundationdb_process_class.go
- fdbclient/admin_client_test.go
- fdbclient/command_runner.go
- internal/removals/remove.go
- internal/removals/remove_test.go
- pkg/fdbstatus/status_checks.go
- pkg/fdbstatus/status_checks_test.go
Otherwise we might issue an exclusions with the IP address.
-
I will add some additional unit tests for this behaviour.
-
-
> If locality-based exclusions are enabled, only make use of the locality

- charts/fdb-operator/Chart.yaml
- charts/fdb-operator/values.yaml
- config/deployment/manager.yaml
- config/samples/deployment.yaml
- docs/changelog/v1.28.0.md
> prepare release v1.28.0

- e2e/fixtures/pods.go
- e2e/test_operator/operator_test.go
- e2e/test_operator_upgrades/operator_upgrades_test.go
We saw some cases in our e2e tests where it seems like the finalizer was not set and the Pod was removed. The changes should make sure that the finalizer is updated.
-
-
-
> Make sure the set finalizer method actually set the finalizer

- controllers/update_status.go
- e2e/fixtures/factory.go
- e2e/fixtures/fdb_operator_fixtures.go
- internal/monitor_conf.go
- internal/monitor_conf_test.go
Refactor the check process method and remove some duplicate work. 
- Other
-
Unit tests.
-
-
> Refactor the check process method and remove some duplicate work

- api/v1beta2/foundationdbcluster_types.go
- controllers/exclude_processes.go
- controllers/exclude_processes_test.go
- e2e/fixtures/factory.go
- e2e/fixtures/fdb_cluster.go
- e2e/fixtures/kubernetes_fixtures.go
- e2e/test_operator/operator_test.go
- e2e/test_operator_ha/operator_ha_test.go
- e2e/test_operator_ha/suite_test.go
Improve exclusion check to make sure that enough processes are up and running.
-
Added a new e2e test suite for HA clusters with a dedicated test.
-
-
> Improve exclusion check to make sure that enough processes are up and running

- api/v1beta2/foundationdbcluster_types.go
- api/v1beta2/foundationdbcluster_types_test.go
fixes: https://github.com/FoundationDB/fdb-kubernetes-operator/issues/1855
*
Added unit test
*
*
> fixing error in AllAddressesExcluded

- config/tests/three_data_hall/Readme.md
- config/tests/three_data_hall/create.bash
- config/tests/three_data_hall/delete.bash
- config/tests/three_data_hall/functions.bash
Allow to set the namespace in the three data hall example.
- Other
-
Created a cluster in a different namespace with this setup.
Added.
-
> Allow to set the namespace in the three data hall example

- controllers/add_pods.go
- controllers/cluster_controller.go
- controllers/controllers.go
- docs/manual/debugging.md
Fixes: https://github.com/FoundationDB/fdb-kubernetes-operator/issues/852
-
N/A
Updated.
-
> Document the logging fields that are commonly used in the operator logging statements

- controllers/cluster_controller.go
- kubectl-fdb/cmd/cordon.go
- kubectl-fdb/cmd/k8s_client.go
Otherwise the plugin complains that the field is not indexed.
-
Ran a manual test with the cordon command.
-
-
> Add the informer for getting a Pod by the node name

- charts/fdb-operator/Chart.yaml
- charts/fdb-operator/values.yaml
- config/deployment/manager.yaml
- config/samples/deployment.yaml
- docs/changelog/v1.30.0.md
> prepare release v1.30.0

- charts/fdb-operator/Chart.yaml
- charts/fdb-operator/values.yaml
- config/deployment/manager.yaml
use `yq` to format yaml files that are modified during the release process
> format files changed during release with yq

- e2e/fixtures/fdb_operator_client.go
This allows to test the unified image as init container to copy binaries and libraries into the application container.
-
Did a manual test.
-
-
> Add support for using the unified image as init container for the operator

- e2e/test_operator_maintenance_mode/operator_maintenance_mode_test.go
Adding 2 additional tests for the maintenance mode with the operator.
- Other
-
Ran those test manually.
-
-
> Add additional tests for the maintenance mode

- .github/workflows/pull_request.yml
- .github/workflows/release.yaml
- Dockerfile
Change base image to Rocky9 Linux.
- Other
-
Manual test runs and CI run.
-
-
> Change base image to rocky9

- charts/fdb-operator/Chart.yaml
- charts/fdb-operator/values.yaml
- config/deployment/manager.yaml
- config/samples/deployment.yaml
- docs/changelog/v1.32.0.md
> prepare release v1.32.0

- controllers/update_database_configuration.go
- pkg/fdbstatus/status_checks.go
- pkg/fdbstatus/status_checks_test.go
The intention of this PR is to make sure the operator only trigger a configuration change if it is safe to do so.
-
Added unit tests and CI will run e2e tests.
Will be updated.
-
> Make sure we test the status conditions before running the configure command

- fdbclient/admin_client.go
Reduce the logging verbosity from the admin client and correct the type of the timeout error.
-
Ran existing tests and a manual deployment.
-
-
> Only log if the command was not timing out

- controllers/update_status.go
- docs/manual/replacements_and_deletions.md
Correct the docs for taint replacement and improve the log output.
-
I copied the example and tested it on a test cluster.
-
-
> Correct docs and improve log output

- charts/fdb-operator/Chart.yaml
- charts/fdb-operator/values.yaml
- config/deployment/manager.yaml
- config/samples/deployment.yaml
- docs/changelog/v1.33.0.md
> prepare release v1.33.0

- charts/fdb-operator/Chart.yaml
- charts/fdb-operator/values.yaml
- config/deployment/manager.yaml
- config/samples/deployment.yaml
- docs/changelog/v1.34.0.md
> prepare release v1.34.0

- README.md
Fixes: https://github.com/FoundationDB/fdb-kubernetes-operator/issues/789
-
N/A
Added.
-
> Add the known limitation that the FDB cluster is only reachable from within Kubernetes

- README.md
- docs/compatibility.md
- docs/manual/customization.md
- docs/manual/debugging.md
- docs/manual/fault_domains.md
- docs/manual/getting_started.md
- docs/manual/operations.md
- docs/manual/operator_customization.md
- docs/manual/replacements_and_deletions.md
- docs/manual/resources.md
- docs/manual/scaling.md
- docs/manual/tls.md
- docs/manual/warnings.md
- e2e/README.md
Updated a few sections in our documentation to improve the wording and the expectations.
-
Not needed.
Updated.
-
> Improve documentation

- charts/fdb-operator/Chart.yaml
- charts/fdb-operator/values.yaml
- config/deployment/manager.yaml
- config/samples/deployment.yaml
- docs/changelog/v1.35.0.md
> prepare release v1.35.0

- docs/manual/getting_started.md
Fixes: https://github.com/FoundationDB/fdb-kubernetes-operator/issues/1958
-
-
Updated the docs.
-
> Add additional documentation for the copied cluster-file

- charts/fdb-operator/Chart.yaml
- charts/fdb-operator/values.yaml
- config/deployment/manager.yaml
- config/samples/deployment.yaml
- docs/changelog/v1.36.0.md
> prepare release v1.36.0

- controllers/cluster_controller.go
- setup/setup.go
Fixes: https://github.com/FoundationDB/fdb-kubernetes-operator/issues/1996
-
Ran unit tests and e2e tests will be running by CI.
-
-
> Remove old indexer

- e2e/README.md
- e2e/fixtures/fdb_data_loader.go
- e2e/fixtures/fdb_operator_client.go
- e2e/test_operator/operator_test.go
Document how to run e2e tests with the new unified image.
-
Tested the command in a manual run.
Updated.
-
> Document how to run e2e tests with the unified image

- charts/fdb-operator/Chart.yaml
- charts/fdb-operator/values.yaml
- config/deployment/manager.yaml
- config/samples/deployment.yaml
- docs/changelog/v1.38.0.md
> prepare release v1.38.0

- .github/workflows/pull_request.yml
- .github/workflows/release.yaml
- Dockerfile
Fixes: https://github.com/FoundationDB/fdb-kubernetes-operator/issues/2012
-
-
-
> Update to go 1.22.3

- e2e/test_operator_velocity/operator_velocity_test.go
Adding a new e2e test for a knob rollout with a process group that must be replaced.
- Other
-
-
-
> Add a new e2e test for knob rollout with process group replacement

- e2e/test_operator/operator_test.go
We saw a few times cases where the test was timing out. Adding the force reconcile could help here.
-
CI.
-
-
> Improve reliability of the reset maintenance test

- e2e/fixtures/fdb_operator_client.go
Unify operator args for the sidecar and unified image approach
-
Manual run.
-
-
> Unify operator args for the sidecar and unified image approach

- charts/fdb-operator/Chart.yaml
- charts/fdb-operator/values.yaml
- config/deployment/manager.yaml
- config/samples/deployment.yaml
- docs/changelog/v1.39.0.md
> prepare release v1.39.0

- docs/manual/replacements_and_deletions.md
- docs/manual/upgrades.md
just additional documentation note to help clarify things
*If this change is adding new safety checks or new potential failure modes, have we documented and how to debug potential issues?*
*Are …
> quick doc addition to help emphasize recreation vs replacement terms

- e2e/test_operator/operator_test.go
Make sure to retry setting the process group under maintenance
We have seen one case in the nightlies where the timestamp was empty, the new logic should help in this case.
Ran the tests manually.
-
-
> Make sure to retry setting the process group under maintenance

- charts/fdb-operator/Chart.yaml
- charts/fdb-operator/values.yaml
- config/deployment/manager.yaml
- config/samples/deployment.yaml
- docs/changelog/v1.41.0.md
> prepare release v1.41.0

- config/samples/backup.yaml
- config/samples/client.yaml
- config/samples/cluster.yaml
- config/samples/restore.yaml
- config/tests/backup/base/backup.yaml
- config/tests/base/cluster.yaml
- config/tests/multi_dc/final.yaml
- config/tests/multi_dc/stage_1.yaml
- config/tests/multi_kc/final.yaml
- config/tests/multi_kc/stage_1.yaml
- config/tests/three_data_hall/final.yaml
- config/tests/three_data_hall/stage_1.yaml
- config/tests/unified_image/images.yaml
Update all examples to make use of the `imageType`.
-
-
-
-
> Update examples for imageType setting

- e2e/fixtures/fdb_data_loader.go
- e2e/test_operator/operator_test.go
e2e test update for: https://github.com/apple/foundationdb/pull/11486
- Other
-
Ran the test manually:
```text
[AfterSuite]
/Users/jscheuermann/go/src/github.com/FoundationDB/fdb-kubernetes-operator/e2e/test_operator/operator_test.go:101
[ReportAfterSuite] PASSED [0.016 seconds]
Ran 1 of 54 Specs in 450.677 seconds
SUCCESS! -- 1 Passed | 0 Failed | 11 Pending | 42 Skipped
PASS | FOCUSED
FAIL    github.com/FoundationDB/fdb-kubernetes-operator/e2e/test_operator       451.115s
FAIL
```
-
-
> Make sure to test if the fdb-kubernetes-monitor is able to update the annotation after the partition

- charts/fdb-operator/templates/rbac/rbac_role_binding.yaml
Bug fix: Added required field namespace for global mode
> Bug fix: Added required field namespace for global mode

- e2e/fixtures/chaos_stress.go
- e2e/fixtures/factory.go
- e2e/fixtures/fdb_data_loader.go
- e2e/fixtures/fdb_operator_fixtures.go
- e2e/fixtures/ha_fdb_cluster.go
- e2e/fixtures/kubernetes_fixtures.go
- e2e/test_operator/operator_test.go
Add the test suite name to the namespace and name of the created cluster. Also add a new chaos mesh experiment and add a new pending test (I have to make some changes in another PR to get it working).
- Other
-
Ran the operator tests manually.
-
-
> Add test suite name into namespace and cluster name to reduce conflicts

- .github/workflows/pull_request.yml
- .github/workflows/release.yaml
- Dockerfile
Fixes: https://github.com/FoundationDB/fdb-kubernetes-operator/issues/2129
- Other
-
CI.
-
-
> Update to go 1.22.7

- e2e/test_operator_velocity/suite_test.go
Otherwise the test suite will not run.
-
I thought about adding a test, but that will also lead to the test suite failure, so in the end the same result.
-
-
> Fix the missing test suite name

- controllers/remove_process_groups.go
- controllers/remove_process_groups_test.go
- internal/error_helper.go
Small code clean up.
- Other
-
Unit tests.
-
-
> Simplify the confirmRemoval code

- docs/manual/customization.md
> Smaller doc fixes

- e2e/fixtures/fdb_cluster.go
- e2e/test_operator_ha_failure/operator_ha_failure_test.go
- e2e/test_operator_ha_failure/suite_test.go
Adding a new test that will cause a fail-over with data loss. The test is currently not running with CI, we might add this test later to CI. Right now the intention is to use this test case to run some additional tests later.
- Other
-
Added in the test case.
-
> Adding a new e2e test for producing data loss

- e2e/Makefile
Enable the unified image randomly in the e2e tests
- Other
Ran e2e tests.
Added in Makefile.
-
> Enable the unified image randomly in the e2e tests

- e2e/test_operator_plugin/operator_plugin_test.go
- kubectl-fdb/cmd/recover_multi_region_cluster.go
Fixes: https://github.com/FoundationDB/fdb-kubernetes-operator/issues/2153
-
Enabled new e2e test.
-
-
> Add support for multi-region recover subcommand with DNS

- charts/fdb-operator/Chart.yaml
- charts/fdb-operator/values.yaml
- config/deployment/manager.yaml
- config/samples/deployment.yaml
- docs/changelog/v1.53.0.md
> prepare release v1.53.0

- charts/fdb-operator/Chart.yaml
- charts/fdb-operator/values.yaml
- config/deployment/manager.yaml
- config/samples/deployment.yaml
- docs/changelog/v1.55.0.md
> prepare release v1.55.0

- kubectl-fdb/cmd/recover_multi_region_cluster.go
This allows other tools to make use of this method.
- Other
-
e2e tests will run the tests with the new plugin.
-
-
> Expose the multi-region recover mechanism

- api/v1beta2/foundationdbcluster_types.go
- controllers/replace_misconfigured_process_groups.go
- controllers/update_pods.go
- controllers/update_pods_test.go
- internal/pod_models.go
- internal/pod_models_test.go
- internal/replacements/replacements.go
- internal/replacements/replacements_test.go
Fixes: https://github.com/FoundationDB/fdb-kubernetes-operator/issues/1638
PR is based on: https://github.com/FoundationDB/fdb-kubernetes-operator/pull/2212
-
Unit tests + CI e2e tests.
Will be updated in a follow up PR.
-
> Ensure operator uses static names for PVC.

- api/v1beta2/foundationdbcluster_types.go
- config/crd/bases/apps.foundationdb.org_foundationdbclusters.yaml
Update the image type default in the CRD, missed that in the previous PRs.
- Other
-
-
-
-
> Update the image type default in the CRD

- .github/workflows/pull_request.yml
- .github/workflows/release.yaml
- Dockerfile
- go.mod
Before this both steps were building the data loader, which resulted in the latest image of the operator not being updated.
-
Waiting for CI.
-
-
> Fix PR action for docker build

- e2e/test_operator_upgrades/operator_upgrades_test.go
Correct check for incompatible clients if the coordinator pod hosted more than one process. Otherwise the test would fail if the selected pod hosted more than one process.
-
Ran the updated test manually.
-
-
> Correct check for incompatible clients if the coordinator pod hosted more than one process

- api/v1beta2/foundationdbcluster_types.go
- controllers/cluster_controller.go
- controllers/update_status.go
- controllers/update_status_test.go
- internal/pod_helper.go
- internal/pod_models.go
Fixes: https://github.com/FoundationDB/fdb-kubernetes-operator/issues/611
-
Ran unit tests and added new unit tests. Ran some e2e tests manually.
-
-
> Add a dedicated condition for wrong pod metadata

- e2e/fixtures/factory.go
- e2e/fixtures/images.go
- e2e/fixtures/images_test.go
- e2e/fixtures/options.go
Correct the handling of images in different scenarios
-
Added unit tests.
-
-
> Correct the handling of images in different scenarios

- .github/workflows/pull_request.yml
- .github/workflows/release.yaml
- Dockerfile
Update the go version to 1.23.9
- Other
-
Build the image.
-
-
> Update the go version to 1.23.9

- api/v1beta2/foundationdbbackup_types.go
- api/v1beta2/foundationdbcluster_types.go
- api/v1beta2/foundationdbrestore_types.go
- charts/fdb-operator/Chart.yaml
- charts/fdb-operator/values.yaml
- config/crd/bases/apps.foundationdb.org_foundationdbbackups.yaml
- config/crd/bases/apps.foundationdb.org_foundationdbclusters.yaml
- config/crd/bases/apps.foundationdb.org_foundationdbrestores.yaml
- config/deployment/manager.yaml
- config/samples/deployment.yaml
- docs/changelog/v2.8.0.md
> prepare release v2.8.0

- api/v1beta2/foundationdb_version.go
- api/v1beta2/foundationdbbackup_types.go
- api/v1beta2/foundationdbrestore_types.go
- config/crd/bases/apps.foundationdb.org_foundationdbbackups.yaml
- config/crd/bases/apps.foundationdb.org_foundationdbrestores.yaml
- controllers/admin_client_test.go
- controllers/start_backup.go
- controllers/start_restore.go
- docs/backup_spec.md
- docs/restore_spec.md
- fdbclient/admin_client.go
- fdbclient/admin_client_test.go
- pkg/fdbadminclient/admin_client.go
- pkg/fdbadminclient/mock/admin_client_mock.go
Supports suppling an encryption key file path for backups and restores. 
*If this change is adding new safety checks or new potential failure modes, have we documented and how to debug …
> Encryption for backup and restore

- setup/setup.go
Support setting health probe binding address through flags
#2328
> feat(operator): support IPV4

- api/v1beta2/foundationdbbackup_types.go
- api/v1beta2/foundationdbcluster_types.go
- api/v1beta2/foundationdbrestore_types.go
- charts/fdb-operator/Chart.yaml
- charts/fdb-operator/values.yaml
- config/crd/bases/apps.foundationdb.org_foundationdbbackups.yaml
- config/crd/bases/apps.foundationdb.org_foundationdbclusters.yaml
- config/crd/bases/apps.foundationdb.org_foundationdbrestores.yaml
- config/deployment/manager.yaml
- config/samples/deployment.yaml
- docs/changelog/v2.13.0.md
> prepare release v2.13.0

- api/v1beta2/foundationdbbackup_types.go
- api/v1beta2/foundationdbcluster_types.go
- api/v1beta2/foundationdbrestore_types.go
- charts/fdb-operator/Chart.yaml
- charts/fdb-operator/values.yaml
- config/crd/bases/apps.foundationdb.org_foundationdbbackups.yaml
- config/crd/bases/apps.foundationdb.org_foundationdbclusters.yaml
- config/crd/bases/apps.foundationdb.org_foundationdbrestores.yaml
- config/deployment/manager.yaml
- config/samples/deployment.yaml
- docs/changelog/v2.14.0.md
Update files for release 2.14.0
> Prepare release 2.14.0

- api/v1beta2/foundationdbbackup_types.go
- api/v1beta2/foundationdbcluster_types.go
- api/v1beta2/foundationdbrestore_types.go
- charts/fdb-operator/Chart.yaml
- charts/fdb-operator/values.yaml
- config/crd/bases/apps.foundationdb.org_foundationdbbackups.yaml
- config/crd/bases/apps.foundationdb.org_foundationdbclusters.yaml
- config/crd/bases/apps.foundationdb.org_foundationdbrestores.yaml
- config/deployment/manager.yaml
- config/samples/deployment.yaml
- docs/changelog/v2.15.0.md
Update files for release 2.15.0
> Prepare release 2.15.0
