- config/samples/deployment.yaml
- config/samples/deployment/rbac_role.yaml
Hi!
I just started playing with the operator, and found a minor issue on the `deployment.yaml`:
```bash
kubectl version                                   
kubectl apply -f config/samples/deployment.yaml
kubectl apply -f config/samples/cluster_local.yaml
kubectl logs fdb-kubernetes-operator-controller-manager-0 --container=manager
```
> Fix 'user cannot patch resource "events" in API group'

- api/v1beta1/foundationdbcluster_types.go
- config/crd/bases/apps.foundationdb.org_foundationdbclusters.yaml
- controllers/controller.go
This allows setting `locality_data_hall` in the fdbmonitor config. Which is needed by the `three_data_hall` redundancy mode.
> Support locality_data_hall

- controllers/add_pods.go
- controllers/controller.go
- controllers/update_pods.go
- controllers/update_status.go
> Move the removal of pods in a shrink to the end of the reconciliation workflow.

- controllers/check_client_compatibility.go
- controllers/controller_test.go
fix for https://github.com/FoundationDB/fdb-kubernetes-operator/issues/43
> blocking cluster downgrade

- .github/workflows/pull_request.yml
- Makefile
Mark all phony targets.
Prevent some of the phony targets from running when there are no changes to necessitate them running.
Closes #169
> General cleanups to Makefile.

- README.md
- config/rbac/foundationdbcluster_editor_role.yaml
- config/rbac/foundationdbcluster_viewer_role.yaml
- config/rbac/role_binding.yaml
- config/samples/deployment.yaml
- config/samples/deployment/manager.yaml
- config/samples/deployment/rbac_role.yaml
- config/samples/deployment/rbac_role_binding.yaml
- docs/user_manual.md
- helm/fdb-operator/templates/manager/deployment.yaml
- helm/fdb-operator/templates/rbac/rbac_role.yaml
Add the backup permissions to more default roles.
Add documentation on the WATCH_NAMESPACE option to the user manual.
Closes #156
> Set the WATCH_NAMESPACE field in more example deployments.

- foundationdb-kubernetes-sidecar/Dockerfile
- foundationdb-kubernetes-sidecar/default_config.json
- foundationdb-kubernetes-sidecar/sidecar.py
This establishes a hard cut-off with FDB 6.3 where using the old environment variables and the JSON config file are no longer supported. Once we stop doing patch releases for FDB 6.2, we can remove this code completely.
Related to #84
> Drop support for old sidecar environment variables in newer versions of FDB.

- api/v1beta1/foundationdbcluster_types.go
- api/v1beta1/suite_test.go
- config/samples/cluster_large.yaml
- config/samples/cluster_local.yaml
- config/samples/cluster_local_tls.yaml
- config/samples/cluster_with_backup.yaml
- config/samples/cluster_with_client.yaml
- controllers/admin_client_test.go
- controllers/pod_models_test.go
- controllers/suite_test.go
- docs/user_manual.md
Enable the require-not-present flag starting with FDB 6.2.20
Add the require-not-present flag to the cluster_with_client example.
Closes #199
> Bump the FDB version in our examples and tests to 6.2.20

- controllers/update_database_configuration.go
- controllers/update_status.go
> Prevent reconfiguring the database once we have detected a configured database.

- Dockerfile
- set -eux to fail on any simple command failing, and undefined
variables
- VERSION in the loop over FDB_ADDITIONAL_VERSIONS was in lowercase and
thus not defined at all, leading to bad curl commands, not failing
because of the for loop and missing set -e
- pin go version at 1.13.11 until the certificate issue is resolved
> Fix #252 docker builds broken

- controllers/admin_client.go
- controllers/cluster_controller_test.go
- controllers/pod_client.go
> Leave the IP address empty in the choose_removals step when the pod does not have an IP.

- controllers/replace_misconfigured_pods.go
> Ignore PVCs that are not owned by the cluster when checking for misconfigured pods.

- api/v1beta1/foundationdbcluster_types.go
- controllers/cluster_controller_test.go
- controllers/update_database_configuration.go
- controllers/update_status.go
> Ignore the values for version flags in the live configuration when those flags are omitted in the cluster spec.

- controllers/add_pods.go
- controllers/cluster_controller.go
- controllers/cluster_controller_test.go
- controllers/controllers.go
- controllers/update_config_map.go
- controllers/update_status.go
Mark pods as incorrect when they do not have the latest config map.
Resolves #42 
Resolves #280
> Use an annotation to track which version of a config map a pod has seen.

- api/v1beta1/foundationdbcluster_types.go
- api/v1beta1/foundationdbcluster_types_test.go
- controllers/admin_client.go
- controllers/admin_client_test.go
- controllers/bounce_processes.go
- controllers/controllers.go
- docs/cluster_spec.md
> Prevent executing a bounce when the minimum process uptime is below a certain limit.

- README.md
- config/samples/deployment.yaml
- docs/user_manual.md
I followed the steps described in https://github.com/FoundationDB/fdb-kubernetes-operator/blob/master/docs/user_manual.md#introduction to setup the operator. During the process I ran into some minor issues which will be fixed with this PR:
1.) Missing RBAC for `deployments`:
```bash
E0811 06:10:46.431800       1 reflector.go:156] pkg/mod/k8s.io/client-go@v0.17.0/tools/cache/reflector.go:108: Failed to list *v1.Deployment: deployments.apps is forbidden: User "system:serviceaccount:default:fdb-kubernetes-operator-controller-manager" cannot list resource "deployments" in API group "apps" in the namespace "default"
```
2.) Missing CRD in the install steps:
```bash
2020-08-11T06:20:28.904Z        ERROR   controller-runtime.source       if kind is a CRD, it should be installed before calling …
```
> Correct roles and deployment for getting started

- api/v1beta1/foundationdbcluster_types.go
- api/v1beta1/foundationdbcluster_types_test.go
- api/v1beta1/zz_generated.deepcopy.go
- config/crd/bases/apps.foundationdb.org_foundationdbclusters.yaml
- controllers/pod_client.go
- controllers/update_status.go
- docs/cluster_spec.md
Only check the Kubernetes sidecar client when determining if we can construct a client for the sidecar.
Resolves #281 
Resolves #291
> Add a check for container readiness when determining if reconciliation is complete.

- README.md
- config/samples/deployment.yaml
I also corrected the log command in the top level Readme.md
The previous defined docker tag was not available (and also looked compared to the other tags wrong):
```bash
$ docker pull foundationdb/fdb-kubernetes-operator:7.0
Error response from daemon: manifest for foundationdb/fdb-kubernetes-operator:7.0 not found: manifest unknown: manifest unknown
$ kubectl get po --show-labels
NAME                                                         READY   STATUS             RESTARTS   AGE   LABELS
fdb-kubernetes-operator-controller-manager-67b88c647-78jj6   0/1     ImagePullBackOff   0          56s   app=fdb-kubernetes-operator-controller-manager,control-plane=controller-manager,pod-template-hash=67b88c647
```
> Correct image tag for operator in samples

- controllers/change_coordinators.go
- controllers/update_status.go
Use the version from the spec as a fallback when we cannot get the cluster status using the running verison, to work around bugs with kills that are done outside of the operator.
Don't allow choosing coordinators that are pending removal but not yet excluded, to work around a bug when processes do not get excluded properly.
> Fix to management of running version during upgrades

- docs/user_manual.md
Fix a trailing sentence in the user manual.
> Adds an example of renaming a cluster to the user manual.

- api/v1beta1/foundationdbcluster_types.go
- api/v1beta1/zz_generated.deepcopy.go
- config/crd/bases/apps.foundationdb.org_foundationdbclusters.yaml
- controllers/check_instances_to_remove.go
- controllers/cluster_controller_test.go
- controllers/confirm_exclusion_completion.go
- controllers/exclude_instances.go
- docs/cluster_spec.md
Update the IP address in the pending removal state automatically when the pod gets rescheduled.
Add an option to remove an instance without excluding it to work around issues with stuck pods.
Fixes #303
> Avoid removing instances that do not have an IP address to prevent losing volumes that are temporarily inaccessible.

- sample-apps/data-loader/Dockerfile
- sample-apps/data-loader/app.py
This change reduces the size of the resulting container (and also reduces the attack surface) for faster startup of the container:
```bash
REPOSITORY              TAG                 IMAGE ID            CREATED             SIZE
johscheuer/sample-app   latest              b5d4c94a6dfc        2 minutes ago       120MB
johscheuer/sample-app   old                 47b9677ed2f9        3 seconds ago       889MB
```
> Use slim base image for sample container

- CONTRIBUTING.md
- README.md
- docs/user_manual.md
I updated the docs for local testing of the controller (e.g. the step for installing the fdb client packages was missing). I also fixed some markdown lint issues in the Readme (that's the reason why so much lines are moved around).
> Update docs for local dev

- foundationdb-kubernetes-sidecar/Dockerfile
This PR changes the base image from Python yo Python-slim to reduce the size of the image:
```bash
johscheuer/foundationdb-kubernetes-sidecar   6.2.25-1            72f0583a0be6        9 minutes ago       1.02GB
johscheuer/foundationdb-kubernetes-sidecar   6.2.25-1-slim       65f52536de49        6 seconds ago       265MB
```
> Use Python slim for sidecar

- Dockerfile
- api/v1beta1/foundationdbcluster_types.go
- config/manager/manager.yaml
Ensure that the docker build script will fail if the downloads fail.
Give more resources to the controller in the local test environment to help with CLI timeouts.
Fixes #11
> Start using non-blocking excludes with FDB 6.3.5.

- controllers/cluster_controller.go
- controllers/cluster_controller_test.go
- controllers/controllers.go
- controllers/pod_client_test.go
- controllers/pod_models.go
- controllers/pod_models_test.go
- controllers/update_sidecar_versions.go
- main.go
Resolves #99 
This solution is a little more complex than might be required for this specific issue, but I wanted to accomplish a couple of other goals:
1. This establishes a general pattern for defining new defaults that won't take effect until the next major version. This will let us define changes to the defaults gradually, without disrupting any existing clusters immediately.
2. This lays some of the groundwork for #282, where we are going to be defining new tools to analyze out-of-date configurations in advance of a major upgrade of the operator
> Add default resource requirements for the sidecar

- .github/workflows/pull_request.yml
- Dockerfile
Update the go version for building the operator to `1.15.2`. This is the same go version that is be used for Kubernetes `1.20` see: https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.20.md#feature.
So far I didn't discovered any strange behaviour in during testing.
Fixes: https://github.com/FoundationDB/fdb-kubernetes-operator/issues/278
> Update go version to 1.15.2

- .github/workflows/pull_request.yml
- .golangci.yml
- Makefile
- api/v1beta1/foundationdbcluster_types.go
- controllers/add_pods.go
- controllers/add_services.go
- controllers/admin_client.go
- controllers/backup_controller.go
- controllers/bounce_processes.go
- controllers/cluster_controller.go
- controllers/controllers.go
- controllers/metrics.go
- controllers/pod_models.go
- controllers/remove_services.go
- controllers/replace_misconfigured_pods.go
- controllers/suite_test.go
- controllers/update_pods.go
- controllers/update_status.go
- errcheck_excludes.txt
- main.go
[golangci-lint](https://github.com/golangci/golangci-lint) is used by many golang based repositories as linter. The current configuration is inspired by the [kubebuilder](https://github.com/kubernetes-sigs/kubebuilder/blob/master/.golangci.yml) repository.
> Add initial support for golangci-lint support

- controllers/update_status.go
> Use the GetConnectionString method when choosing the correct connection option so we always get an up-to-date cluster file.

- controllers/cluster_controller.go
- controllers/remove_pods.go
Add safety checks to ensure that our list calls in RemovePods only return 0 or 1 items.
Part of this was done in a recent commit to master, but we need to get this into a patch release.
> Include the cluster name in the labels we check when fetching a single pod.

- README.md
- controllers/admin_client_test.go
- controllers/backup_controller_test.go
- controllers/cluster_controller_test.go
- controllers/restore_controller_test.go
- controllers/suite_test.go
Fixes for some test suite problems - layers on #402, but attempts to get out in front of all future such problems by setting the global timeout to 5 seconds and removes most of the explicit overrides, and gets rid of the hard to reason about semi-global variable.
Also fixed an egregious race in the storage-servers-per-disk test - without this focusing on that one test and running
```
ginkgo -untilItFails controllers
```
would fail within 1 runs about 95% of the time on that test, and afterwards I managed to get a 10 run sequence successfully.
> Test suite improvements

- README.md
- scripts/setup_ramdisk_macos.sh
With the feedback and the analyse from @rbtcollins I added a script to setup a `ramdisk` for MacOS which brings a nice performance boost (at least at my machine):
```bash
make test
go test ./... -coverprofile cover.out
?       github.com/FoundationDB/fdb-kubernetes-operator [no test files]
ok      github.com/FoundationDB/fdb-kubernetes-operator/api/v1beta1     0.337s  coverage: 44.7% of statements
?       github.com/FoundationDB/fdb-kubernetes-operator/cmd/po-docgen   [no test files]
ok      github.com/FoundationDB/fdb-kubernetes-operator/controllers     449.010s        coverage: 74.5% of statements
make test
go test ./... -coverprofile cover.out
?       github.com/FoundationDB/fdb-kubernetes-operator [no test files]
ok      github.com/FoundationDB/fdb-kubernetes-operator/api/v1beta1 …
```
> Add script to setup ramdisk for macos

- helm/fdb-operator/templates/manager/deployment.yaml
... and another one :)
This PR adds a livenessProbe to the helm chart. Why? Because we validate all our helm charts before application using [kube-score,](https://github.com/zegl/kube-score) which complains if we don't have probes in our pods. I understand that this is not, by itself, a good enough reason to add some arbitrary podProbes, but a livenessProbe **will** force Kubernetes to restart the pod if it happens to crash in a nasty way. And it is the "right" thing to do ;)
(_I didn't bother with a readinessProbe, since an operator doesn't need to receive any ingress traffic_)
Cheers!
D
> Add livenessProbe to helm chart

- helm/fdb-operator/templates/manager/deployment.yaml
- helm/fdb-operator/values.yaml
Continuing the PR blitz, this PR adds the option for the user to customize the resource requests/limits in the helm chart, while "falling back" to the existing requests/limits by default.
Why? We like to fine-tune our resource allocations, and being able to control the allocations for the operator pod is desirable ;)
Cheers!
D
> Allow customization of pod resources in helm chart

- .github/workflows/pull_request.yml
customise released a new version which breaks our build so I pinned it to `v3.8.8` which works (on my machine 😄) I open an issue to check what breaks https://github.com/kubernetes-sigs/kustomize/releases.
> Pin kustomize version

- api/v1beta1/foundationdbcluster_types.go
- api/v1beta1/foundationdbcluster_types_test.go
- controllers/cluster_controller_test.go
- controllers/update_status.go
Fixes: https://github.com/FoundationDB/fdb-kubernetes-operator/issues/441 since we passed `clusterStatus FoundationDBClusterStatus` by value and not by reference the "real" status was always empty.
> Fix bug to update storageServerPerPod

- Dockerfile
- config/samples/deployment.yaml
- config/samples/deployment/manager.yaml
- helm/fdb-operator/templates/manager/deployment.yaml
Hey guys,
This PR adds a securityContext to both the manager pod, and the specific manager container. Because we enforce `readOnlyRootFilesystem` in `container.securityContext`, we also add an `emptyDir` volumeMount to allow `/tmp` to be read/write, without allowing the **rest** of the pod to be read/write.
I also adjusted the UID to 40590 in both the `pod.securityContext` and the `Dockerfile`, so that subsequent CI actions (_coming in a separate PR_) using [kube-score](_https://github.com/zegl/kube-score_) will pass the manifests (_since the UID will be > 10000_). Additionally, clusters employing PSPs enforcing containers to run as non-root will allow the container image to run, since the `USER` value is now numeric (_this PR supercedes my previous PR #424_)
Cheers!
D
> Add securityContext to helm chart

- config/samples/multi_dc/final.yaml
- controllers/cluster_controller.go
- controllers/lock_client.go
Add more logging when taking locks.
Fix the priorities in the database config in the multi-DC sample.
Resolves #459
> Add a timeout to the transactions for managing locks.

- controllers/lock_client.go
Currently we can run in this nasty error:
```bash
E0204 15:03:11.712420       1 runtime.go:78] Observed a panic: &runtime.TypeAssertionError{_interface:(*runtime._type)(0x1468ee0), concrete:(*runtime._type)(nil), asserted:(*runtime._type)(0x13ff780), missingMethod:""} (interface conversion: interface {} is nil, not bool)
goroutine 679 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x14a2240, 0xc0007bb1d0)
/go/pkg/mod/k8s.io/apimachinery@v0.17.0/pkg/util/runtime/runtime.go:74 +0xa3
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
/go/pkg/mod/k8s.io/apimachinery@v0.17.0/pkg/util/runtime/runtime.go:48 +0x82
panic(0x14a2240, 0xc0007bb1d0)
/usr/local/go/src/runtime/panic.go:679 +0x1b2
github.com/FoundationDB/fdb-kubernetes-operator/controllers.(*RealLockClient).TakeLock …
```
> Check for nil before casting

- .github/workflows/pull_request.yml
- Makefile
- controllers/admin_client.go
- controllers/admin_client_test.go
- controllers/backup_controller_test.go
- controllers/cluster_controller.go
- controllers/cluster_controller_test.go
- controllers/pod_client.go
- controllers/replace_failed_pods_test.go
- controllers/restore_controller_test.go
- controllers/suite_test.go
- mock-kubernetes-client/client/client.go
- mock-kubernetes-client/client/client_test.go
- mock-kubernetes-client/client/doc.go
Resolves #406 
This makes larger-scale changes to our test suite to make it more reliable. With this PR, we run the Reconcile method explicitly in the tests, rather than relying on the event stream. It also uses a custom mock Kubernetes client instead of using the standard controller-runtime client, so that we do not have to worry about nondeterministic behavior from the cache.
> Run the race detector in our test suite.

- go.mod
- main.go
Default is json logs
See https://github.com/FoundationDB/fdb-kubernetes-operator/issues/464
> Add flag to enable verbose development/console logs

- controllers/admin_client.go
- controllers/cluster_controller.go
- controllers/fdb_client.go
- controllers/lock_client.go
Fixes: https://github.com/FoundationDB/fdb-kubernetes-operator/issues/487
I will open some follow ups to evaluate how we want to test the interaction with FDB and commands that we run with `fdbcli` currently we have some mock but we don't actually test "real" logic.
> Read status directly from FDB

- .github/workflows/release.yaml
- Makefile
- kubectl-fdb/cmd/k8s_client.go
- kubectl-fdb/cmd/version.go
- kubectl-fdb/cmd/version_test.go
Fixes: https://github.com/FoundationDB/fdb-kubernetes-operator/issues/484
Fixes: https://github.com/FoundationDB/fdb-kubernetes-operator/issues/483
This PR ensures we fetch the operator version from the correct container and during the release process we set the tag for the plugin.
> Fetch version plugin

- .github/workflows/master.yml
- .github/workflows/release.yaml
Fixes: https://github.com/FoundationDB/fdb-kubernetes-operator/issues/75
You can see the successful workflow here: https://github.com/johscheuer/fdb-kubernetes-operator/actions/runs/522035788
There is a bunch of stuff we should discuss after the weekend to see if we want to use the GitHub solution.
> Build and push docker images for releases and on master

- .github/workflows/master.yml
- .github/workflows/release.yaml
The current push to the registry failes because our org uses some uppercase letters:
```
invalid reference format: repository name must be lowercase
```
so the resulted image was:
```
FoundationDB/fdb-data-loader:latest
```
instead I just "hard-coded" the image names since they won't change that often.
> Correct image name for DockerHub

- Dockerfile
Updates the golang version to the latest 1.15.8 to build the operator.
> Update to golang 1.15.8

- controllers/pod_models.go
The ClusterIP services are not doing true service discovery, instead
they are just fixed proxies for the pod, and so the readiness of the pod
is not relevant. Pod readiness automatically prevents traffic flow via
the ClusterIP if the pod isn't ready - either during startup, or during
the pod deletion lifecycle, but if the FDB process is running, outbound
connections may be made, and this sets up a grey-failed network scenario
which is poor for FDB.
Signed-off-by: Robert Collins <robert.collins@cognite.com>
> Fix #520: Public NotReady pods to pod cluster IPs

- kubectl-fdb/cmd/k8s_client.go
- kubectl-fdb/cmd/remove.go
- kubectl-fdb/cmd/remove_instances.go
- kubectl-fdb/cmd/remove_instances_test.go
- kubectl-fdb/cmd/root.go
- kubectl-fdb/cmd/version.go
- kubectl-fdb/main.go
fixes: https://github.com/FoundationDB/fdb-kubernetes-operator/issues/481
I made this option the default since I think most operators will use the Pod name rather than the instance name. I also restructured the remove command a little bit so that we have now:
```bash
kubectl fdb -n default remove instances -c cluster instance-1 instance-2
```
So that we can add later on the possibility to remove also clusters, backups, etc.
> Allow to remove instances by pod name

- kubectl-fdb/cmd/cordon.go
- kubectl-fdb/cmd/exec.go
- kubectl-fdb/cmd/remove.go
- kubectl-fdb/cmd/remove_instances.go
- kubectl-fdb/cmd/root.go
- kubectl-fdb/cmd/root_test.go
- kubectl-fdb/cmd/version.go
This PR is based on https://github.com/FoundationDB/fdb-kubernetes-operator/pull/505
I added a test case for the `root cmd` we can/will add more test cases for the specific command in a follow up. The simple test allows to test the cmd creation (e.g. all flags are set do we only use referenced flags etc. to prevent some mistakes).
> Add test for kubectl rootcmd

- .github/workflows/pull_request.yml
- Makefile
- README.md
- config/crd/bases/apps.foundationdb.org_foundationdbbackups.yaml
- config/crd/bases/apps.foundationdb.org_foundationdbclusters.yaml
- config/minio/operator.yaml
- config/rbac/leader_election_role.yaml
- config/rbac/leader_election_role_binding.yaml
- config/samples/deployment.yaml
- config/samples/deployment/rbac_role.yaml
- main.go
- scripts/setup_kind_local_registry.sh
Initially I only wanted to fix this issue https://github.com/kubernetes-sigs/controller-tools/issues/529 (I didn't saw this issue because some older Kubernetes version ignore (e.g. 1.15 which is the default for kube-builder) and I wanted to add a small test to deploy the CRDs against our expected Kubernetes versions.
> Add e2e test to create CRDs against a newer version of the API server

- api/v1beta1/foundationdbcluster_types.go
- api/v1beta1/foundationdbcluster_types_test.go
- api/v1beta1/zz_generated.deepcopy.go
- controllers/add_process_groups.go
- controllers/cluster_controller.go
- controllers/cluster_controller_test.go
- controllers/controllers.go
- controllers/pod_client.go
- controllers/pod_models.go
- controllers/pod_models_test.go
- controllers/replace_misconfigured_pods_test.go
- controllers/update_status.go
- controllers/update_status_test.go
- docs/cluster_spec.md
- kubectl-fdb/cmd/cordon_test.go
- kubectl-fdb/cmd/exec_test.go
- kubectl-fdb/cmd/remove_instances.go
- kubectl-fdb/cmd/remove_instances_test.go
Sorry for this enormous out of the blue patch, and I'll understand if the answer is 'wat, nope.'
It came out of the other coordinator patch where a little more type safety would have been useful. And then the minimum set the tentacles reached to this size.
The basic idea is the usual benefits of type safety - no accidentally assigning random strings to ProcessClass places, etc. 
This version can probably be cleaned up a bit if the basic idea is not objectionable.
> Make ProcessClass a type

- controllers/admin_client.go
- controllers/admin_client_test.go
We still have an issue when we use the `fdbcli status` e.g. for backups or when we want to call it in the kubectl plugin the new version of fdbcli should report warnings and errors to stderr (https://github.com/apple/foundationdb/pull/4332) so we shouldn't see this error anymore until all of the old version are deprecated we should have a workaround for these cases. This PR removes all leading characters of the JSON output that is not a `{`.
> Remove all leading non JSON output

- helm/fdb-operator/values.yaml
Hey guys,
This PR simply corrects what seems to be an error in the latest helm chart - the desired container image should be `v0.29.0`, rather than `0.29.0` (which doesn't exist)
Cheers!
D
> Correct v0.29.0 image tag in helm chart

- api/v1beta1/foundationdbcluster_types.go
- config/crd/bases/apps.foundationdb.org_foundationdbclusters.yaml
I stumbled over this when I created a multi dc FDB cluster and used the `satellite` field as `priority`. This can be a little bit tricky to debug so I think it makes sense to add this as a validation check.
> Add validation for satellite

- .github/workflows/pull_request.yml
It seems like the cache for the binaries is more faulty than it offer speed improvement.
> Disable faulty cache

- api/v1beta1/foundationdbcluster_types.go
- config/crd/bases/apps.foundationdb.org_foundationdbclusters.yaml
If you run multiple FDB clusters it would be nice to see in which version the specific clusters are.
> Add version to status output

- controllers/cluster_controller_test.go
- controllers/exclude_instances.go
Fixes #363 
This is going to block on any process missing, not just the ones that we added as a replacement.
> Block exclusions on missing processes

- README.md
With we renamed the action so I had to fix the badge: https://github.com/FoundationDB/fdb-kubernetes-operator/pull/554
> Fix broken badge for CI

- main.go
Instead of defining our own custom flags we should use the standard flags of the controller-runtime. This will be a breaking change and we should note this in the new release as action required during the update of the operator. e.g. `log-level` will be `zap-log-level` (see: https://github.com/kubernetes-sigs/controller-runtime/blob/master/pkg/log/zap/zap.go#L235-L242).
> Make use of the standard logging flags

- go.mod
- main.go
Fixes: https://github.com/FoundationDB/fdb-kubernetes-operator/issues/572
Before:
```
{"level":"info","ts":1616333160.5288906,"logger":"setup","msg":"starting manager"}
I0321 13:26:00.529170       1 leaderelection.go:243] attempting to acquire leader lease default/fdb-kubernetes-operator...
{"level":"info","ts":1616333160.6301408,"logger":"controller-runtime.manager","msg":"starting metrics server","path":"/metrics"}
I0321 13:26:18.299225       1 leaderelection.go:253] successfully acquired lease default/fdb-kubernetes-operator
```
After:
```
{"level":"info","ts":1616489413.469807,"logger":"setup","msg":"starting manager"}
{"level":"info","ts":1616489413.4702618,"logger":"controller-runtime.manager","msg":"starting metrics server","path":"/metrics"} …
```
> Set logger for go-client

- controllers/add_pods.go
- controllers/add_process_groups.go
- controllers/bounce_processes.go
- controllers/change_coordinators.go
- controllers/check_client_compatibility.go
- controllers/choose_removals.go
- controllers/cluster_controller.go
- controllers/exclude_instances.go
- controllers/generate_initial_cluster_file.go
- controllers/remove_pods.go
- controllers/update_backup_agents.go
- controllers/update_config_map.go
- controllers/update_database_configuration.go
- controllers/update_pods.go
- controllers/update_sidecar_versions.go
Makes use of the `corev1.EventType` and fixed the wrong `error` event.
Before:
```bash
Events:
Type    Reason           Age   From                            Message
----    ------           ----  ----                            -------
Normal  AddingProcesses  38s   foundationdbcluster-controller  Adding 4 storage processes
Normal  AddingProcesses  38s   foundationdbcluster-controller  Adding 4 log processes
Normal  AddingProcesses  38s   foundationdbcluster-controller  Adding 1 cluster_controller processes
```
After:
```bash
Type     Reason           Age               From                            Message
----     ------           ----              ----                            -------
Normal   AddingProcesses  3m15s             foundationdbcluster-controller  Adding 4 storage …
```
> Make use of constant for event type and remove invalid error type

- controllers/cluster_controller.go
fixes: https://github.com/FoundationDB/fdb-kubernetes-operator/issues/269 I validated with this change I don't see any conflicts anymore.
> Check resource version to prevent conflicts

- docs/design/process_group_crd.md
This is the initial design to move the `ProcessGroup` out of the status of the cluster into an own dedicated CRD.
> Add design doc for ProcessGroup as CRD

- api/v1beta1/foundationdbcluster_types.go
- controllers/bounce_processes.go
- controllers/cluster_controller_test.go
- controllers/update_status.go
- controllers/update_status_test.go
We can ignore processes that are marked for removal during the bounce.
> Ignore removed processes for bounce

- controllers/pod_models_test.go
- controllers/update_sidecar_versions.go
- controllers/update_sidecar_versions_test.go
Before we used different methods to generate the sidecar image which lead to a different behaviour when someone sets a custom sidecar.
> Use the same mechanism to generate the sidecar image

- controllers/backup_controller.go
- controllers/cluster_controller.go
- controllers/restore_controller.go
- main.go
This is an old artefact from the upgrade of the controller-runtime and is not required.
> Remove unused scheme

- api/v1beta1/foundationdb_version.go
- api/v1beta1/foundationdbcluster_types.go
- api/v1beta1/foundationdbcluster_types_test.go
- config/crd/bases/apps.foundationdb.org_foundationdbclusters.yaml
- controllers/admin_client.go
- controllers/cluster_controller.go
- docs/cluster_spec.md
That should help to catch a misconfiguration in the FDB version before the operator has to complain.
> Add validation to the FDB version

- kubectl-fdb/cmd/root_test.go
Fixes: https://github.com/FoundationDB/fdb-kubernetes-operator/issues/648
Interestingly the args passed to the framework will be passed to the `cmd` if we don't overwrite it 🤔
> Reset the args to prevent test failure

- Dockerfile
- api/v1beta1/foundationdb_version.go
- config/manager/manager.yaml
- config/samples/deployment.yaml
- config/samples/deployment/manager.yaml
- helm/fdb-operator/templates/manager/deployment.yaml
- main.go
> Pull the FDB binaries for the operator from init containers to decouple FDB versions and operator versions.

- controllers/replace_failed_pods.go
- controllers/replace_failed_pods_test.go
Fixes: https://github.com/FoundationDB/fdb-kubernetes-operator/issues/640 for now we just ignore process groups without an address.
> Ignore process groups without an address

- controllers/admin_client.go
In `fdbcli` support to output errors and warnings on stderr instead of stdout (https://github.com/apple/foundationdb/pull/4332) was added. To read all messages (stdout and stderr) we have to use `CombinedOutput` instead of `Output` only.
> Make use of combined output

- config/samples/cluster_with_backup.yaml
- controllers/admin_client.go
Remove a parameter from the backup and restore commands that is only available on fdbcli.
Extend the snapshot period in the local sample to prevent lots of small snapshots from slowing things down.
> Add instructions on testing a restore in our backup sample.

- Makefile
- e2e/suite_test.go
Fixes: https://github.com/FoundationDB/fdb-kubernetes-operator/issues/685 CC: @rbtcollins
> Make use of build tags to prevent running e2e tests with go test

- controllers/add_pods.go
- controllers/cluster_controller.go
- controllers/cluster_controller_test.go
- controllers/controllers.go
- controllers/pod_models.go
- controllers/pod_models_test.go
- controllers/update_pod_config.go
- controllers/update_status.go
Fixes: https://github.com/FoundationDB/fdb-kubernetes-operator/issues/377
With this change it's not that confusing why all processes must be "updated" when we change either the number of storage server per Pod or a class specific setting.
> Calculate ConfigMap hash based on process class and servers per pod

- config/samples/pod_disruption_budget.yaml
- controllers/change_coordinators.go
- controllers/change_coordinators_test.go
- docs/user_manual.md
This makes it possible to write PDBs that safely permit individual node
draining even when a single pod from each of multiple storage classes
are present on that node. See #507 and #316 for more context.
Possibly this should automatically fall back to using all stateful
storage classes in very small clusters? Or perhaps a configuration
switch?
Signed-off-by: Robert Collins <robert.collins@cognite.com>
> Restrict coordinators to storage pods

- main.go
Make usr of `DatabaseClientProvider` to prevent issues with cleaning up the DB cache.
> Make use of the new db client

- api/v1beta1/foundationdbcluster_types.go
- api/v1beta1/foundationdbcluster_types_test.go
- controllers/admin_client.go
- controllers/cluster_controller.go
- controllers/cluster_controller_test.go
- controllers/pod_client.go
- controllers/suite_test.go
- controllers/update_status.go
- mock-kubernetes-client/client/client.go
- mock-kubernetes-client/client/client_test.go
Fixes: https://github.com/FoundationDB/fdb-kubernetes-operator/issues/702
The first part is removing the `MockPodIP` and the second part is the actual bug fix.
> Only track latest address

- api/v1beta1/foundationdb_labels.go
- controllers/update_pod_config.go
Resolves #731
I did a test run of this locally, and it reduced the initial cluster creation time from 115 seconds to 40 seconds.
> Apply an annotation when we see an out-of-date config map.

- controllers/change_coordinators_test.go
- controllers/cluster_controller.go
- controllers/cluster_controller_test.go
Fixes: https://github.com/FoundationDB/fdb-kubernetes-operator/issues/718
The sorting makes the coordinator selection more expensive but I think that's worth the deterministic output and also we only select new coordinators when a coordinator is not available.
> Ensure that the coordinator selection is deterministic

- controllers/backup_controller.go
- controllers/bounce_processes.go
- controllers/cluster_controller.go
- controllers/generate_initial_cluster_file.go
- controllers/restore_controller.go
Fixes: https://github.com/FoundationDB/fdb-kubernetes-operator/issues/569
Fixes: https://github.com/FoundationDB/fdb-kubernetes-operator/issues/360
I noticed I got that change on my machine and never pushed it 🤦 I tested that adding/changing the annotation triggers a reconciliation as well a deleting a Pod or changing a Pod annotation.
> Only reconcile on generation or annotation change

- api/v1beta1/foundationdbcluster_types.go
- config/crd/bases/apps.foundationdb.org_foundationdbclusters.yaml
I think the healthy output is too flaky to be useful.
> Show available instead of healthy in the kubectl get command

- foundationdb-kubernetes-sidecar/sidecar.py
I ran into the following error where `FDB_MACHINE_ID` pointed to the node name and obviously on the node itself no FDB process was running. Instead of using the `getaddrinfo` we should just fallback to the `FDB_POD_IP` variable or the IP in the container (should be the same).
```bash
Traceback (most recent call last):
File "//sidecar.py", line 662, in <module>
copy_files()
File "//sidecar.py", line 556, in copy_files
config = Config.shared()
File "//sidecar.py", line 297, in shared
cls.shared_config = Config()
File "//sidecar.py", line 228, in __init__
address_info = socket.getaddrinfo(
File "/usr/local/lib/python3.9/socket.py", line 953, in getaddrinfo
for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution …
```
> Fallback to Pod IP and not to the machine ID

- api/v1beta1/foundationdbcluster_types.go
- api/v1beta1/foundationdbcluster_types_test.go
- controllers/update_status.go
This adds a new process group condition to track when we've terminated resources, and uses that to track when we want to set the special `HasPendingRemoval` field in the generation status. This means that if we exclude the processes but aren't able to start the termination, we won't set this field, and won't mark the cluster as reconciled.
This may not be necessary, since the space for failures between finishing exclusions and terminating pods is pretty small, but I think …
> Wait to set the HasPendingRemoval flag in the status until we’ve started terminating the resources.

- controllers/cluster_controller_test.go
- controllers/metrics.go
Remove old deprecated metrics.
Fixes: https://github.com/FoundationDB/fdb-kubernetes-operator/issues/651
No
locally
No
No
> Remove deprecated metrics

- api/v1beta1/foundationdb_version.go
- api/v1beta1/foundationdb_version_test.go
- api/v1beta1/foundationdbbackup_types_test.go
- api/v1beta1/foundationdbcluster_types_test.go
This change adds methods to the `FDBVersion` struct to get the next versions. This will be useful e.g. for testing purposes.
No
Unit tests
No
Nothing
> Add methods to get the next version based on the current version

- controllers/cluster_controller.go
- controllers/update_status.go
Add more context when a failure happens during the `GetStartCommand` e.g. when the sidecar is not available.
None
Locally
No
No
> Wrap error with additional process group info

- controllers/generate_initial_cluster_file.go
Just adding the desired count and the current running Pods to the message to help the human operator to see why the operator is not able to reconcile.
This came up in: https://github.com/FoundationDB/fdb-kubernetes-operator/issues/839
-
Locally
-
-
> Add the number of desired Pods in the message for initial cluster file generation

- controllers/cluster_controller.go
- controllers/generate_initial_cluster_file.go
Remove a useless sort of the instances. The problem is that we always sort even if we don't have enough processes for our desired coordinator count and in [chooseDistributedProcesses](https://github.com/FoundationDB/fdb-kubernetes-operator/blob/1dade55f1efa1ee6135cec5846538d7490785c5d/controllers/cluster_controller.go#L1226) we also sort the processes so there is no need to pre-sort them.
Nothing.
locally.
None.
None.
> Remove sort from initial file generation

- controllers/cluster_controller.go
- main.go
Expose the `GetPodSpec` in the controllers until `UpdatePods` is refactored.
Otherwise external clients are not able to implement the `UpdatePods` logic to check the Pod Spec.
Locally, unit tests
None.
None.
> Expose the GetPodSpec method in the controller package

- api/v1beta1/foundationdbcluster_types.go
- api/v1beta1/foundationdbcluster_types_test.go
This allows to also define only an IP address as process address (we use this for Pod actions like exclusion and inclusion) and adding some additional test cases.
- 
None.
Unit tests, locally and e2e.
Nothing.
Nothing.
> Allow to only set the IP address without any ports and add more tests

- api/v1beta1/foundationdbcluster_types.go
- api/v1beta1/foundationdbcluster_types_test.go
- api/v1beta1/zz_generated.deepcopy.go
- config/crd/bases/apps.foundationdb.org_foundationdbclusters.yaml
- controllers/admin_client.go
- controllers/cluster_controller_test.go
- controllers/generate_initial_cluster_file.go
- docs/cluster_spec.md
Reverting the change that coordinators in the connection string (CRD) are handled as `ProcessAddress`.
Local, e2e.
None.
None.
> Revert the change for the CRD to use coordinators as strings

- controllers/replace_misconfigured_pods.go
- controllers/replace_misconfigured_pods_test.go
Replace instances if PVC hash/name does not match with cluster spec. Currently, PVC hash is only validated against cluster spec. This will add the PVC name for validation. 
NA
Added Unit test cases
NA
NA
*If this change is adding or removing subreconcilers, have we …
> Replace instances if PVC hash/name does not match

- api/v1beta1/foundationdbcluster_types.go
- controllers/admin_client.go
- controllers/cluster_controller_test.go
- internal/pod_client.go
- mock-kubernetes-client/client/client.go
This fixes a bug where IP addresses would be enclosed in two sets of brackets when we generated the connection string for IPv6 clusters.
This does fairly primitive parsing, but I don't know if there's a cleaner way of expressing what we're trying to do.
I added new unit tests for IPv6 clusters, and created a real IPv6 cluster in a test environment.
No.
No.
*If this …
> Prevent double-encoding IPv6 addresses when translating between pod IPs and process addresses.

- kubectl-fdb/cmd/analyze.go
Print Pod names instead of Pod structs when running the analyze command.
Unit tests + locally
-
-
> Printout Pod names instead of Pod struct

- api/v1beta1/foundationdbcluster_types.go
- api/v1beta1/foundationdbcluster_types_test.go
- controllers/update_status.go
- docs/manual/debugging.md
- kubectl-fdb/cmd/exec.go
- kubectl-fdb/cmd/fix_coordinator_ips.go
- kubectl-fdb/cmd/fix_coordinator_ips_test.go
- kubectl-fdb/cmd/root.go
This provides tooling and documentation to help with a potential failure scenario where all coordinators get deleted and come up with new IPs.
The new command doesn't work for multi-KC clusters, because any given invocation will only have access to the process group information (and thus the new addresses) for the processes in that KC. I think we should address that in the future, as part of the broader work on improving multi-KC support in the plugin.
I changed the logic around tracking process group IPs to keep old IPs around when the database is unavailable. This was necessary to be able to use the process group …
> Add a command to fix coordinator IPs after a majority of coordinators get new IPs.

- controllers/cluster_controller_test.go
- internal/deprecations.go
- internal/deprecations_test.go
- internal/pod_models.go
- internal/pod_models_test.go
This moves the logic for handling 3 deprecated fields in ContainerOverrides into the NormalizeClusterSpec method.
Resolves #888 
No
Manual tests and unit tests
No
I don't think there are any documentation updates necessary.
No.
*Does this introduce new defaults that we should re-evaluate in the …
> Adds additional checks for deprecated fields in container overrides.

- fdbclient/admin_client.go
Currently, If the `fdbcli` binary is not present `nil` is returned instead of an error string [here](https://github.com/FoundationDB/fdb-kubernetes-operator/blob/3fac0fbfed79abb4785c77b03dcc69acf11d9981/fdbclient/admin_client.go#L422). This makes debugging difficult.  
NA
Local testing
NA
NA
*If this change is adding new functionality, do we need to describe …
> Return err if file not found instead of nil

- api/v1beta1/foundationdbcluster_types.go
- config/crd/bases/apps.foundationdb.org_foundationdbclusters.yaml
Adding the fully replicated information to the status printout:
```bash
$ kubectl get fdb
NAME                                                     GENERATION   RECONCILED   AVAILABLE   FULLREPLICATION   VERSION   AGE
foundationdbcluster.apps.foundationdb.org/test-cluster   1            1            true        true              6.2.30    44s
```
None
Locally
None
None
> Add the fully replicated information into the status printout

- controllers/pod_lifecycle_manager.go
Ironically the FDB cluster health is a bad indicator of the actual cluster health. Instead we should look if the cluster is fully replicated and if the cluster is available. Otherwise different things that are unrelated to the actual cluster health can block deletions e.g. a test process that is not running any more or clients with a wrong cluster file.
None.
Locally.
None.
None.
> Check for fault tolerance and not cluster health when deleting Pods

- .github/workflows/pull_request.yml
- .github/workflows/release.yaml
- Dockerfile
- fdbclient/admin_client.go
- fdbclient/common.go
- go.mod
- internal/pod_client.go
Update to go `1.16.8`. Release notes for https://golang.org/doc/go1.16 since go `1.17` was released `1.15` is no longer "supported". 
None.
Unit + local.
None.
None.
> Update go to version 1.16.8

- controllers/generate_initial_cluster_file.go
Fixes #838. Checked all the other occurrences and didn't find anything similar
Not needed
Not needed
Not needed
Not needed
> Don't requeue in generate initial cluster file when no error occurs

- api/v1beta1/foundationdbcluster_types.go
- controllers/add_pods.go
- controllers/add_process_groups.go
- controllers/add_pvcs.go
- controllers/add_services.go
- controllers/admin_client.go
- controllers/bounce_processes.go
- controllers/cluster_controller.go
- controllers/cluster_controller_test.go
- controllers/delete_pods_for_buggification.go
- controllers/fdb_instance.go
- controllers/fdb_process_group.go
- controllers/generate_initial_cluster_file.go
- controllers/pod_lifecycle_manager.go
- controllers/remove_process_groups.go
- controllers/replace_misconfigured_pods.go
- controllers/replace_misconfigured_pods_test.go
- controllers/update_labels.go
- controllers/update_labels_test.go
- controllers/update_pod_config.go
- controllers/update_pod_config_test.go
- controllers/update_pods.go
- controllers/update_sidecar_versions.go
- controllers/update_sidecar_versions_test.go
- controllers/update_status.go
- controllers/update_status_test.go
- internal/pod_client.go
- internal/pod_helper.go
- internal/pod_models_test.go
Fixes: https://github.com/FoundationDB/fdb-kubernetes-operator/issues/681 the change is intended to be a breaking change (which is fine for our `0.*` state) for everyone using our code. The benefit of the refactoring is that we can move more code into our internal package to reduce the public surface.
- Breaking change 
There might be some other places where we can be smarter but I would leave this opt./refactoring for another PR.
Unit + locally. Will run some e2e tests later report back.
Nothing to document.
- https://github.com/FoundationDB/fdb-kubernetes-operator/issues/918
> Refactor fdb instance

- api/v1beta1/foundationdbbackup_types.go
- api/v1beta1/foundationdbbackup_types_test.go
- controllers/backup_controller_test.go
- docs/backup_spec.md
- internal/test_helper.go
Moved the backup state to a constant for better reusability.
None
Unit + local testing
None.
None.
> Move backup states into constants

- controllers/bounce_processes_test.go
- internal/pod_client.go
Make use of the default retry policy instead of a custom one (https://pkg.go.dev/github.com/hashicorp/go-retryablehttp#DefaultRetryPolicy)
I'm not sure why we added the custom logic but looking at the sidecar I don't think that the custom check has any benefits.
Unit + local.
None.
-
> Use default retry policy

- controllers/add_pods.go
- controllers/cluster_controller.go
- controllers/delete_pods_for_buggification.go
- controllers/replace_misconfigured_process_groups.go
- controllers/replace_misconfigured_process_groups_test.go
- controllers/update_labels.go
- controllers/update_labels_test.go
- controllers/update_pod_config.go
- controllers/update_pods.go
- controllers/update_sidecar_versions.go
- docs/manual/technical_design.md
- internal/configmap_helper.go
- internal/deprecations_test.go
- internal/log.go
- internal/monitor_conf.go
- internal/pod_helper.go
- internal/pvc_helper.go
- internal/test_helper.go
Fixes: https://github.com/FoundationDB/fdb-kubernetes-operator/issues/918 (Ensure in reconcilers that we iterate over ProcessGroups not Instances/Pods )
- 
Unit + local 
Adjusted.
-
> Ensure we only iterate over process groups

- api/v1beta1/foundationdbcluster_types.go
- docs/cluster_spec.md
Fixes: https://github.com/FoundationDB/fdb-kubernetes-operator/issues/940 to remove the setting in 1.0 and not allow to deactivate it.
-
-
-
-
> Deprecate enforce full replication

- Dockerfile
Specify the complete registry to allow builds with container runtimes/builders other than `docker`.
Docker has hardcoded that search path but we should make it explicit to make it easier for other tools to use the Dockerfile.
local.
-
-
> Specify the complete registry

- controllers/update_status.go
This addresses a failure mode I've observed in cluster creation where an error in reconciliation at a certain phase will call cause the cluster to have a connection string in the FoundationDBCluster resource, but not in the config map or any of the pods.
We may want to be more resilient to failures to get the database status in general, rather than narrowly targeting this at cases where the database has not been configured.
I had a live case of this problem in my test environment, and I verified that the fix allowed cluster creation …
> Prevents the cluster creation from getting deadlocked when it cannot connect to the database before the processes have a cluster file.

- internal/replacements/replacements.go
- internal/replacements/replacements_test.go
- internal/replacements/suite_test.go
This is a fix for https://github.com/FoundationDB/fdb-kubernetes-operator/issues/950.
This will trigger a replacement if any part of the pod template spec is changed if there is a [PodNodeSelector](https://kubernetes.io/docs/reference/access-authn-authz/admission-controllers/#podnodeselector). Which isn't ideal but is better than the previous behavior of the pods being replaced endlessly.
I ran unit tests and manually deployed the operator and cluster in a namespace with a PodNodeSelector.
> Only replace on changed node selector if pod spec hash has changed

- controllers/admin_client_mock.go
- controllers/admin_client_mock_test.go
- controllers/cluster_controller_test.go
- controllers/exclude_processes.go
- controllers/remove_process_groups_test.go
- internal/error_helper.go
Fixes: https://github.com/FoundationDB/fdb-kubernetes-operator/issues/971
Moving forward allows the operator to actually change coordinators if required or do any other operator and is not blocked on a single replacement/exclusion. Since the operator will only replace process groups that are excluded (or we skip the exclusion) it's safe to move forwards.
Unit + local
-
None
> Make exclusions not block in sub reconciler

- api/v1beta1/foundationdbcluster_types.go
- docs/cluster_spec.md
Fixes: https://github.com/FoundationDB/fdb-kubernetes-operator/issues/887
One of the concerns in the issue was that the `ImageConfigs` are not allowing to change the image for only a specific process class. I think that this is out of scope and we currently don't want to support that. Once we identify the need we could also extend the `ImageConfigs` to include a process class.
-
Was already documented.
Remove the knob before 1.0
> Deprecate AllowTagOverride

- controllers/backup_controller.go
- controllers/cluster_controller.go
- controllers/restore_controller.go
- docs/manual/operations.md
- setup/setup.go
Fixes: https://github.com/FoundationDB/fdb-kubernetes-operator/issues/841
The label selector is optional but allows users to operate multiple operators in the same namespace/cluster. 
Unit + local.
Added.
I create an issue to optimise the client cache.
> Add support for label selector

- api/v1beta1/foundationdbcluster_types.go
- api/v1beta1/foundationdbcluster_types_test.go
- kubectl-fdb/cmd/configuration.go
- kubectl-fdb/cmd/configuration_test.go
- kubectl-fdb/cmd/get.go
- kubectl-fdb/cmd/root.go
Add a plugin command that returns the configuration string based on the cluster spec e.g.:
```bash
$ /bin/kubectl-fdb get configuration --fail-over test
triple ssd-2 usable_regions=1 logs=3 proxies=3 resolvers=1 log_routers=-1 remote_logs=-1 log_version:=5 regions=[{\"datacenters\":[{\"id\":\"test\",\"priority\":1}]}]
```
-
Unit and local.
Added in the command.
The next step would be a fail-over command to change the cluster spec and make the operator fail-over the cluster.
> Add plugin command to get the configuration string

- controllers/update_pods.go
If we don't delay the requeue the operator can never delete process groups that are fully excluded. 
-
Local + unit
-
-
> Delay the requeue after the update Pods method deleted Pods

- Dockerfile
I don' see a harm here since we only copy the files into the build container. On the other hand we remove the surprises for user that want to change something in the Dockerfile or if they want to run tests in the (build) container.
-
Local.
-
Wee might consider in the future to load everything into the container and work with a `.dockerignore` file .
> Add missing go pkg to copy

- docs/design/thee_datahall.md
- docs/design/three_datahall.md
Design for https://github.com/FoundationDB/fdb-kubernetes-operator/issues/348 to support `three_data_hall` and `three_datacenter`
I think I covered all requirements for these redundancy modes.
None.
None.
Once the design is approach wI will create the according issues to work on.
> Add design for three_data_hall and three_datacenter

- controllers/cluster_controller.go
- controllers/cluster_controller_test.go
- internal/configmap_helper.go
- internal/configmap_helper_test.go
- internal/monitor_conf.go
- internal/monitor_conf_test.go
This fixes the handling of custom parameters with substitution variables.
Fixes #1016 
This will only work in old image with the separate sidecar image; it won't work with the unified image. I think that supporting it properly in the new image will require a more complex solution with structured custom parameters, but I wanted to get a fix in for the regression on this feature in the old image.
@johscheuer took a different approach in #1017, but closed that PR without …
> Fix handling of custom parameters with substitution variables.

- .github/workflows/pull_request.yml
- .github/workflows/release.yaml
- Dockerfile
- docs/backup_spec.md
- docs/cluster_spec.md
This moves the download source for FDB assets to GitHub rather than the FDB website. This is necessary in the short term while the website is under maintenance, but I think we can continue to use GitHub as the source of these assets in the long term. 
No.
I ran a local build of the operator with the new dockerfile.
*Do we need to perform additional testing once this is merged, or …
> Download FDB assets from GitHub rather than the FDB website.

- api/v1beta1/foundationdbcluster_types.go
- api/v1beta1/foundationdbcluster_types_test.go
- api/v1beta1/zz_generated.deepcopy.go
- config/crd/bases/apps.foundationdb.org_foundationdbclusters.yaml
- controllers/add_pods.go
- controllers/add_pods_test.go
- controllers/add_process_groups.go
- controllers/add_process_groups_test.go
- controllers/add_pvcs.go
- controllers/add_pvcs_test.go
- controllers/add_services.go
- controllers/add_services_test.go
- controllers/choose_removals.go
- controllers/choose_removals_test.go
- controllers/delete_pods_for_buggification.go
- controllers/exclude_processes.go
- controllers/metrics.go
- controllers/remove_process_groups.go
- controllers/replace_failed_process_groups_test.go
- controllers/update_labels.go
- controllers/update_pod_config.go
- controllers/update_pods.go
- controllers/update_sidecar_versions.go
- controllers/update_status.go
- controllers/update_status_test.go
- docs/cluster_spec.md
- internal/replacements/replace_failed_process_groups.go
- internal/replacements/replacements.go
- internal/replacements/replacements_test.go
- kubectl-fdb/cmd/analyze.go
Fixes: https://github.com/FoundationDB/fdb-kubernetes-operator/issues/982
This allows to see when a process group was removed or excluded without looking into the logs.
I added this as an addition and in another release we can drop the support for the boolean flags.
Unit + local testing:
```yaml
- addresses:
- 10.42.0.118
processClass: storage
processGroupID: storage-3
remove: true
removeTimestamp: "2021-11-26T17:52:41Z"
```
I can update the operation manual with the new variable.
-
> Add timestamp for remove and exclude

- controllers/update_labels.go
Fixes: https://github.com/FoundationDB/fdb-kubernetes-operator/issues/1037
-
local
-
-
> Don't log missing PVC for stateless processes

- controllers/update_status.go
Fixes: https://github.com/FoundationDB/fdb-kubernetes-operator/issues/995
We already added process groups for PVCs and Services, I think we should also do that for Pods to ensure we are not leaking resources.
Local.
-
-
> Refresh process group status and that Pods, PVCs and Services machting selector into account

- .github/ISSUE_TEMPLATE/bug_report.yml
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/enhancement.yml
Fixes: https://github.com/FoundationDB/fdb-kubernetes-operator/issues/735
I think those two templates are a good start and we can add more templates if we identify the need for it.
-
-
-
> Add issue templates

- config/samples/deployment.yaml
- config/samples/deployment/manager.yaml
- docs/manual/customization.md
- setup/setup.go
Add new cli flag `-watch-namespace` with same functionality as the `WATCH_NAMESPACE` env variable. For compatibility, I let the env var take precedence if set. 
Addresses issue: https://github.com/FoundationDB/fdb-kubernetes-operator/issues/659
> manager: add new cli flag `-watch-namespace`

- go.mod
- go.sum
Bumping fsnotify to 1.5.1 as 1.5.0 is marked as retracted
```
go: downloading github.com/FoundationDB/fdb-kubernetes-operator v0.51.1-0.20220211101952-c6fc0d975a0b
go: warning: github.com/fsnotify/fsnotify@v1.5.0: retracted by module author
go: to switch to the latest unretracted version, run:
go get github.com/fsnotify/fsnotify@latest
```
None.
Not needed.
> bump fsnotify to 1.5.1 as 1.5.0 is retracted

- kubectl-fdb/cmd/remove_process_group_test.go
In order to prevent a race condition we check if the returned list has all elements from the expected and if they have the same length. Before this a different ordering could result in a failure.
-
Unit test
-
-
> Fix race condition in test case

- api/v1beta1/foundationdbcluster_types.go
- fdbclient/admin_client.go
- fdbclient/admin_client_test.go
This change adds support for only checking with the `exclude` command for already excluded addresses if they are fully excluded and if they can be removed from the cluster. Before this change it could happen that we invoked the `CanSafelyRemove` method before an address was excluded in the exclude sub reconciler (which has some additional age checks). In order to be more restrictive and be safer I added a check to only run the exclude command for processes that are marked as excluded in the cluster status.
local testing and I will add some more unit tests.
-
I will create a design doc for some ideas how to improve the exclusion handling in the operator.
> Check if processes are excluded before run exclude command in CanSafelyRemove

- Makefile
- README.md
Support container builds for amd64 platform on Apple M1 (#1065)
I have retained the default behavior of building the image for the platform where we run `make rebuild-operator`. This can optionally be overridden by setting the environment variable `BUILD_PLATFORM="linux/amd64" make rebuild-operator`.
Tested manually by building amd64 image on Apple M1
Updated README
> Support container builds for amd64 platform on Apple M1 (#1065)

- config/samples/deployment.yaml
- config/samples/deployment/manager.yaml
This removes a flag from our sample deployments that isn't supported in the last stable release. This flag doesn't have any effect in the context where it was being used, because it was being set to the environment variable that is used as the default when the flag is omitted.
Resolves #1081 
I considered changing the version of the operator in the deployment to use the latest tag, but we would want to revert that in the future, and I don't think we need this flag in the …
> Remove the watch namespace flag from the sample deployment.

- .github/workflows/pull_request.yml
- .github/workflows/release.yaml
- Dockerfile
- distrolesss.dockerfile
Fixes: https://github.com/FoundationDB/fdb-kubernetes-operator/issues/1067 IO also fixed a bug that the latest image was not published anymore when we changed from `master` to `main`.
This adds a new slim image (which was the default previously) and the new default image will have centos8 as base image that allows people easier to debug any issues.
I currently have some tests running in GitHub and I ensured that the new image runs with centos8
-
-
> Add slim image

- config/development/debug_logs.yaml
- config/development/kustomization.yaml
- fdbclient/admin_client.go
- fdbclient/common.go
- fdbclient/lock_client.go
- setup/setup.go
This removes the creation of a new (not configured) logger in the fdbclient package instead we pass down the configured logger from our setup method. Now the status printout is correctly identified as debug log:
```
{"level":"info","ts":1647165605.8607554,"logger":"fdbclient","msg":"Fetch status from FDB","namespace":"default","cluster":"test-cluster"}
{"level":"debug","ts":1647165605.8626332,"logger":"controller-runtime.manager.events","msg":"Normal","object":{"kind":"FoundationDBCluster","namespace":"default","name":"test-cluster","uid":"876e80a3-d0ac-4174-9b8b-0f101401e9d4","apiVersion":"apps.foundationdb.org/v1beta2","resourceVersion":"662619"},"reason":"RemovingProcesses","message":"Removing pods: []"}
{"level":"debug","ts":1647165606.1626394,"logger":"fdbclient","msg":"Retrieved …
```
> Pass configured logger into fdbclient

- config/development/images.yaml
- config/tests/dns/client.yaml
- config/tests/dns/dns.yaml
- config/tests/dns/kustomization.yaml
- config/tests/tls/kustomization.yaml
- config/tests/unified_image/kustomization.yaml
- internal/monitor_conf.go
- internal/pod_client.go
This changes the way we handle unknown environment variables when evaluating the monitor conf, to handle cases where we want the monitor conf to reference environment variables that haven't been defined on all the pods yet. This comes up in the conversion process for DNS names, because we add a new environment variable to pass the DNS name into the locality config.
This also adds a release candidate version of FDB for use in the DNS name testing, and updates some test cases that were using older builds of the CRD.
The change to the handling of unspecified environment variables may be too broad, and may make it harder to detect problems where we haven't defined …
> Changes to support coordinator changes when using DNS names

- api/v1beta2/foundationdbcluster_types.go
- api/v1beta2/foundationdbcluster_types_test.go
- kubectl-fdb/cmd/remove_process_group.go
- kubectl-fdb/cmd/remove_process_group_test.go
Fixes: https://github.com/FoundationDB/fdb-kubernetes-operator/issues/1078
There was actual a bug in the old implementation in a way that we didn't added a processes group to the removal list without exclusions if the process was already marked as removal.
Local + unit.
-
-
> Fix flaky unit test and bug in process group removal

- .github/PULL_REQUEST_TEMPLATE.md
- Makefile
- README.md
Remove the `go get` command to install our dependencies and update our documentation
-
Locally tested `make deps`
-
-
> Remove the usage of go get and unused dep

- Makefile
Run Ginkgo specs in parallel (not the individual tests):
```bash
time go test -count=1 ./...
?       github.com/FoundationDB/fdb-kubernetes-operator [no test files]
ok      github.com/FoundationDB/fdb-kubernetes-operator/api/v1beta1     0.351s
ok      github.com/FoundationDB/fdb-kubernetes-operator/api/v1beta2     0.532s
?       github.com/FoundationDB/fdb-kubernetes-operator/cmd/po-docgen   [no test files]
ok      github.com/FoundationDB/fdb-kubernetes-operator/controllers     90.306s
ok      github.com/FoundationDB/fdb-kubernetes-operator/fdbclient       1.325s
ok      github.com/FoundationDB/fdb-kubernetes-operator/internal        0.964s
ok      github.com/FoundationDB/fdb-kubernetes-operator/internal/removals       0.634s
ok …
```
> Run specs in parallel

- .github/workflows/pull_request.yml
- .github/workflows/release.yaml
- .gitignore
- .goreleaser.yaml
- Makefile
- kubectl-fdb/Readme.md
Make use of go releaser (https://goreleaser.com/).
Fixes: https://github.com/FoundationDB/fdb-kubernetes-operator/issues/721
This simplifies the release process for the plugin and adds builds for Windows and arm64.
Example release: https://github.com/johscheuer/fdb-kubernetes-operator/releases/tag/v1.0.3
Locally + sample pipeline.
Adjusted.
-
> Make use of goreleaser for plugin

- api/v1beta2/foundationdb_database_configuration.go
- api/v1beta2/foundationdb_database_configuration_test.go
- config/crd/bases/apps.foundationdb.org_foundationdbclusters.yaml
- docs/cluster_spec.md
- docs/manual/debugging.md
- kubectl-fdb/cmd/analyze.go
- kubectl-fdb/cmd/analyze_test.go
- kubectl-fdb/cmd/configuration.go
- kubectl-fdb/cmd/configuration_test.go
- kubectl-fdb/cmd/cordon.go
- kubectl-fdb/cmd/cordon_test.go
- kubectl-fdb/cmd/deprecation.go
- kubectl-fdb/cmd/remove_process_group.go
- kubectl-fdb/cmd/remove_process_group_test.go
- kubectl-fdb/cmd/restart.go
- kubectl-fdb/cmd/root.go
Document the configuration sub command in the kubectl plugin and allow the plugin to update a cluster directly.
-
locally.
Added.
-
> Document failover with plugin and allow to update config

- .github/workflows/pull_request.yml
- .github/workflows/release.yaml
- Dockerfile
- distrolesss.dockerfile
Updates go to the latest 1.17 version with some security patches.
-
Locally + unit
-
-
> Update go version to 1.17.8

- controllers/add_pods.go
- controllers/add_pods_test.go
- docs/manual/technical_design.md
This fixes #970, which is an issue that can happen when some nodes crash (or are accidentally deleted, as happened in our case) while a cluster is in the process of being scaled down. If one or more of the nodes that crashed had been marked for removal but weren't fully drained before they crashed, we need to bring them back up again so that they can be drained before actually being shut down cleanly.
Bug fix (non-breaking change which fixes an issue).
This implementation of the fix relies on a previous run of the `removeProcessGroups` subreconciler having called `SetExcluded()` on process groups that FDB has confirmed to be fully excluded from the cluster (and saved that status to Kubernetes).
- Unit tests (including new tests in `controllers/add_pods_test.go`)
- Initiating a scale-down …
> Recreating pods that are not fully excluded.

- api/v1beta2/foundationdb_status.go
- fdbclient/admin_client.go
- fdbclient/admin_client_test.go
- internal/fdb_status_helper.go
- internal/fdb_status_helper_test.go
- kubectl-fdb/cmd/exclusion_status.go
- kubectl-fdb/cmd/get.go
- kubectl-fdb/cmd/k8s_client.go
Add an experimental plugin command to show the state of exclusions. This command is not finished and has some todos open but already offers some value.
I will check if the `stored_bytes` is the best indicator for how long it will take until the process is fully excluded.
Local.
None, will be added once the command is in a stable command.
Finish the to-dos.
> Experimental command for the plugin to show the state of exclusions

- controllers/remove_process_groups.go
- controllers/remove_process_groups_test.go
Fixes: https://github.com/FoundationDB/fdb-kubernetes-operator/issues/1144
-
Local + unit test.
-
-
> Ensure we delete all resources when a process group is in resource terminating state

- controllers/replace_failed_process_groups.go
- controllers/replace_failed_process_groups_test.go
- internal/replacements/replace_failed_process_groups.go
This prevents the operator from replacing process groups if the `EmptyMonitorConf` setting is set to true and all fdb processes are missing.
Before that the operator would try to replace the process groups.
Locally + unit test.
-
-
> Fix replacements with empty monitor conf setting

- kubectl-fdb/cmd/analyze.go
- kubectl-fdb/cmd/analyze_test.go
Fixes: https://github.com/FoundationDB/fdb-kubernetes-operator/issues/1068
The flag will be enabled by default and the result looks like this:
```bash
$ ./dist/kubectl-fdb_darwin_amd64/kubectl-fdb analyze test-cluster
Checking cluster: default/test-cluster
✔ Cluster is available
✔ Cluster is fully replicated
✔ Cluster is reconciled
⚠ ignored 1 process groups marked for removal
✔ ProcessGroups are all in ready condition
✔ Pods are all running and available
```
Local + unit
Added in code.
-
> Add flag to ignore removals

- api/v1beta2/foundationdb_database_configuration.go
- api/v1beta2/foundationdbcluster_types.go
- api/v1beta2/foundationdbcluster_types_test.go
- controllers/admin_client_test.go
- controllers/update_database_configuration.go
- controllers/update_status.go
Fixes  #1150 #1151. 
If proxies are set to 0, then grv_proxies/commit_proxies will be used in the configure string correctly and vice versa. Defaults have been set for all cases and added some extra logic in normalization of the status to account for that so that reconciliation completes.
Unit tests and local dev environment.
> role count fix

- controllers/update_pods.go
Adding a delay to the requeue if a Pod is in the terminating state. We already do this for the deletion step but we didn't added this for the terminating check: https://github.com/FoundationDB/fdb-kubernetes-operator/blob/main/controllers/update_pods.go#L237
Otherwise this might block any ongoing replacements for no reason.
Local + unit test.
-
-
> Delay requeue for terminating Pod in update pods

- controllers/cluster_controller.go
- internal/pod_client.go
- setup/setup.go
Fixes: https://github.com/FoundationDB/fdb-kubernetes-operator/issues/1177 this allows to configure the timeout e.g. when you're using debug binaries which take longer to be copied.
-
Unit + local.
-
-
> Add flags for http timeouts

- controllers/remove_process_groups_test.go
Fixes: https://github.com/FoundationDB/fdb-kubernetes-operator/issues/1163
The issue was a underlying race condition on how fast the process groups were removed.
Unit tests.
-
-
> Fix wrong setting for test case

- .goreleaser.yaml
Remove the CGO env for the plugin, there is no need to build it without CGO.
- Bug fix (non-breaking change which fixes an issue)r
-
Locally.
-
-
> Remove CGO setting for building the plugin

- api/v1beta2/foundationdb_database_configuration.go
- api/v1beta2/foundationdbcluster_types.go
- api/v1beta2/foundationdbcluster_types_test.go
- internal/pod_models.go
Fixes: https://github.com/FoundationDB/fdb-kubernetes-operator/issues/1179 this change makes upgrades easier since all three proxies can be defined before upgrading and after the upgrade the more precise definition (grv and commit) of proxies will be used.
-
Local + unit test
I'll add that in a separate PR to document the upgrade process in general.
-
> For versions that support grv and commit use grv and commit proxy count if defined

- fdbclient/admin_client.go
- fdbclient/admin_client_test.go
The idea here is to run the exclusion check in two steps:
1. Check all processes that are already fully excluded (don't serve any roles), this is only an additional safety check and shouldn't be required actually.
2. Check all exclusions that are "in progress"
The benefit of this approach is that a slow exclusion doesn't block the removal of other process groups that are already fully excluded.
-
Unit tests + locally.
Like commented here: https://github.com/apple/foundationdb/issues/6854#issuecomment-1110608724 it would actually be nice if FDB would offer this functionality. if I get some spare time I might look into creating this in the c bindings. 
*Are there any follow-up issues that …
> Check exclusion status of fully excluded and in progress exclusions in two steps

- controllers/remove_process_groups.go
In `remove_process_group.go` we are throwing an error for multiple occurrences of an instance using `len(x) > 0`. This should be greater than 1. 
-
Did unit testing for the same. 
-
-
> updating the logic for check more than 1 value

- api/v1beta2/foundationdb_version.go
- internal/pod_client.go
Fixes: https://github.com/FoundationDB/fdb-kubernetes-operator/issues/1205 in addition to that this PR fixes a bug in the `is_present` method.
Before this change we never checked the response of the `check_hash` call in the `is_present`, that means the operator thought the file would be there even if the sidecar returned a `404`.
Unit + local testing with a own build sidecar.
-
-
> Add support for is present and fix a bug in is_present

- Makefile
This allows to run the Makefile and use a different kubernetes context or namespace.
-
Locally.
-
-
> Add kubetl args for Makefile

- api/v1beta2/foundationdbcluster_types.go
- api/v1beta2/foundationdbcluster_types_test.go
- docs/manual/replacements_and_deletions.md
Fixes: https://github.com/FoundationDB/fdb-kubernetes-operator/issues/1213
This should catch the case where a Pod is deleted (or in a deleted state) but the process is still running.
Unit testing.
-
-
> Add more conditions for automatic replacement

- go.mod
- go.sum
Updates the go bindings to [7.1.5](https://github.com/apple/foundationdb/tree/7.1.5)
- Other (Version update)
-
Unit + local
-
-
> Update go bindings for operator

- controllers/metrics.go
- controllers/metrics_test.go
Fixes: https://github.com/FoundationDB/fdb-kubernetes-operator/issues/1215
-
Unit + local:
```bash
$ curl -s localhost:8080/metrics | rg 'fdb_operator_desired'
fdb_operator_desired_process_group_total{name="test-cluster",namespace="default",process_class="cluster_controller"} 1
fdb_operator_desired_process_group_total{name="test-cluster",namespace="default",process_class="log"} 4
fdb_operator_desired_process_group_total{name="test-cluster",namespace="default",process_class="storage"} 3
```
-
-
> Add metrics to reflect the desired number of processes

- controllers/cluster_controller.go
This is working around an issue when disabling DNS names, where we were removing the headless service before the replacement transaction processes were able to come up, leaving them stuck indefinitely.
Fixes #1226 
This is relying on indirect properties, and the ordering of steps, in order to determine whether the DNS names are required. I don't know if we want to rely on that, or if we want to have a more explicit signal. However, designing that signal would be more …
> Move the remove services set to after we remove process groups.

- Dockerfile
- docs/compatibility.md
- docs/fdb_release_prep.md
- docs/manual/customization.md
- docs/manual/index.md
- docs/manual/operator_customization.md
- go.mod
- go.sum
- main.go
This reverts the builds to use version 6.2 of the FDB binding and client package, and increases the API version selected at runtime to `620`. This aligns all these points of configuration with the oldest supported version of FDB, and avoids issues with using older client libraries with newer versions of the bindings.
No.
I've tested this build manually against 6.3 clusters to …
> Revert to an older FDB version.

- .github/workflows/pull_request.yml
- .github/workflows/release.yaml
- Dockerfile
- distrolesss.dockerfile
Update the used go version to the latest 1.17 with the latest security fixes.
- Other
-
Locally.
-
-
> Update go version to 1.17.11 and correct the same FDB library

- Makefile
The command `sed` is failing on Mac as it explicitly requires the `-e` option for `sed` to work.  This command is used in the Makefile to replace `Role` with `ClusterRole` in the role.yaml file 
Before this PR error:
```# Per default controller-gen will generate a ClusterRole for our example we want to use a Role and the namespace marker doesn't
sed: 1: "./config/rbac/role.yaml": invalid command code .
```
√ Bug fix (non-breaking change which fixes an issue)
- Other
*Please describe the tests that you ran …
> update sed command to run on Mac

- controllers/remove_process_groups_test.go
This should ensure that our CI pipelines pass constantly. We should look into the flaky test in addition to decide how to fix it or if it should be removed.
This is only a workaround to retry the flaky test automatically.
-
-
-
> Retry flaky test

- .github/workflows/pull_request.yml
- .github/workflows/release.yaml
Part of https://github.com/FoundationDB/fdb-kubernetes-operator/issues/1271
The new helm chart release will create tags like `fdb-operator-0.2`, those are not server compatible with goreleaser, so we have to pull the latest server compatible tag ourself (goreleaser doesn't support this).
I tested this in my fork: e.g. https://github.com/johscheuer/fdb-kubernetes-operator/runs/7146785492?check_suite_focus=true
-
-
> Fix how goreleaser fetches the current tag

- controllers/update_database_configuration.go
- controllers/update_pods.go
- controllers/update_status.go
Found this bug during some HA upgrade tests. This bug was introduced in https://github.com/FoundationDB/fdb-kubernetes-operator/pull/1187. Running multiple reconfigure commands should be relatively harmless but they trigger probably a new recruitment of the transaction system which means we see more recoveries. 
-
Unit testing + e2e tests.
-
-
> Fix bug where config update is triggered to often

- kubectl-fdb/cmd/analyze.go
This changes the help text for the analyze command to remove the word "cluster" in some examples where it doesn't seem correct.
No.
I ran the unit tests locally.
No.
Yes.
No. …
> Remove the keyword "cluster" from the examples for the analyze command.

- api/v1beta1/foundationdbcluster_types.go
- api/v1beta2/foundationdbcluster_types.go
- docs/cluster_spec.md
- docs/manual/replacements_and_deletions.md
- internal/deprecations_test.go
Updated the default value for failure detection time to 2 hours from 30 mins.
- Other
No
Updated the existing test case with correct value. 
*If this change is adding or …
> updating the default time for failure detection

- api/v1beta2/foundationdbcluster_types.go
- controllers/bounce_processes.go
- controllers/exclude_processes.go
- controllers/update_pod_config.go
Make the rollout process for config changes more reliable to process groups that are in an unreachable status.
I think it's safe to ignore process groups if their sidecar is unreachable otherwise one single process group might block the whole reconciliation.
Locally. Will add an additional e2e test before merging.
-
-
> Ignore process groups if they have the sidecar unreachable condition in the bounce sub reconciler

- fdbclient/admin_client.go
- fdbclient/common.go
Adds a logging call when we read a value from FDB with the fdb client and add an additional log when the call ended to see how long the call took.
-
Locally.
-
-
> Add better logging for fdb client calls

- fdbclient/admin_client.go
- fdbclient/admin_client_test.go
- fdbclient/common.go
Fixes: https://github.com/FoundationDB/fdb-kubernetes-operator/issues/1308
This ensures that the command returns the current connection string.
e2e.
-
-
> Correct the way how the connection string is read

- controllers/bounce_processes.go
- controllers/bounce_processes_test.go
Ignore processes that are excluded when calculating the minimum uptime.
Unit tests
> Ignore excluded processes from minimum uptime calculation when doing a rolling bounce

- controllers/remove_incompatible_processes.go
- controllers/remove_incompatible_processes_test.go
Fixes: https://github.com/FoundationDB/fdb-kubernetes-operator/issues/1337
See the issue for more details.
Unit tests + e2e tests.
-
-
> Only run remove incompatible processes sub reconciler when cluster was upgraded

- .github/workflows/pull_request.yml
In https://github.com/FoundationDB/fdb-kubernetes-operator/pull/1355 we did some refactoring and missed to add the login step if we operator on the main branch.
-
-
-
-
> Add Docker login back for pushing from main

- api/v1beta2/foundationdb_database_configuration.go
- api/v1beta2/foundationdb_database_configuration_test.go
- api/v1beta2/foundationdbcluster_types.go
- config/crd/bases/apps.foundationdb.org_foundationdbclusters.yaml
- docs/cluster_spec.md
Fixes: https://github.com/FoundationDB/fdb-kubernetes-operator/issues/1298
Sadly the current CRD setup (not the setup in our repository) doesn't allow "complex" jsonpath queries, so we have to add two different fields in the kubectl output. The `priority: 1` means that those fields are only be present in the output if someone runs `kubectl get fdb ... -o wide`
Local testing and unit tests.
-
-
> Add support for desired and reconciled process groups in status

- fdbclient/admin_client.go
- fdbclient/common.go
- setup/setup.go
Fixes: https://github.com/FoundationDB/fdb-kubernetes-operator/issues/1302
-
Unit test + local testing.
-
-
> Make use of time.duration instead of int for timeout

- api/v1beta2/foundationdb_database_configuration.go
- api/v1beta2/foundationdbcluster_types.go
- api/v1beta2/foundationdbcluster_types_test.go
- api/v1beta2/groupversion_info.go
- controllers/bounce_processes.go
If we disable to restart FDB processes we want to skip any further work and just skip the whole reconciler.
-
Local testing + unit tests.
-
-
> Ensure we skip all work in the bounce reconciler if we disable restarts

- api/v1beta1/foundationdb_database_configuration.go
- api/v1beta2/foundationdb_database_configuration.go
- config/crd/bases/apps.foundationdb.org_foundationdbclusters.yaml
- controllers/cluster_controller.go
- controllers/cluster_controller_test.go
- docs/cluster_spec.md
- internal/monitor_conf_test.go
This PR adds "test" processCount.
This changes are based on discussion under 
https://github.com/FoundationDB/fdb-kubernetes-operator/issues/1346
Unit test
Yes, added description in fdb cluster page.
Add deprecation for tester
Does not have anything
> Add test process count

- internal/pod_client.go
- internal/pod_client_test.go
If the operator is not able to communicate with the sidecar HTTP server an error will be returned and the response will be nil. In the current implementation this would lead to a nil pointer exception: `panic: runtime error: invalid memory address or nil pointer dereference`
Local testing + e2e tests.
-
-
> Fix nil pointer error

- controllers/update_status.go
- fdbclient/admin_client.go
The multi-version client library should be able to automatically detect the correct version to communicate with the FDB cluster.
I believe this is in general the right direction to use the client library where possible instead of having our code try multiple different configurations.
Local testing and unit tests.
-
-
> Make use of client library to get the connection string

- .golangci.yml
- fdbclient/admin_client.go
- fdbclient/common.go
- internal/error_helper.go
- internal/pod_client_test.go
Enable the `errorlint` in out listing setup.
-
Run local tests and the lint command.
-
-
> Enable error linting in code base

- controllers/bounce_processes.go
- controllers/bounce_processes_test.go
- internal/restarts/restarts.go
- internal/restarts/restarts_test.go
- internal/restarts/suite_test.go
Ensure we wait for all processes before doing the upgrade and don't skip processes in the `SidecarUnreachable` state. I believe in the long term we want to implement some kind of a ratio to ignore some processes before doing the upgrade (instead of blocking until the issue is resolved).
See above, we probably want to rethink the upgrade prerequisites to not require all processes being ready to be upgraded but rather a % or fixed number of processes.
Unit tests + I tested this with the e2e tests to ensure the upgrade is blocked until all processes are "ready" to be upgraded.
-
-
> If the cluster is upgraded wait for all processes to be ready

- controllers/exclude_processes.go
Remove the lock mechanism from the exclude reconciler.
- Other
The initial idea of the lock was to reduce the risk of successive recoveries. This is only true if the exclude is happening in a different Kubernetes cluster/namespace not managed by this operator instance. Exclusions in the same namespace can still trigger successive recoveries. A drawback of this approach is that an exclusion in another Kubernetes cluster/namespace might be delay until this operator instance can get a lock.
If we want to use some safeguards around the exclusion we could think of using the minimum uptime, similar to the bounce reconciler.
unit tests.
-
-
> Remove lock for exclusions

- fdbclient/admin_client.go
- fdbclient/common.go
- fdbclient/common_test.go
This removes a resource leak. Before that we never removed the cluster files when we use lock client or if we used the client libraries.
This change will add a `Close()` method to the lock client to ensure the files are removed once the lock client is not required anymore.
Local testing + unit tests.
-
-
> Use deterministic name for cluster file

- controllers/admin_client_test.go
- controllers/backup_controller.go
- controllers/backup_controller_test.go
- controllers/bounce_processes_test.go
- controllers/change_coordinators.go
- controllers/change_coordinators_test.go
- controllers/choose_removals_test.go
- controllers/cluster_controller.go
- controllers/cluster_controller_test.go
- controllers/maintenance_mode_checker_test.go
- controllers/remove_incompatible_processes_test.go
- controllers/remove_process_groups_test.go
- controllers/replace_failed_process_groups_test.go
- controllers/restore_controller.go
- controllers/restore_controller_test.go
- controllers/suite_test.go
- controllers/update_lock_configuration_test.go
- controllers/update_status_test.go
- fdbclient/common.go
- pkg/fdbadminclient/admin_client.go
- pkg/fdbadminclient/database_provider.go
- pkg/fdbadminclient/mock/admin_client_mock.go
- pkg/fdbadminclient/mock/admin_client_mock_test.go
- pkg/fdbadminclient/mock/database_provider.go
- pkg/fdbadminclient/mock/lock_client.go
- pkg/fdbadminclient/mock/lock_client_test.go
- pkg/fdbadminclient/mock/suite_test.go
This will expose the mock implementations for the AdminClient and the LockClient. The idea is to make it available for users of the fdbclient package for unit tests.
Since we are moving things around this will be a breaking change but my exception is that this allows users to use the mock client without breaking to many things in the future.
Local testing with another test repository.
-
-
> Expose mock admin client and lock client

- controllers/suite_test.go
- controllers/update_lock_configuration_test.go
- controllers/update_pod_config.go
- internal/locality/locality_test.go
- internal/monitor_conf.go
- internal/monitor_conf_test.go
- internal/pod_client.go
- pkg/fdbadminclient/mock/admin_client_mock.go
- pkg/podclient/mock/pod_client.go
This allows to use the mock Pod Client in different repositories and make it easier to consume/test the Pod client interface.
- Other
This is not a breaking change, since all interfaces stay the same.
Unit tests + e2e pipeline.
-
-
> Expose Pod Mock Client for testing

- controllers/bounce_processes.go
- mock-kubernetes-client/client/client.go
- pkg/fdbadminclient/mock/admin_client_mock.go
- pkg/fdbadminclient/mock/admin_client_mock_test.go
- pkg/fdbadminclient/mock/suite_test.go
> Initial changes to remove update Pod config in bounce reconciler

- controllers/cluster_controller_test.go
- controllers/update_database_configuration.go
This change ensures that the operator is not performing any actions if we set `configureDatabase` to false. The idea is to reduce the load on the FDB cluster.
- Other
-
Unit tests and e2e tests.
-
-
> If configure database is set to false skip all work

- mock-kubernetes-client/client/client.go
- mock-kubernetes-client/client/client_test.go
This is a similar feature to the create hooks, were a user can define a custom method that will be executed during the creation of objects, just for the update method. This will be helpful to mock controllers that manages other resources (like a replicaSet).
-
Unit tests.
It's probably worth creating a new PR + issue to better document our mock client implementation.
-
> Add update hooks to the mock Kubernetes client

- internal/restarts/restarts.go
- internal/restarts/restarts_test.go
This ensures that the ConfigMap is synced before restarting processes (this includes the generated fdbmonitor file). The current behaviour only works because of this bug: https://github.com/FoundationDB/fdb-kubernetes-operator/issues/611
-
Unit tests and e2e tests.
-
-
> Ensure that the configmap is synced before restarting processes

- .github/workflows/pull_request.yml
Remove old failing Kubernetes version from tests.
-
CI.
-
-
> Remove old Kubernetes version from tests

- Makefile
Some editor litter file copies in directory when editing, and we just glob over all those  files right now. This one makes Make ignore ones made by emacs.
> make: don't target emacs autosave files

- api/v1beta2/foundationdb_labels.go
- api/v1beta2/foundationdbcluster_types.go
- controllers/bounce_processes.go
- controllers/bounce_processes_test.go
- controllers/remove_incompatible_processes.go
- controllers/remove_process_groups.go
- internal/fault_tolerance.go
- pkg/fdbadminclient/mock/admin_client_mock.go
This is an attempt to relax the constraint for upgrades to ensure we account for scenarios where some processes are already upgraded (or are missing). Otherwise it could happen that a upgrade is blocked by a single process that was restarted and is already running on the new version.
-
Unit tests + e2e tests.
I will write down a more in depth document about the upgrade process: https://github.com/FoundationDB/fdb-kubernetes-operator/issues/1473
See above.
> Improve operator restart logic for upgrades

- controllers/remove_incompatible_processes.go
Ensure we are not blocking the next steps of the reconciliation if the removeIncompatibleProcesses get's an error back, e.g. because the FDB cluster is unavailable.
-
Local + e2e.
N/A
-
> Make sure we do a delayed reconcile if the incompatible check has an error

- docs/manual/getting_started.md
- scripts/setup_e2e.sh
Add comment on the environment where the setup_e2e.sh can work out of box. 
Fix a broken link in getting_started.md.
> Add recommended running env for setup_e2e.sh and fix a broken link in getting_started

- controllers/exclude_processes.go
- controllers/remove_incompatible_processes.go
- controllers/remove_incompatible_processes_test.go
- controllers/update_database_configuration.go
- fdbclient/admin_client.go
- fdbclient/admin_client_test.go
- fdbclient/command_runner.go
- fdbclient/command_runner_test.go
- fdbclient/common.go
This change makes sure we are not setting any FDB environment variables for the `fdbcli` command to prevent the use of the multi version client for 7.1+ fdbclis. In addition we added more fallback logic to the `GetStatus` method to transparently try the new (desired) version if the runningVersion is not working.
This adds some more complexity around the upgrade handling but the multi version client is not reliable in cases where not all coordinators are upgraded.
I will see if I can add some additional unit tests and I will do a test with out new upgrade test.
Will be covered in the other upgrade doc issue.
-
> Improve the way how the operator handles partitial upgrades

- api/v1beta2/foundationdbcluster_types.go
- internal/pod_models.go
- internal/pod_models_test.go
- kubectl-fdb/cmd/analyze.go
- kubectl-fdb/cmd/cordon.go
- kubectl-fdb/cmd/cordon_test.go
- kubectl-fdb/cmd/root.go
- kubectl-fdb/cmd/suite_test.go
Currently the `cordon` command in plugin requires a cluster name to remove all the pods that are running of a specific node on a cluster. This PR is to extend that behaviour to remove all the pods that are running on that node irrespective of the cluster name. This requires us to use a new flag `use-custom-label` which enables this new feature and then we also need to provide a `custom-label`. The default value of `custom-label` is `fdb-cluster-name` is nothing was given. 
*Are there any design details that you would like to discuss …
> extending the cordon command for all clusters

- api/v1beta1/foundationdbcluster_types.go
- api/v1beta2/foundationdbcluster_types.go
- docs/cluster_spec.md
- kubectl-fdb/cmd/root.go
ReplaceProcessGroup procedure has typo in its help message and comment.
This PR fixex the typos.
No functional change.
No testing since it's not changing functionality.
> Correct typo for replaceProcessGroup

- fdbclient/lock_client.go
In https://github.com/FoundationDB/fdb-kubernetes-operator/pull/1498 we added a new typed string but we forgot to adjust the type in some places.
-
e2e test. Currently this code path is not unit tested, I'm. going to create a new issue for doing that.
-
-
> Fix the internal handling of the lock client for get pending upgrades

- controllers/bounce_processes.go
In https://github.com/FoundationDB/fdb-kubernetes-operator/pull/1474/files#diff-d0bee063a26a37c83244adbffd63b8a0daaf66032647b5e17bd78e0ca4cf4310R254 we made a change to check for fault tolerance and not only for availability. In theory this sounds like a good idea but we discovered in our e2e testings that this can block the operator from moving forward with the upgrade e.g. in the case where some processes are restarted before the operator dis the `kill` command.
-
e2e tests.
Will be updated in https://github.com/FoundationDB/fdb-kubernetes-operator/pull/1511
-
> Revert fault tolerance check to only check availability

- setup/setup.go
- setup/setup_test.go
- setup/suite_test.go
Allow to specify a different set of permissions for the operator logs. The default changed in a newer version of lumberjack (https://github.com/natefinch/lumberjack/issues/82). This PR adds support to specific the desired permission for the log output file.
Unit tests.
Done in the flag method.
-
> Fix permission issue for log file writer

- api/v1beta2/foundationdb_process_class.go
- api/v1beta2/foundationdb_status.go
- api/v1beta2/foundationdb_status_test.go
ProcessRole and ProcessClass, the two types didn't include all the existing roles and classes, this PR complements them.
No.
No.
No, didn't need to update any doc.
No.
> Complement ProcessRole and ProcessClass

- api/v1beta2/foundationdb_database_configuration.go
- api/v1beta2/foundationdb_version.go
- api/v1beta2/foundationdbcluster_types_test.go
- controllers/cluster_controller_test.go
FDB 7.0.0 is the first release of the Redwood Storage Engine. This PR complements version supporting check for Redwood Experimental storage engine type. 
No.
Manual testing.
I think no additional testing needed once this is merge.
Didn't update any documentation. I just complemented the operator part, didn't summary any new doc.
No.
> Add Version Check to Redwood Experimental Storage Engine Type

- api/v1beta2/foundationdbcluster_types.go
- controllers/admin_client_test.go
- controllers/cluster_controller_test.go
- controllers/generate_initial_cluster_file.go
Modify the initial cluster file sub reconciler to make use of the coordinator selection mechanism. And, update the affected tests.
Addresses issue: https://github.com/FoundationDB/fdb-kubernetes-operator/issues/1089
- Does the current operator logic always select storage processes as coordinators? If so, this PR may cause log processes to also be selected as coordinators? And, if so, what is the impact of that during recovery? So, overall, is this a good change?
Ran the operator unit tests successfully (by doing "make fmt lint test").
TBD: Do we need to update any documentation?
> Generate initial cluster file based on "CoordinatorSelection"

- controllers/suite_test.go
- controllers/update_pods.go
- controllers/update_pods_test.go
This is mainly a refactoring to make the `getPodsToUpdate` method testable.
Unit tests + e2e test.
-
Nothing.
> Ensure we are not blocking if the operator is not able to get the Pod client

- fdbclient/admin_client.go
Adding back the `status` request when killing fdbserver processes to ensure the reboot request was sent to all processes.
We had this check in an earlier version of the fdbclient but then removed it. This change adds it back again to ensure the reboot command is sent to all processes.
e2e test.
-
-
> Add longer delay after kill command

- api/v1beta2/foundationdbcluster_types.go
- config/crd/bases/apps.foundationdb.org_foundationdbclusters.yaml
Add validation pattern to ProcessGroupIDPrefix.
Addresses issue: https://github.com/FoundationDB/fdb-kubernetes-operator/issues/1096
- Ran operator unit tests (by running "make fmt lint test")
> Add validation pattern to ProcessGroupIDPrefix

- config/deployment/manager.yaml
- config/samples/backup.yaml
- config/samples/client.yaml
- config/samples/cluster.yaml
- config/samples/deployment.yaml
- config/samples/restore.yaml
- config/tests/backup/base/backup.yaml
- config/tests/base/cluster.yaml
- config/tests/client/client.yaml
- config/tests/dns/client.yaml
- config/tests/dns/dns.yaml
- config/tests/multi_dc/final.yaml
- config/tests/multi_dc/stage_1.yaml
- config/tests/multi_kc/final.yaml
- config/tests/multi_kc/stage_1.yaml
- docs/manual/backup.md
- docs/manual/customization.md
- docs/manual/fault_domains.md
- docs/manual/getting_started.md
- docs/manual/operations.md
- docs/manual/scaling.md
- docs/manual/tls.md
Fixes: https://github.com/FoundationDB/fdb-kubernetes-operator/issues/560 and updates the example version for FDB clusters.
-
-
Updated
-
> Update examples and better document how to run a multi-region FDB cluster

- docs/design/node_taint_eviction.md
Initial work for: https://github.com/FoundationDB/fdb-kubernetes-operator/issues/1492
The focus of the doc is to handle nodes that are tainted. We could extend the design to also handle nodes that are in a `NotReady` state but still host Pods.
-
Updated the design.
Implementation.
> Initial design for replacing Pods running on tainted nodes

- controllers/add_services_test.go
- controllers/bounce_processes.go
- controllers/change_coordinators_test.go
- controllers/choose_removals_test.go
- controllers/cluster_controller.go
- controllers/cluster_controller_test.go
- controllers/suite_test.go
- controllers/update_pod_config.go
- controllers/update_status.go
- controllers/update_status_test.go
- internal/configmap_helper.go
- internal/fdb_status_helper_test.go
- internal/foundationdb_status.go
- internal/foundationdb_status_test.go
- internal/locality/locality.go
- internal/locality/locality_test.go
- pkg/fdbadminclient/mock/admin_client_mock.go
This change makes sure we are not using the ConfigMap Annotation to check if a Pod has all the recent files. This can be critical during upgrades when the Annotation was already updated to another value.
This will result in a higher resource consumption on the operator side since the operator has to do those requests in 2 different places.
Unit tests and e2e tests will be running.
-
-
> Make sure we always check the sidecar to get the most recent information about the updated ConfigMap

- fdbclient/admin_client.go
- fdbclient/admin_client_test.go
- fdbclient/common.go
- fdbclient/fdb_client.go
We've seen some issues with the frequent calling of the `fdbcli exclude` command to check if a process is excluded from the operator side. We already have logic in the operator code to check if a process is safe to delete (serves no roles) based on the cluster status. The only case where we want to call the exclude command is when the operator has an address that is missing in the cluster status json.
Most of the code changes are unit tests to ensure we cover all important cases.
Unit tests and the CI pipeline will run the e2e tests.
We don't have a dedicated doc for how the operator handles exclusions, I think it would be a good idea to start a doc in a different PR: …
> Ensure we call exclude only on missing processes

- e2e/fixtures/chaos_common.go
- e2e/fixtures/chaos_disk.go
- e2e/fixtures/chaos_http.go
- e2e/fixtures/fdb_cluster.go
- e2e/fixtures/fdb_cluster_specs.go
- e2e/test_operator_upgrades/operator_upgrades_test.go
- go.mod
- go.sum
- internal/pod_client.go
Adding a new test case to ensure the upgrade is blocked if not all Pods are ready to be restarted.
- Other
I ran a manual test:
```text
[AfterSuite]
/Users/jscheuermann/go/src/github.com/FoundationDB/fdb-kubernetes-operator/e2e/test_operator_upgrades/operator_upgrades_test.go:36
[ReportAfterSuite] PASSED [0.011 seconds]
Ran 1 of 11 Specs in 269.758 seconds
SUCCESS! -- 1 Passed | 0 Failed | 0 Pending | 10 Skipped
PASS | FOCUSED
FAIL …
```
> Add an upgrade test case where one sidecar is not ready for the upgrade

- e2e/fixtures/factory.go
- e2e/fixtures/fdb_operator_client.go
- e2e/fixtures/singleton.go
Fix the way how the sidecar is used in the operator setup. I removed the singleton setup and created a method in the factory struct. This should simplify the usage of the images.
-
I did a local run with a different registry.
-
-
> Correct the way how the provided images and registry are used

- e2e/test_operator_upgrades/operator_upgrades_test.go
This test makes sure that our upgrade is stuck when the new binary is missing from one of the Pods.
- Other
-
Ran the test manually:
```text
2023/03/29 07:44:44 storage-2 IncorrectCommandLine
2023/03/29 07:45:13 finished all tests, start deleting namespace jscheuermann-xtfzxidt
• [288.991 seconds]
[AfterSuite]
/Users/jscheuermann/go/src/github.com/FoundationDB/fdb-kubernetes-operator/e2e/test_operator_upgrades/operator_upgrades_test.go:53
[ReportAfterSuite] PASSED [0.004 seconds]
Ran 1 of 12 Specs in 288.991 seconds
SUCCESS! -- 1 Passed | 0 Failed | 0 Pending | 11 …
```
> Add test case to validate that the upgrade is stuck when the new binary is missing

- e2e/fixtures/factory.go
- e2e/fixtures/status.go
- e2e/test_operator_upgrades/operator_upgrades_test.go
This change makes the status invariant checker more robust during upgrades. If the operator is not able to communicate to the quorum of the coordinator we cannot make any assumption about the cluster state.
-
Running e2e tests locally (will report once they finished).
Added in code.
-
> Ensure we only mark the database as unavailable if we can talk to the majority of coordinators

- e2e/fixtures/factory.go
- e2e/fixtures/fdb_operator_client.go
- e2e/fixtures/options.go
- e2e/fixtures/upgrade_test_configuration.go
Expose the sidecar config to make it easier to consume it from outside the test suite.
- Other
I changed the type from string to fdbv1beta2.version to remove some steps where we parsed the version multiple times.
Ran a an e2e upgrade test.
Added in the code itself.
-
> Refactor e2e test suite to make it easier to use the sidecar config

- .github/workflows/pull_request.yml
I hit an issue in #1301 where the PRB checks were failing because the PR added new fields in both the CRD and the samples, and the fields weren't available when the samples were validated. This adds an additional check that the CRD updates are complete between the steps where the CRDs are installed and when the samples are validated.
No.
I've run the steps in the PRB locally.
*Do …
> Add an additional wait after installing CRDs in pull request tests.

- e2e/fixtures/fdb_cluster_specs.go
This change should allow the 7.1 -> 7.2 upgrades to succeed.
Fixes: https://github.com/FoundationDB/fdb-kubernetes-operator/issues/1566
-
I will run a test upgrade from 7.1 -> 7.2
I add the documentation for the upgrades from 7.1 -> 7.2 in another doc.
Add documentation for the upgrade setup.
> Add ignore log group in e2e tests

- e2e/Makefile
Make use of the latest FDB 7.1 release (7.1.31) for our e2e tests.
- Other
This should resolved the last flakiness of our tests where we same the exclude command failing with `10% free space`.
e2e pipeline will be running.
-
-
> Update FDB version used for e2e tests

- e2e/fixtures/cluster_config.go
- e2e/fixtures/cluster_config_test.go
- e2e/fixtures/suite_test.go
Fixes a bug in the calculation of the resources for storage processes in a performance cluster.
-
Added unit tests for the resource generation.
-
Add more tests around our testing framework as some steps are more complex.
> Fix the way the resources for storage processes are calculated in the e2e test framework

- fdbclient/admin_client.go
- fdbclient/admin_client_test.go
Only perform the exclusion check if we have 1 active generation, otherwise assume no process is fully excluded.
-
Unit tests + e2e tests are running.
-
Implement: https://github.com/FoundationDB/fdb-kubernetes-operator/issues/990 (will only work for 7+ clusters)
> Make sure to only check exclusions if we have 1 active generation

- controllers/bounce_processes.go
- controllers/bounce_processes_test.go
- e2e/test_operator_ha_upgrades/operator_ha_upgrade_test.go
- internal/buggify/buggify.go
Test upgrading an HA cluster when no remote processes are restarted.
Co-authored by: Johannes Scheuermann
- Other (testing related)
No.
Ran the test locally. (Did four runs today, one of those runs didn't complete after about half-an-hour, I think (at which point I stopped the test), the other runs completed successfully.)
Yes (we will need to run this test as part of regression testing).
*If this change is adding new …
> Test upgrade when no remote processes are restarted

- e2e/fixtures/fdb_cluster.go
- e2e/fixtures/ha_fdb_cluster.go
- e2e/test_operator_ha_upgrades/operator_ha_upgrade_test.go
- e2e/test_operator_upgrades/operator_upgrades_test.go
Make sure we force a reconciliation after some time for the upgrade `verifyVersion` method and make sure we dump the state to make debugging easier.
-
Ran tests manually.
-
-
> Make sure we use the force reconcile method if needed and we dump the state if an upgrade is stuck

- api/v1beta2/foundationdbcluster_types.go
- api/v1beta2/foundationdbcluster_types_test.go
- controllers/add_pods.go
- controllers/delete_pods_for_buggification.go
- controllers/generate_initial_cluster_file.go
- controllers/remove_incompatible_processes.go
- controllers/replace_failed_process_groups_test.go
- controllers/replace_misconfigured_process_groups.go
- controllers/suite_test.go
- controllers/update_labels.go
- controllers/update_pod_config.go
- controllers/update_pods.go
- controllers/update_pods_test.go
- controllers/update_sidecar_versions.go
- controllers/update_status.go
- controllers/update_status_test.go
- internal/pod_helper.go
- internal/replacements/replacements.go
- internal/replacements/replacements_test.go
- internal/replacements/suite_test.go
- pkg/podmanager/pod_lifecycle_manager.go
Fixes: https://github.com/FoundationDB/fdb-kubernetes-operator/issues/1612
For large clusters it will be more efficient to use the controller-runtime cache directly instead of doing a list and then building our own cache on top of the controller-runtime cache.
This is a breaking change as we extend the `PodLifecycleManager` interface.
Adjusted unit tests and e2e tests will be running.
-
Could be: https://github.com/FoundationDB/fdb-kubernetes-operator/issues/1619 to make sure we reduce the number of conversions and parsing in our operator.
> Remove the internal Pod map and use the controller runtime cache

- e2e/README.md
running the provided commands threw an error:
```
fdb-kubernetes-operator/e2e/scripts/setup_e2e.sh: line 74: helm: command not found
```
Installing helm in the testing machine fixed it. 
In this PR we update the docs to include this dependency.
- Other
*Please describe the tests that you ran to …
> Update e2e README.md

- api/v1beta2/foundationdbcluster_types.go
- config/crd/bases/apps.foundationdb.org_foundationdbclusters.yaml
- controllers/update_status.go
- controllers/update_status_test.go
- docs/cluster_spec.md
Fixes: https://github.com/FoundationDB/fdb-kubernetes-operator/issues/1564
This is currently only used as an additional information source that can be used in addition to the information from the cluster status.
Unit tests.
Will be added before merging.
We could add the fault domain as a label to make the selection of Pods easier.
> Initial support for fault domains in CRD

- controllers/update_status.go
- controllers/update_status_test.go
Make "update_status" reconciler to also update maintenance mode information in cluster status.
- Other (re-organizes code; likely we will need to revisit the logic in the maintenance_mode reconciler)
As mentioned above, it is likely we will need to revisit the logic in the maintenance_mode reconciler.
CI will run the operator unit tests.
Yes, nightly operator regression tests.
No.
*If this change is adding new …
> Update maintenance mode information in the update_status controller

- api/v1beta2/foundationdb_labels.go
- controllers/cluster_controller.go
- controllers/cluster_controller_test.go
- controllers/update_metadata.go
- controllers/update_metadata_test.go
Fixes: https://github.com/FoundationDB/fdb-kubernetes-operator/issues/1653
This additional information in the annotation can be used by other systems that only fetches the metadata of the Pod resources.
Unit tests.
-
-
> Add the current running node for a Pod into the Pod annotations

- .github/workflows/pull_request.yml
- config/samples/pod_disruption_budget.yaml
- docs/manual/getting_started.md
Because `batch/v1beta1` and `policy/v1beta1` will be deprecated in K8s 1.25.
- Update PodDisruptionBudget apiVersion to policy/v1
- Update CronJob apiVersion to batch/v1
- Other
*Are there any design details that you would like to discuss further?* No
Manual testing?* 
*If this …
> Update CronJob and PodDisruptionBudget apiVersion for K8s 1.25 

- api/v1beta2/foundationdbcluster_types.go
- api/v1beta2/foundationdbcluster_types_test.go
- kubectl-fdb/cmd/analyze.go
- kubectl-fdb/cmd/analyze_test.go
- kubectl-fdb/cmd/cordon.go
- kubectl-fdb/cmd/cordon_test.go
- kubectl-fdb/cmd/remove_process_group.go
- kubectl-fdb/cmd/remove_process_group_test.go
- kubectl-fdb/cmd/suite_test.go
This PR adds two new methods that will return the process group IDs for removal operations. The new methods will be used by the kubectl plugin but could also be used by other clients to set the `cluster.Spec.ProcessGroupsToRemove` setting (or the same for `WithoutExclusion`). The methods will return all process group IDs that are not marked for removal and will filter out process groups that are not part of the `FoundationDBCluster` status process groups or are already marked for removal. This will make sure in the long term, that the list of process groups are eventually cleaned up.
-
Unit tests.
Added documentation for the methods.
-
> Add new method to get all process group IDs for removal

- api/v1beta2/foundationdb_status.go
- controllers/change_coordinators.go
- controllers/change_coordinators_test.go
- e2e/test_operator/operator_test.go
- fdbclient/admin_client.go
- internal/locality/locality.go
- pkg/fdbadminclient/mock/admin_client_mock.go
Extend the logic that selects/verifies the validity of current coordinators to take maintenance mode information into account.
Read maintenance mode information from special keyspace.
- Other (extends the existing functionality)
No.
Ran the test, locally, that has been added in this PR.
Yes (nightly regression tests will need to be run).
No.
Maybe (at a later point). …
> Take maintenance mode into account while choosing coordinators and read maintenance mode information from special key space

- e2e/test_operator/operator_test.go
- Get "maintenance mode is on" test to succeed and enable it.
- Bug fix (non-breaking change which fixes an issue); testing related
No.
Manual testing.
Yes, nightly regression testing.
N/A
N/A
N/A
*If this …
> Enable "maintenance mode is on" test in "operator_test.go"

- internal/replacements/replacements.go
This provides better insights into the spec changes for a replacement.
I decided to log the spec as base64 to prevent any json parsing issues.
Locally.
-
-
> Add better logging for spec hash changes

- e2e/test_operator_upgrades/operator_upgrades_test.go
- internal/pod_models.go
- internal/pod_models_test.go
The result of this bug was that the transaction system Pods were replaced more often than required e.g. twice instead of once.
-
Unit test and I will adjust an e2e test to check this behaviour.
-
-
> Make sure we update the sidecar images too for patch upgrades

- kubectl-fdb/cmd/k8s_client.go
- kubectl-fdb/cmd/k8s_client_test.go
- kubectl-fdb/cmd/restart.go
Fixes #1640 
- Unit tests added 
- Manual testing: 
```
$ kubectl-fdb restart -c fdb-cluster --context fdb-dev  --process-condition=MissingProcesses 
Skipping Process Group: test, because it does not have a corresponding Pod.
Skipping Process Group: test2, because it does not have a corresponding Pod.
Restart [] in cluster timeseries/foundationdb-cluster [y/n]: 
```
*Do we need to perform additional testing once this is merged, or perform in a larger testing environment?* No
*Did you update relevant documentation within this repository?* No …
> Fixes issue #1640

- controllers/update_status.go
- controllers/update_status_test.go
- e2e/test_operator/operator_test.go
This will be helpful to detect any issues with a flapping running version.
- Other
-
Unit tests.
-
-
> Add logging when the operator detects a new running version

- e2e/test_operator_ha_upgrades/operator_ha_upgrade_test.go
Enable HA upgrade tests on PRs.
- Other
HA upgrades have some other timing characteristic, so we should make sure new changes are not breaking any assumptions in a HA setup.
-
-
-
> Run HA upgrade tests on PRs

- e2e/test_operator/operator_test.go
We've seen a few failures where the e2e test framework was not able to connect to the operator Pod, e.g. because it was just killed by the Pod chaos. In order to make the tests more reliable we should retry the command(s).
-
Manual test.
-
-
> Make sure we retry the maintenance commands if they fail once

- controllers/change_coordinators.go
- controllers/cluster_controller.go
- controllers/update_status.go
- e2e/test_operator_ha_upgrades/operator_ha_upgrade_test.go
Make sure we propagate the fetched connection string only in one place and we check that the fetched connection string is not empty before assigning it.
-
Manuel e2e test run.
-
-
> Make sure we set the connection string if the status is cached

- kubectl-fdb/cmd/analyze.go
Fixes: https://github.com/FoundationDB/fdb-kubernetes-operator/issues/1693
Thanks @masih  for reporting
-
Did a local test with the fix:
```bash
$ ./dist/kubectl-fdb_darwin_arm64/kubectl-fdb analyze tabaluga
Error:
could not fetch cluster information for: default/tabaluga, error: foundationdbclusters.apps.foundationdb.org "tabaluga" not found
```
-
-
> Fix panic in analyze command if cluster is not found

- api/v1beta2/foundationdbcluster_types.go
- controllers/update_status.go
- e2e/test_operator_upgrades/operator_upgrades_test.go
Added some more description in the test case. TLDR: the test case was not working properly for version compatible upgrades as the Pod was recreated by the operator and then the network partition was lost (as chaos-mesh is not re-injecting chaos).
-
Manual run with a version compatible upgrade.
Added in code.
-
> Fix test case for version compatible upgrades

- e2e/Makefile
- e2e/fixtures/factory.go
- e2e/fixtures/options.go
This allows us to re-use existing clusters and can greatly fasten the testing time.
- Other
*Did …
> Add prefix factory option

- fdbclient/admin_client.go
Otherwise the operator might issues multiple kill commands which can lead to multiple recoveries.
-
Unit tests and an e2e test run will be started.
-
-
> Run kill command once without back off to reduce risk of multiple recoveries

- e2e/test_operator_upgrades/operator_upgrades_test.go
Wait for 5 minutes before failing if the incompatible connections are not 0. This makes sure we give the FDB cluster some time to clean up the incompatible connections as this information is cached for some time.
-
Manual run.
-
-
> Make sure we wait some time before checking the incompatible connections

- e2e/fixtures/kubernetes_fixtures.go
Fixes the way how we validate the username. Before an invalid username was resulting in an empty namespace.
-
Local tests with invalid names.
-
-
> Correct the way how the e2e test framework checks the username

- e2e/fixtures/factory.go
- e2e/fixtures/fdb_cluster_specs.go
Exposing those methods will be helpful for some special use cases where a modified version of the cluster spec will be used to create a cluster.
-
unit test + e2e tests.
-
-
> Expose methods to create a cluster based on the generated spec

- api/v1beta2/foundationdbcluster_types.go
- controllers/check_client_compatibility.go
- docs/cluster_spec.md
- docs/manual/operations.md
Fixes: https://github.com/FoundationDB/fdb-kubernetes-operator/issues/1468 and documents the behaviour.
-
Manual test run
Added.
-
> Document upgrades for 7.1+ and add the default log group to the ignore list

- fdbclient/admin_client.go
- pkg/fdbadminclient/admin_client.go
- pkg/fdbadminclient/mock/admin_client_mock.go
Fixes: https://github.com/FoundationDB/fdb-kubernetes-operator/issues/1710
-
Manual e2e test run:
```text
fdb-kubernetes-operator-controller-manager-7695576797-vk9vr manager {"level":"info","ts":"2023-06-28T12:17:11Z","logger":"fdbclient","msg":"Done fetching values from FDB","namespace":"jscheuermann-ove3b2kz","cluster":"fdb-cluster-ho1fvswm","testing":"12345","key":"\ufffd/coordinators"}
```
-
-
> Allow to set additional fields for the admin client logger

- mock-kubernetes-client/client/client.go
Otherwise the scheme is not properly set.
-
Unit tests.
-
-
> Make sure the fake client is created with the correct scheme

- api/v1beta2/foundationdbcluster_types.go
- controllers/replace_failed_process_groups.go
- controllers/replace_failed_process_groups_test.go
- internal/replacements/replace_failed_process_groups.go
Modify operator replacement logic to ignore process groups that are in maintenance mode.
Manual testing.
> Replacement logic should ignore process groups that are in maintenance mode

- controllers/cluster_controller.go
- docs/manual/replacements_and_deletions.md
- setup/setup.go
Fixes: https://github.com/FoundationDB/fdb-kubernetes-operator/issues/1727
-
Unit tests.
Updated.
-
> Disable node access per default in the operator

- e2e/test_operator_ha_upgrades/operator_ha_upgrade_test.go
Add an explanation for the number of recoveries that happen during an upgrade.
Resolves issue: https://github.com/FoundationDB/fdb-kubernetes-operator/issues/1607
- Other
No.
None.
No.
Yes (updated a test related comment)
N/A
*If this change is adding or removing subreconcilers, have we updated the core technical design doc to …
> Explanation for the number of recoveries that happen during an upgrade

- api/v1beta1/foundationdbcluster_types.go
- api/v1beta1/zz_generated.deepcopy.go
- config/crd/bases/apps.foundationdb.org_foundationdbclusters.yaml
Remove this setting from the v1beta1 API as the setting has no affect here.
Clean up from the previous log server PR.
N/A
-
-
> Remove logServersPerDisk from v1beta1 API

- controllers/cluster_controller.go
When providing label selector for operator I expect to have following behaviour:
1. Adding label that match label selector to existing foundationdbcluster should reconcile cluster
2. Removing label that match label selector to foundationdbcluster should reconcile cluster
Right now I have following scenario which do not match this expectation:
1. Running fdbcluster with label that matches label selector of operator
2. Remove label above from fdbcluster
3. Remove bunch of pods from fdbcluster
4. Add label back
5. It's not reconcile (I expect this to be reconciled)
It happens due to fdb operator filtering events when such thing happens, so the cluster will stay drifted from expected state and operator won't do reconcilation.
No
Built and …
> Add label watch perdicate

- api/v1beta2/foundationdbcluster_types.go
- api/v1beta2/foundationdbcluster_types_test.go
- controllers/remove_process_groups_test.go
Before the `GetRemovalMode` was returning the wrong value.
Fixes: https://github.com/FoundationDB/fdb-kubernetes-operator/issues/1750
-
Added unit tests for the method.
-
-
> Fix get removal mode

- controllers/cluster_controller.go
- controllers/remove_process_groups.go
- controllers/remove_process_groups_test.go
This change removes the need for fetching the FoundationDB machine-readable status again to get the set of coordinators.
- Other
There is no need to issue the get status command again only to fetch the coordinator set.
Changed the unit test and e2e tests will be running.
-
-
> Remove the additional get status call for getting the coordinator set

- controllers/cluster_controller.go
- controllers/remove_process_groups.go
- controllers/remove_process_groups_test.go
- controllers/update_status.go
- fdbclient/admin_client_test.go
- pkg/fdbstatus/status_checks.go
- pkg/fdbstatus/status_checks_test.go
We want to make sure that the database is available if we do any checks for the exclusion status based on the machine-readable status. If the database is unavailable we could hit a case were processes are reported but not the roles for them. In this case it will be better to wait until the database is available again.
I decided to return all processes as "not excluded" to prevent the operator doing any additional checks with the exclude command, as the exclude command could make the unavailable database state even worse.
Unit tests.
-
-
> Check if the database is available before doing any exclusion checks

- fdbclient/admin_client_test.go
- internal/removals/remove.go
- pkg/fdbstatus/status_checks.go
Verify the processes that are assumed to be excluded by the machine-readable status are also excluded based on the exclude command
This change will make sure we have a second safety net for processes that might be missing the roles sporadic in the amchine-readable status.
Unit tests. I will see if there is a good way to reproduce a process without any roles but not excluded.
-
-
> Verify the processes that are excluded 

- e2e/Makefile
- e2e/fixtures/factory.go
- e2e/fixtures/options.go
Allow to reduce the verbosity of the operator test framework.
- Other
-
Local e2e test run and it didn't printout the dump statements.
Added in the Makefile.
-
> Allow to reduce debugging information in operator test framework

- docs/manual/replacements_and_deletions.md
- e2e/fixtures/cluster_config.go
- e2e/fixtures/factory.go
- e2e/fixtures/fdb_cluster_specs.go
- e2e/fixtures/fdb_operator_fixtures.go
- e2e/fixtures/ha_fdb_cluster.go
- e2e/test_operator_upgrades/operator_upgrades_test.go
Fixes: https://github.com/FoundationDB/fdb-kubernetes-operator/issues/1648
Fixes: https://github.com/FoundationDB/fdb-kubernetes-operator/issues/1648
- Other
-
Added a minimal upgrade test with the maintenance mode enabled.
Added documentation on how to use it and the current limitations.
We have a few radars around the maintenance mode.
> Document the maintenance mode feature

- Makefile
- config/crd/bases/apps.foundationdb.org_foundationdbbackups.yaml
- config/crd/bases/apps.foundationdb.org_foundationdbclusters.yaml
- config/crd/bases/apps.foundationdb.org_foundationdbrestores.yaml
- config/rbac/role.yaml
- config/samples/deployment.yaml
Update the controller-gen tool: https://github.com/kubernetes-sigs/controller-tools/releases/tag/v0.12.0.
- Other
-
Local testing.
-
-
> Update controller gen

- api/v1beta2/foundationdb_process_class.go
- api/v1beta2/foundationdbcluster_types.go
- controllers/add_process_groups.go
- controllers/add_process_groups_test.go
- controllers/add_services.go
- e2e/fixtures/factory.go
- e2e/fixtures/fdb_cluster.go
- e2e/fixtures/fdb_operator_client.go
- e2e/fixtures/test_runner.go
- e2e/test_operator/operator_test.go
- internal/pod_models.go
- internal/replacements/replacements.go
- internal/replacements/replacements_test.go
Fixes: https://github.com/FoundationDB/fdb-kubernetes-operator/issues/1764 (by adding an e2e test and verify this behaviour).
Fixes: https://github.com/FoundationDB/fdb-kubernetes-operator/issues/1748
- Other
I refactored the way how the new ProcessGroupID is generated to make it usable by the e2e tests.
Added a new e2e test and ran it manually.
-
-
> Add e2e test to make sure operator can handle Pods that are stuck in pending

- .goreleaser.yaml
- Makefile
attempt to fix release failing to build `macos` and `windows` `arm64` artifacts
> update goreleaser version, and remove invalid config

- api/v1beta2/foundationdbcluster_types.go
- controllers/add_services.go
- controllers/add_services_test.go
- internal/pod_models.go
- internal/pod_models_test.go
- internal/service_helper.go
Updated the service spec to include IPFamilies for IPv6. Also updated the sidecar args. 
No
Added unit tests
Added / updated unit tests.
*If this change is …
> updating ipv6 support in sidecar and service

- api/v1beta2/foundationdbcluster_types.go
- config/crd/bases/apps.foundationdb.org_foundationdbclusters.yaml
- e2e/test_operator/operator_test.go
Fixes: https://github.com/FoundationDB/fdb-kubernetes-operator/issues/1777
-
I added an e2e test and ran it manually. We have to add a better test, as the FDB cluster will be broken after the test.
-
-
> Fix CRD validation for Process Group ID and allow wildcard

- Dockerfile
- e2e/Makefile
- e2e/scripts/setup_e2e.sh
Update the default e2e test versions to 7.1 and 7.3.
- Other
-
e2e test with the new versions will be triggered.
-
-
> Update the default e2e FDB versions

- .golangci.yml
Fixes #1739 
This PR updates golangcli-lint `depgard` configuration to allow the packages currently used by the operator.
- Bug fix 
*Are there any design details that you would like to discuss further? No
Manual testing? <<<
```
$ make lint
/home/manufog/go/bin/golangci-lint run ./...
```
*Do we need to perform additional testing once this is merged, or perform in a larger testing environment? No
*Did you update relevant documentation within this repository? No
*If this change is adding new functionality, do we need to describe it in our user manual? No
*If this change is adding or removing subreconcilers, have we updated the core technical design doc to reflect that? N/A
*If this change is adding new safety …
> Fix Issue #1739

- docs/design/suspending_pods.md
This design will allow the operator to suspend a Process Group (only delete the Pod) before deleting all resources.
Fixes: https://github.com/FoundationDB/fdb-kubernetes-operator/issues/1756
- Other
-
-
-
Implementation
> Initial design doc for suspending Process Groups

- e2e/test_operator_upgrades/operator_upgrades_test.go
Increase the timeout for the default single cluster upgrade. This should make sure that the operator has enough time to replace any process that might not be coming up correctly.
- Other
-
I ran those test manually.
-
-
> Increase timeout for default single cluster upgrade

- controllers/remove_process_groups_test.go
- controllers/replace_failed_process_groups_test.go
- pkg/fdbstatus/status_checks.go
- pkg/fdbstatus/status_checks_test.go
Fixes: https://github.com/FoundationDB/fdb-kubernetes-operator/issues/1340. We require in all regions full replication before proceeding, this is a very strict requirement that could be improved in a follow up PR.
-
Unit tests + CI will be running e2e tests.
I will update the docs with the fault tolerance metrics.
.
> Make use of the new fault tolerance methods

- controllers/update_status.go
- controllers/update_status_test.go
Fixes: https://github.com/FoundationDB/fdb-kubernetes-operator/issues/1793 otherwise the process groups might get the `MissingProcesses` condition assigned if the machine-readable status is missing all processes.
Unit tests and e2e tests will be running by CI.
-
We can add more dedicated checks for specific messages in the machine-readable status.
> Only set the MissingProcesses condition if the machine-readable status contains at least one process

- controllers/bounce_processes.go
- controllers/cluster_controller.go
- controllers/update_status.go
- fdbclient/lock_client.go
- pkg/fdbadminclient/lock_client.go
- pkg/fdbadminclient/mock/lock_client.go
Otherwise we have wait until the current lock expires. The default lock duration is 10 minutes, so waiting until the lock expires will slow down operations for HA clusters.
Ran the unit tests (but they are not yet traversing the code path) and ran some e2e tests.
I will try to see if we can add some additional unit tests for this.
Will be updated once the changes look good (to make sure we document the right approach).
-
> Improve operator lock handling by releasing locks once cluster is reconciled

- e2e/fixtures/cluster_config.go
- e2e/fixtures/kubernetes_fixtures.go
Before this change the prefix for the namespaces of an HA cluster were different and the e2e test suite would always create an empty namespace running the operator deployment. With this change the prefix for HA cluster namespaces will be constant and only create the single namespace per default for non HA clusters.
-
Ran the e2e tests.
-
-
> Correct the namespace creation for e2e tests

- controllers/cluster_controller.go
- fdbclient/admin_client.go
- fdbclient/admin_client_test.go
- fdbclient/common.go
- setup/setup.go
Instead of retrying to fetch the status with multiple different timeouts, we should fetch the status directly with the maximum timeout. This reduced the amount of retries if the cluster is not responsive. I create a follow up for a better retry mechanism.
-
e2e tests will be running.
-
-
> Allow to use max timeout for get status and allow to specify the max timeout

- e2e/fixtures/fdb_cluster.go
- e2e/test_operator_upgrades/operator_upgrades_test.go
- e2e/test_operator_upgrades_variations/operator_upgrades__variations_test.go
- e2e/test_operator_upgrades_variations/suite_test.go
With some of the recent changes we saw that the upgrade tests are timing out. The approach here is to split the upgrade tests into configuration tests and robustness/reliability tests.
- Other
-
e2e tests will be running in CI.
Updated in code.
-
> Split upgrade tests as we hit the timeout for our CI pipeline

- charts/fdb-operator/Chart.yaml
- charts/fdb-operator/values.yaml
- config/deployment/manager.yaml
- config/samples/deployment.yaml
- docs/changelog/v1.25.0.md
> prepare release v1.25.0

- api/v1beta2/foundationdbcluster_types.go
- e2e/fixtures/chaos_common.go
- e2e/fixtures/factory.go
- e2e/fixtures/fdb_cluster.go
- e2e/fixtures/ha_fdb_cluster.go
- e2e/test_operator/operator_test.go
- e2e/test_operator_ha_flaky_upgrades/operator_ha_flaky_upgrade_test.go
- e2e/test_operator_ha_upgrades/operator_ha_upgrade_test.go
- go.mod
- go.sum
Make use of [errgroup ](https://pkg.go.dev/golang.org/x/sync/errgroup) inlaces where we implemented that by ourself. This reduces some complexity in our testing code.
- Other (code clean up).
-
Ran local/manual tests.
-
-
> Make use of errgroup and simplify some testing code

- api/v1beta2/foundationdb_labels.go
- api/v1beta2/foundationdbcluster_types.go
- api/v1beta2/foundationdbcluster_types_test.go
- controllers/remove_process_groups.go
- e2e/fixtures/cluster_config.go
- e2e/fixtures/fdb_cluster_specs.go
- e2e/test_operator/operator_test.go
- e2e/test_operator_upgrades_variations/operator_upgrades_variations_test.go
- pkg/fdbstatus/status_checks.go
- pkg/fdbstatus/status_checks_test.go
Add first specific tests to for locality based exclusions. The locality based exclusion will be the default in the future, so we have to add more testing for it.
- Other
-
Manual run.
-
-
> Add first set of tests for locality based exclusions and fix bug in locality based exclusions

- controllers/add_pods.go
- controllers/add_pvcs.go
- controllers/add_services.go
- controllers/cluster_controller_test.go
- controllers/update_pods.go
- controllers/update_status.go
- e2e/fixtures/fdb_cluster.go
- e2e/test_operator/operator_test.go
- internal/monitor_conf_test.go
- internal/pod_client_test.go
- internal/pod_helper.go
- internal/pod_models.go
- internal/pod_models_test.go
- internal/replacements/replacements.go
- internal/replacements/replacements_test.go
- internal/test_helper.go
- pkg/podmanager/pod_lifecycle_manager.go
This is a follow up to refactor the operator code and remove some old technical debts, e.g. there is no need to parse the process class and id number multiple times, we just can pass down the whole process group.
- Other
Most of the changes are adjustments for the test cases.
Ran unit tests and e2e tests will be running with CI.
-
-
> Refactor code to make use of the process group directly without passing the class and id number down

- controllers/change_coordinators.go
- e2e/test_operator/operator_test.go
Fixes: https://github.com/FoundationDB/fdb-kubernetes-operator/issues/1254
-
Ran the new e2e test manually.
-
-
> Add e2e test for changing a cluster to use DNS in cluster files

- controllers/admin_client_test.go
- controllers/cluster_controller_test.go
- controllers/exclude_processes.go
- controllers/exclude_processes_test.go
- controllers/update_metadata_test.go
- docs/manual/replacements_and_deletions.md
- docs/manual/technical_design.md
- e2e/test_operator_migrations/operator_migration_test.go
- e2e/test_operator_migrations/suite_test.go
Fixes: https://github.com/FoundationDB/fdb-kubernetes-operator/issues/1639
Fixes: https://github.com/FoundationDB/fdb-kubernetes-operator/issues/1225
- Non breaking change.
-
Created a new migration test for this and updated the existing unit tests:
```text
Ran 1 of 1 Specs in 1373.773 seconds
SUCCESS! -- 1 Passed | 0 Failed | 0 Pending | 0 Skipped
--- PASS: TestOperatorMigrations (1373.84s)
PASS
ok      github.com/FoundationDB/fdb-kubernetes-operator/e2e/test_operator_migrations    1374.187s
```
Updated the exclusion logic.
-
> Handle large exclusions better

- e2e/fixtures/fdb_cluster.go
- e2e/test_operator/operator_test.go
- e2e/test_operator_migrations/operator_migration_test.go
- e2e/test_operator_upgrades_variations/operator_upgrades_variations_test.go
- e2e/test_operator_velocity/operator_velocity_test.go
Make sure the test setup is correct and the tests are stable.
-
CI will run the e2e tests.
N/A
-
> Improve test stability

- api/v1beta2/foundationdbcluster_types.go
- controllers/replace_failed_process_groups_test.go
- controllers/update_status.go
- controllers/update_status_test.go
- docs/manual/replacements_and_deletions.md
- e2e/test_operator/operator_test.go
Fixes: https://github.com/FoundationDB/fdb-kubernetes-operator/issues/1674
I added units tests and a new e2e test that I ran manually:
```text
Ran 1 of 40 Specs in 1070.055 seconds
SUCCESS! -- 1 Passed | 0 Failed | 9 Pending | 30 Skipped
PASS | FOCUSED
```
Updated.
N/A
> Let operator replace processes that are excluded but not yet marked as removed

- api/v1beta2/foundationdb_process_address.go
- controllers/cluster_controller_test.go
- controllers/remove_process_groups_test.go
- pkg/fdbadminclient/mock/admin_client_mock.go
- pkg/fdbstatus/status_checks.go
- pkg/fdbstatus/status_checks_test.go
Adding a fault tolerance check for coordinators and only allow operations if all coordinators are up and running. In a fallow up we could use those fault tolerances and only validate them for affected Pods, e.g. only validate the coordinator fault tolerance for coordinator changes.
Currently the requirement is that all coordinators are up and running. This is the most strict policy.
I added new unit tests. Some of the existing tests are broken and they need some modification (or the mock setup).
-
-
> Add coordinator fault tolerance check

- e2e/fixtures/factory.go
- e2e/fixtures/fdb_cluster.go
- e2e/fixtures/fdb_data_loader.go
- e2e/fixtures/fixtures.go
- e2e/fixtures/options.go
- e2e/fixtures/singleton.go
- e2e/fixtures/status.go
- e2e/test_operator/operator_test.go
- e2e/test_operator_ha_upgrades/operator_ha_upgrade_test.go
- e2e/test_operator_upgrades/operator_upgrades_test.go
- e2e/test_operator_upgrades_variations/operator_upgrades_variations_test.go
- sample-apps/data-loader/Dockerfile
Fixes: https://github.com/FoundationDB/fdb-kubernetes-operator/issues/1760
-
e2e tests.
Will be updated.
-
> Add DataLoader to make sure cluster has minimal data

- api/v1beta2/foundationdb_version.go
- api/v1beta2/foundationdb_version_test.go
- api/v1beta2/foundationdbcluster_types.go
- api/v1beta2/foundationdbcluster_types_test.go
- controllers/check_client_compatibility.go
- controllers/cluster_controller.go
- controllers/exclude_processes_test.go
- e2e/fixtures/upgrade_test_configuration.go
- fdbclient/admin_client.go
Allow to use downgrade versions in the upgrade tests. This is a preparation for: https://github.com/FoundationDB/fdb-kubernetes-operator/issues/1712
-
Ran a manual test.
-
-
> Allow e2e test suite to specify downgrade versions

- api/v1beta2/foundationdbcluster_types.go
- api/v1beta2/foundationdbcluster_types_test.go
- internal/replacements/replace_failed_process_groups.go
- kubectl-fdb/cmd/analyze.go
- kubectl-fdb/cmd/remove_process_group.go
This change adds additional information to the replacement logic for failed process groups. Historically we only replaced processes based on one condition, but now in the current implementation we have multiple reasons that could lead to an automatic replacement. Adding this information to the logging output, makes it easier to understand why the operator started the replacement.
- Other (improve logging)
-
Updated unit tests + CI will run e2e tests.
-
-
> Add failure condition to logging in automatic replacements

- api/v1beta2/foundationdb_database_configuration.go
- api/v1beta2/foundationdb_database_configuration_test.go
- api/v1beta2/foundationdb_labels.go
- api/v1beta2/foundationdbcluster_types.go
- config/crd/bases/apps.foundationdb.org_foundationdbclusters.yaml
- config/tests/three_data_hall/Readme.md
- config/tests/three_data_hall/create.bash
- config/tests/three_data_hall/delete.bash
- config/tests/three_data_hall/final.yaml
- config/tests/three_data_hall/functions.bash
- config/tests/three_data_hall/stage_1.yaml
- controllers/change_coordinators.go
- controllers/change_coordinators_test.go
- controllers/suite_test.go
- docs/manual/fault_domains.md
- internal/locality/locality.go
- internal/locality/locality_test.go
- internal/monitor_conf.go
Fixes: https://github.com/FoundationDB/fdb-kubernetes-operator/issues/348
When running a FoundationDB cluster on public cloud providers it can be useful to use three data hall as redundancy more and spread Pods across multiple availability zones. So far the operator was not supporting this mode. Now the operator supports this mode with minimal code changes, the drawback is, that a user has to create 3 `FoundationDBCluster` resources.
I did some manual testing:
```bash
$ kubectl get fdb,po 
NAME                                                                GENERATION   RECONCILED   AVAILABLE   FULLREPLICATION   VERSION   AGE
foundationdbcluster.apps.foundationdb.org/test-cluster-us-west-2 …
```
> Initial support for three data hall replication

- api/v1beta2/foundationdbcluster_types.go
- controllers/add_pods.go
- controllers/add_pvcs.go
- controllers/add_pvcs_test.go
- controllers/add_services.go
- controllers/add_services_test.go
Otherwise the operator might get in a deadlock where it doesn't create the PVC and therefore the Pod is stuck in pending forever. Since the Pod might have never received an IP address, the operator is currently not allowed/able to remove the process group. This issue can happen when migrations are triggered in a rapid manner or resource limitations are hit.
-
Updated the unit tests to handle the new behaviour.
N/A
-
> Make sure that the PVC and service gets created if a process group gets quickly marked as removal

- e2e/fixtures/cluster_config_test.go
- e2e/fixtures/fdb_cluster.go
- e2e/fixtures/fdb_cluster_test.go
- e2e/fixtures/fdb_data_loader.go
- e2e/test_operator/operator_test.go
- e2e/test_operator_migrations/operator_migration_test.go
Fixes: https://github.com/FoundationDB/fdb-kubernetes-operator/issues/1835
The flakiness was in the test, depending on the test behaviour there was a race condition in the Eventually statement.
Ran the e2e test manually.
-
-
> Fix flaky migration test setup

- controllers/remove_process_groups.go
- controllers/remove_process_groups_test.go
- controllers/update_status.go
- internal/removals/remove.go
- internal/removals/remove_test.go
Using the get method is more efficient than doing a List, especially if the operator is managing a large amount of resources.
Once https://github.com/FoundationDB/fdb-kubernetes-operator/issues/1638 is fixed we are rid of all List command except the once in `update_status`, but those are intended to catch resources that are missing in the status.
Ran unit tests, CI will run e2e test.
-
- https://github.com/FoundationDB/fdb-kubernetes-operator/issues/1638
> Remove the list call in the remove process groups reconciler and use the get method instead.

- go.mod
- go.sum
Update 6.2 reference to https://github.com/apple/foundationdb/pull/11004, this allows to compile the operator locally again.
-
Ran `make fmt lint test`
N/A
-
> Update fdb go bindings to allow copile on MacOS

- api/v1beta2/foundationdb_database_configuration.go
- api/v1beta2/foundationdbcluster_types.go
- api/v1beta2/foundationdbcluster_types_test.go
- controllers/add_process_groups.go
- controllers/update_database_configuration.go
- controllers/update_status.go
Refactoring of the get configuration string to make use of the string builder and directly iterate over the map.
- Other
-
Ran unit tests and CI will run e2e tests.
-
-
> Make use of string builder for getting the configuration string

- controllers/exclude_processes.go
- controllers/exclude_processes_test.go
- e2e/fixtures/chaos_common.go
- e2e/fixtures/fdb_cluster.go
- e2e/test_operator/operator_test.go
This PR contains a bug fix in the operator logic, if multiple pods are failing and the automatic replacements are not allowed to replace all pods at once.
-
Added unit and e2e tests.
-
-
> Make sure the operator can proceed with exclusions even if multiple pods are failing

- api/v1beta2/foundationdb_database_configuration.go
- controllers/remove_process_groups_test.go
The operator should be allowed to remove processes when a cluster running with `three_data_hall` redundancy is healthy and have minimum _three_ replicas of storage data (not _four_).
Fixes https://github.com/FoundationDB/fdb-kubernetes-operator/issues/1861
- Unit tests which checks if removals happen based on MinReplicasRemaining in the team tracker status.
- Manually verified removal of processes in a running `three_data_hall` cluster.
> Three data hall fault domain storage check bug fix

- controllers/update_pod_config.go
- controllers/update_pod_config_test.go
Ignore Pods in the Pod config update when the Pod is terminating. If the Pod is already in terminating state the containers will probably be shutdown anyway and this would only lead to a  wrong signal that the sidecar is unreachable.
- Other
-
Added unit tests.
-
-
> Ignore Pods in the Pod config update when the Pod is terminating

- api/v1beta2/foundationdb_database_configuration.go
- api/v1beta2/foundationdbcluster_types.go
- api/v1beta2/foundationdbcluster_types_test.go
- controllers/cluster_controller.go
- controllers/update_database_configuration.go
- controllers/update_status.go
- e2e/test_operator/operator_test.go
- fdbclient/admin_client.go
- fdbclient/common.go
- pkg/fdbadminclient/admin_client.go
- pkg/fdbadminclient/mock/admin_client_mock.go
- setup/setup.go
In https://github.com/FoundationDB/fdb-kubernetes-operator/pull/1863 we did some refactoring of the database configuration generation. This refactoring introduced a bug when `proxies` are specified in FDB versions 7.1+.
-
I added a dedicated e2e test to make sure the cluster is able to reconcile and has the targeted configuration.
-
Updated the documentation hoe the different proxy configuration interact.
> Fix database configuration bug if only proxies are specified

- e2e/test_operator/operator_test.go
- e2e/test_operator_upgrades_variations/operator_upgrades_variations_test.go
If a FDB versions doesn't support the locality based exclusions, we should just skip this check.
-
-
-
> Make sure the e2e test suite only runs locality based e2e tests if the provided versions support it

- mock-kubernetes-client/client/client.go
- mock-kubernetes-client/client/client_test.go
If a resource has a predefined creationTimestamp, make use of that creationTimestamp, to allow mocking resources that were created some time ago.
-
Added unit test.
-
-
> Allow to define creationTimestamp mock

- e2e/test_operator/operator_test.go
Fixes the failure in: https://github.com/FoundationDB/fdb-kubernetes-operator/pull/1873#issuecomment-1802442002 where the operator Pod was removed during the exclude command execution.
-
Manual run of this test case.
-
-
> Make sure the exclusion is tried again

- api/v1beta2/foundationdbcluster_types.go
- api/v1beta2/foundationdbcluster_types_test.go
- docs/manual/fault_domains.md
Enable locking by default when `RedundancyMode` is `three_data_hall`, such that certain operations are coordinated across `foundationdb` k8s resources. [See [Coordinating Global Operations](https://github.com/FoundationDB/fdb-kubernetes-operator/blob/main/docs/manual/fault_domains.md#coordinating-global-operations)]
Enabling locking addresses https://github.com/FoundationDB/fdb-kubernetes-operator/issues/1872.
Unit tests
Updated fault_domains.md
> Three data hall enable locking by default

- e2e/test_operator_ha_upgrades/operator_ha_upgrade_test.go
The test should not be executed if the provided version doesn't support it.
-
Ran the test manually
-
-
> Ignore HA locality-based exclusion test if version doesn't support locality based exclusions

- kubectl-fdb/cmd/analyze.go
- kubectl-fdb/cmd/buggify_crash_loop.go
- kubectl-fdb/cmd/buggify_empty_monitor_conf.go
- kubectl-fdb/cmd/buggify_no_schedule.go
- kubectl-fdb/cmd/configuration.go
- kubectl-fdb/cmd/cordon.go
- kubectl-fdb/cmd/deprecation.go
- kubectl-fdb/cmd/exclusion_status.go
- kubectl-fdb/cmd/exec.go
- kubectl-fdb/cmd/fix_coordinator_ips.go
- kubectl-fdb/cmd/k8s_client.go
- kubectl-fdb/cmd/remove_process_group.go
- kubectl-fdb/cmd/restart.go
- kubectl-fdb/cmd/version.go
Fixes: https://github.com/FoundationDB/fdb-kubernetes-operator/issues/1675
Fixes: https://github.com/FoundationDB/fdb-kubernetes-operator/issues/1496 (fetching the same cluster multiple times is not an issue as they will be read from the cache)
-
Ran some manual tests.
-
We should remove some of the logic in the plugin to make sure we make use of the get calls and remove any caches we put on top of the controller client.
> Add cache to plugin

- e2e/fixtures/fdb_operator_client.go
We have seen cases where it took longer than the expected 60 seconds for the Pods to get scheduled and into a running state, so this PR increases the threshold to 120 seconds and the overall wait time. I removed some duplication code in `RecreateOperatorPods`. 
- Other
-
CI will run tests.
-
-
> Update the way the operator deployment is created and verified

- e2e/fixtures/cluster_config.go
Enable 2 Storage Servers per disk as the default config in our e2e tests.
- Other
We will enable one e2e tests with 1 SS per disk.
CI will run e21e tests.
Will be updated.
Add dedicated test(s) for single SS per Pod.
> Enable 2 Storage Servers per default in test cases

- config/tests/unified_image/unified_image_role.yaml
- e2e/fixtures/kubernetes_fixtures.go
Otherwise the FDB kubernetes monitor is not able to list the Pod(s).
-
Did a manual run.
-
-
> Add the missing list verb to Pods for testing the unified image

- setup/setup.go
This change allows to modify the leader election settings for the controller runtime.
This gives some more flexibility in setting out the leader election mechanism in the operator.
CI tests will be running.
-
-
> Allow to modify the leader election timeouts

- e2e/fixtures/fdb_cluster.go
- e2e/test_operator_maintenance_mode/operator_maintenance_mode_test.go
- e2e/test_operator_maintenance_mode/suite_test.go
This PR adds two tests cases for testing the interaction with the maintenance mode. In the future we can extend those test cases.
- Other
-
Ran manually:
```
Ran 2 of 2 Specs in 930.483 seconds
SUCCESS! -- 2 Passed | 0 Failed | 0 Pending | 0 Skipped
--- PASS: TestOperatorHA (930.49s)
PASS
ok      github.com/FoundationDB/fdb-kubernetes-operator/e2e/test_operator_maintenance_mode      930.898s
```
-
-
> Add e2e test case for maintenance mode interaction

- kubectl-fdb/cmd/k8s_client.go
Fixes: https://github.com/FoundationDB/fdb-kubernetes-operator/issues/1916
-
Manually ran the command with a manual build:
```bash
$ ./dist/kubectl-fdb_darwin_arm64/kubectl-fdb -n dev  exec -c test-cluster --version-check=false -- bas
[fdb@test-cluster-storage-6 /]$ exit
exit
```
N/A
I checked for other fields we use and we should be covering all now.
> Add indexer to fix exec command

- fdbclient/command_runner.go
- fdbclient/command_runner_test.go
The fdb client has the option to set the environment variable `FDB_NETWORK_OPTION_CLIENT_THREADS_PER_VERSION` to make use of multiple threads, see: https://apple.github.io/foundationdb/api-general.html#multi-threaded-client. If this environment variable is set all `fdbcli` call will fail because of this variable. In order to fix this we have to exclude this variable when calling fdbcli. Setting this variable doesn't make any sense for fdbcli, as fdbcli can only connect to a single cluster anyway.
-
Ran a manual e2e test where I set `FDB_NETWORK_OPTION_CLIENT_THREADS_PER_VERSION`.
-
-
> Make sure we exclude the FDB_NETWORK_OPTION_CLIENT_THREADS_PER_VERSION env variable and don't pass it down to fdbcli

- setup/setup.go
Fixes: https://github.com/FoundationDB/fdb-kubernetes-operator/issues/985. This will reduce the cached resources to the once that matches the label selector if one is specified.
-
Unit tests + CI will run e2e tests. I will run some additional tests.
-
-
> Add cache client selector

- api/v1beta2/foundationdbcluster_types.go
- controllers/bounce_processes.go
- controllers/update_database_configuration.go
- controllers/update_status.go
Remove the update calls from the `BounceProcesses` reconciler and the `UpdateDatabaseConfiguration` reconciler. Those updates are done in the `UpdateStatus` reconciler already. This should reduce some conflicts and simplifies the code.
- Other (code cleanup).
There are other places that can be reviewed to try to update the `FoundationDBCluster` resource in a single place.
Ran unit tests and e2e tests are running with CI.
-
-
> Reduce the update calls for the FoundationDB resource

- kubectl-fdb/cmd/buggify_crash_loop_test.go
- kubectl-fdb/cmd/buggify_no_schedule.go
- kubectl-fdb/cmd/buggify_no_schedule_test.go
- kubectl-fdb/cmd/k8s_client_test.go
- kubectl-fdb/cmd/remove_process_group_test.go
- kubectl-fdb/cmd/suite_test.go
This PR sets `ProcessGroupIdPrefix` to the testing helper function `generateClusterStruct`, which makes it more correct for tests to refer to process group IDs with a <clustername> prefix, as they are doing right now.  This in turn makes test cases more consistent and easier to understand.
- Other: test bug fix?
Nope!
unit-test fix
PR only includes unit test changes, I tried to clarify comments and names as needed
N/A
> add ProcessGroupIdPrefix to testing generateClusterStruct and correct test cases

- fdbclient/admin_client.go
Having the mutex as it is will block the concurrency for the `GetStatus` method and limit it to be one request at a time.
I'm not sure about the historical reason why we added it, but that mutex shouldn't be required as the operator and users will probably create a new admin client any way. If we want to keep the mutex for ? reasons, we should be thinking about making that mutex cluster aware. But it's also interesting that only the `GetStatus` uses the mutex and no other method.
Ran unit tests and e2e tests will be running.
-
-
> Remove the global admin mutex for the admin client

- kubectl-fdb/cmd/analyze.go
- kubectl-fdb/cmd/cordon.go
- kubectl-fdb/cmd/cordon_test.go
- kubectl-fdb/cmd/k8s_client.go
- kubectl-fdb/cmd/remove_process_group.go
- kubectl-fdb/cmd/remove_process_group_test.go
- kubectl-fdb/cmd/suite_test.go
This addresses https://github.com/FoundationDB/fdb-kubernetes-operator/issues/1702
Let me know if the error raising is undesirable, also if a struct of common options for these commands might be helpful instead of the long list of parameters/options that includes many naked bools.
Unit tests are in the PR and I tested it on some actual pods
I do not believe so, no.
I don't think this is needed beyond the docstrings
*If this change is adding new functionality, do we need to describe it …
> Allow the remove sub command to remove by process class

- kubectl-fdb/cmd/analyze.go
- kubectl-fdb/cmd/cordon.go
- kubectl-fdb/cmd/cordon_test.go
- kubectl-fdb/cmd/k8s_client.go
- kubectl-fdb/cmd/remove_process_group.go
- kubectl-fdb/cmd/remove_process_group_test.go
This improves the verbosity of the cordon and remove process commands. It should address https://github.com/FoundationDB/fdb-kubernetes-operator/issues/1602 (if not exactly as described)
Example output for cordon (no wait):
```
Starting to cordon 2 nodes
Cordoning node: node-1
Cluster test/test2:
removed [test2-instance-1] (exclude: false)
Cluster test/test:
removed [test-instance-1] (exclude: false)
Cordoning node: node-2
Cluster test/test2:
removed [test2-instance-2] (exclude: false)
Cluster test/test:
removed [test-instance-2] (exclude: false)
Completed removal of 4 Pods
```
Example output for remove process-groups by cluster-label (with wait)
```
Remove [test-instance-1] from cluster test with exclude: true [y/n]: y
Cluster test:
removed [test-instance-1] (exclude: true)
Completed …
```
> Improve verbosity of cordon and remove process commands

- controllers/replace_failed_process_groups_test.go
- internal/replacements/replace_failed_process_groups.go
Fixes: https://github.com/FoundationDB/fdb-kubernetes-operator/issues/1890
-
Added an additional test and CI will run e2e tests.
-
-
> Don't skip the exclusion for process groups without an address when using localities

- kubectl-fdb/cmd/analyze.go
- kubectl-fdb/cmd/cordon.go
- kubectl-fdb/cmd/cordon_test.go
- kubectl-fdb/cmd/k8s_client.go
- kubectl-fdb/cmd/k8s_client_test.go
- kubectl-fdb/cmd/remove_process_group.go
- kubectl-fdb/cmd/remove_process_group_test.go
- kubectl-fdb/cmd/root.go
work towards https://github.com/FoundationDB/fdb-kubernetes-operator/issues/615 by creating a function which returns a map of processGroupIDs by FDB cluster based on process selection options.  
This PR only refactors removeProcessGroup's logic, but subsequent PRs will unify `buggify no-schedule`, `buggify crash-loop` and `restart` commands with the same selection function as well.  In order to meet feature-parity with `restart`, the selection function must have the ability to select by processGroup Condition, and thus will address https://github.com/FoundationDB/fdb-kubernetes-operator/issues/614 in a separate followup PR.
- Cleanup / Tech debt / New Feature
No
*Please …
> Create a unified process selection function and use it in removeProcessGroups

- api/v1beta2/foundationdbcluster_types.go
- kubectl-fdb/cmd/k8s_client.go
- kubectl-fdb/cmd/k8s_client_test.go
- kubectl-fdb/cmd/remove_process_group.go
- kubectl-fdb/cmd/remove_process_group_test.go
- kubectl-fdb/cmd/restart.go
- kubectl-fdb/cmd/root.go
- kubectl-fdb/cmd/suite_test.go
The common function is currently only used by remove-process-group.  This solves https://github.com/FoundationDB/fdb-kubernetes-operator/issues/614.
It also includes some refactoring of the error logic in the unified function -- I tried to make it as clear as possible for end users and it definitely assumes that this is on CLI use.  Definitely open to complaints!
This is work towards https://github.com/FoundationDB/fdb-kubernetes-operator/issues/615; the next PR will involve having all the process-group selection commands (`buggify no-schedule`, `buggify crash-loop`, and `restart`) use the common function now that it supports all the selection options with this PR.
*Please include a summary of the change and which issue is addressed. If this change resolves an issue, please include the …
> Add condition selection option to common processGroup selection function

- controllers/replace_failed_process_groups.go
- controllers/replace_failed_process_groups_test.go
- internal/replacements/replace_failed_process_groups.go
Let the operator requeue another reconcile attempt if more failed process groups are detected.
Otherwise the operator might not requeue and has to wait for another event to trigger a new reconciliation step.
Unit tests + CI will run e2e tests.
-
-
> Let the operator requeue another reconcile attempt if more failed process groups are detected

- kubectl-fdb/cmd/buggify_crash_loop.go
- kubectl-fdb/cmd/buggify_crash_loop_test.go
- kubectl-fdb/cmd/buggify_no_schedule.go
- kubectl-fdb/cmd/buggify_no_schedule_test.go
- kubectl-fdb/cmd/remove_process_group.go
- kubectl-fdb/cmd/restart.go
- kubectl-fdb/cmd/root.go
This PR should end up resolving https://github.com/FoundationDB/fdb-kubernetes-operator/issues/615 by having all the process-group selection commands (buggify no-schedule, buggify crash-loop, and restart) use the common function that remove-process-groups has come to use in previous PRs https://github.com/FoundationDB/fdb-kubernetes-operator/pull/1937 and https://github.com/FoundationDB/fdb-kubernetes-operator/pull/1940 
- Tech Debt / New feature (non-breaking change which adds functionality)
Not particularly
Unit tests, manually (but mostly spotchecked as there are so many possible combinations)
*Do we need to perform …
> use common process selection function in buggify crash-loop, buggify no-schedule, and restart commands

- kubectl-fdb/cmd/analyze_test.go
- kubectl-fdb/cmd/buggify_crash_loop_test.go
- kubectl-fdb/cmd/buggify_no_schedule_test.go
- kubectl-fdb/cmd/cordon_test.go
- kubectl-fdb/cmd/exec_test.go
- kubectl-fdb/cmd/fix_coordinator_ips_test.go
- kubectl-fdb/cmd/k8s_client.go
- kubectl-fdb/cmd/k8s_client_test.go
- kubectl-fdb/cmd/remove_process_group_test.go
- kubectl-fdb/cmd/restart.go
- kubectl-fdb/cmd/suite_test.go
This is just a followup to https://github.com/FoundationDB/fdb-kubernetes-operator/pull/1941 which used an unsatisfying way to get podNames from processGroupIDs.  
I am not sure that this is much better, but they do seem like useful functions in the transition away from selecting by processGroupID.  
**It will be much easier to see the changes if you view by commit to avoid looking at the second commit,** which changes test pod names to include processClass in the name, which is an expectation of built-in functions (GetPodName will index-out-of-bounds).
- Code Cleanup
I wonder if there should be some explicit creation function which does not allow FDB pods to have invalid names, as I suspect that it is not only GetPodName which could have undefined behavior if expectations aren't met. …
> add podName selection functions

- e2e/Makefile
- e2e/README.md
- e2e/fixtures/cluster_config.go
- e2e/fixtures/factory.go
- e2e/fixtures/fdb_operator_fixtures.go
- e2e/fixtures/options.go
- e2e/fixtures/status.go
Depending on the test case it would be useful to reuse a cluster, e.g. in cases where a test cluster gets loaded with some amount of data.
Ran a manual test:
```text
NAMESPACE=jdev CLUSTER_NAME=jdev  make -C e2e test_operator.run
```
With the following cluster and Pods created (the cluster is not available as the data loader is active):
```text
$ kubectl -n jdev get fdb,po 
NAME                                             GENERATION   RECONCILED   AVAILABLE   FULLREPLICATION   VERSION   AGE
foundationdbcluster.apps.foundationdb.org/jdev   1                                                       7.1.53    4m46s
NAME …
```
> Allow to specify a cluster name in test suite

- e2e/Makefile
- e2e/fixtures/cluster_config.go
- e2e/fixtures/factory.go
- e2e/fixtures/options.go
This change makes it easier to run e2e tests with different storage engines.
Most of the work was already done and I just had to extend the options to take the storage engine as a command line argument.
Ran a manual test:
```text
$ kubectl -n jscheuermann-9bn2uqhy    exec -ti fdb-cluster-8qrv6e98-stateless-1   -- bash
[root@fdb-cluster-8qrv6e98-stateless-1 /]# fdbcli
Using cluster file `/var/dynamic-conf/fdb.cluster'.
The database is available.
Welcome to the fdbcli. For help, type `help'.
fdb> status
Using cluster file `/var/dynamic-conf/fdb.cluster'.
Configuration:
Redundancy mode        - triple
Storage engine         - ssd-rocksdb-v1
Coordinators           - 5
Desired Commit Proxies …
```
> Allow to specify the storage engine when running e2e tests

- e2e/test_operator_ha_flaky_upgrades/operator_ha_flaky_upgrade_test.go
Once those tests are not flaky anymore we can more them to the right test suite and enable them again.
-
-
-
-
> Disable flaky test in nightly runs

- e2e/fixtures/factory.go
- e2e/fixtures/fdb_operator_fixtures.go
We observed the following issue in our nightly test cases:
```text
[PANICKED] Test Panicked
In [It] at: /usr/local/go/src/runtime/panic.go:260 @ 02/28/24 13:40:16.976
runtime error: invalid memory address or nil pointer dereference
Full Stack Trace
github.com/FoundationDB/fdb-kubernetes-operator/e2e/fixtures.(*HaFdbCluster).GetCluster(...)
/codebuild/output/src3955936553/src/github.com/FoundationDB/fdb-kubernetes-operator/e2e/fixtures/ha_fdb_cluster.go:95
github.com/FoundationDB/fdb-kubernetes-operator/e2e/fixtures.(*HaFdbCluster).GetPrimary(...)
/codebuild/output/src3955936553/src/github.com/FoundationDB/fdb-kubernetes-operator/e2e/fixtures/ha_fdb_cluster.go:54
github.com/FoundationDB/fdb-kubernetes-operator/e2e/fixtures.(*Factory).CreateFdbHaCluster(0xc000615218?, 0xf91e4ee5dfcf676b?, …
```
> Fix nil pointer ha e2e

- docs/manual/technical_design.md
This is a minor typo fix in the documentation (technical design).
> Minor typo fix in mention of localities

- api/v1beta2/foundationdb_version.go
- controllers/bounce_processes.go
- controllers/bounce_processes_test.go
- e2e/Makefile
- e2e/test_operator/operator_test.go
Updates the operator logic and e2e test case for this change in FDB: https://github.com/apple/foundationdb/pull/11149
-
Ran unit tests and CI will run the e2e tests.
-
-
> Fix the e2e test case for the new FDB version that supports to remove old tester processes automatically

- .gitignore
- Dockerfile
- docs/manual/operator_customization.md
Documents the limitations of the copy approach for the primary FDB lib, see: https://github.com/apple/foundationdb/issues/11222
Fixes: https://github.com/FoundationDB/fdb-kubernetes-operator/issues/1950
I also added `tini` to the operator image to allow the manager to generate coredumps, if the process is PID 1 it doesn't work.
-
Updated.
-
> Document issue with older fdb bindings and DNS support

- controllers/bounce_processes.go
We have seen a case in our nightly runs where one process was marked for removal but not yet fully excluded. I believe in such cases it's fine to have more addresses than the expected list, as it could take a while until a process is fully excluded,
-
Ran unit tests and CI will run e2e tests.
-
-
> Allow more addresses to be present in the upgrade bounce case

- README.md
- charts/fdb-operator/Chart.yaml
I updated the docs for the helm chart and tried to clarify that those are are contributed by the community and they are not automatically tested in our CI.
Fixes: https://github.com/FoundationDB/fdb-kubernetes-operator/issues/1788
-
-
Updated.
-
> Update the state of the helm charts

- controllers/update_pods.go
- controllers/update_pods_test.go
- e2e/test_operator/operator_test.go
- internal/replacements/replacements.go
- internal/replacements/replacements_test.go
Fixes bug where delete strategy is applied on pods not marked for removal in the replaceMisconfiguredProcessGroups step, https://github.com/FoundationDB/fdb-kubernetes-operator/issues/1918, by checking if the pod needs removal in the updatePods reconciler.
In addition to the ginkgo tests, also tested in a kubernetes deployment, verifying that update deletion strategy will not be applied if the update requires a removal / replacement.
> Update pods check needs removal

- api/v1beta2/foundationdbcluster_types.go
- api/v1beta2/zz_generated.deepcopy.go
- config/crd/bases/apps.foundationdb.org_foundationdbclusters.yaml
- controllers/bounce_processes.go
- controllers/change_coordinators.go
- controllers/cluster_controller.go
- controllers/maintenance_mode_checker.go
- controllers/maintenance_mode_checker_test.go
- controllers/suite_test.go
- controllers/update_database_configuration.go
- controllers/update_pods.go
- controllers/update_pods_test.go
- controllers/update_status.go
- controllers/update_status_test.go
- docs/cluster_spec.md
- docs/manual/operations.md
- docs/manual/replacements_and_deletions.md
- e2e/fixtures/fdb_cluster.go
- e2e/fixtures/status.go
- e2e/test_operator/operator_test.go
- e2e/test_operator_ha_upgrades/operator_ha_upgrade_test.go
- fdbclient/admin_client.go
- internal/maintenance/maintenance.go
- internal/maintenance/maintenance_test.go
- internal/maintenance/suite_test.go
- pkg/fdbadminclient/admin_client.go
- pkg/fdbadminclient/mock/admin_client_mock.go
- setup/setup.go
This PR provides changes for a better integration with the maintenance mode for the operator. I'll provide more information in the docs.
fixes: https://github.com/FoundationDB/fdb-kubernetes-operator/issues/1656
fixes: https://github.com/FoundationDB/fdb-kubernetes-operator/issues/1655
fixes: https://github.com/FoundationDB/fdb-kubernetes-operator/issues/1654
fixes: https://github.com/FoundationDB/fdb-kubernetes-operator/issues/1650
-
Manual testing. I added a new e2e test for this and added a new HA test with maintenance mode enabled. 
I will also add some additional unit tests to the once I already added.
Will be updated before merging.
-
> Initial changes for new maintenance mode integration

- controllers/cluster_controller.go
- controllers/exclude_processes.go
- controllers/remove_process_groups.go
- controllers/remove_process_groups_test.go
- docs/manual/technical_design.md
- e2e/fixtures/fdb_operator_client.go
- internal/removals/remove.go
- pkg/fdbadminclient/mock/admin_client_mock.go
- pkg/fdbstatus/status_checks.go
- pkg/fdbstatus/status_checks_test.go
- setup/setup.go
Improve the safety check around exclusions and add a safety check for inclusions. This should reduce the risk of repeated recoveries because of the operator.
-
Unit tests and the e2e test will be running by CI.
Will be updated.
-
> Add safety checks for inclusion and improve the exclusion check

- api/v1beta2/foundationdb_version.go
- api/v1beta2/foundationdb_version_test.go
- e2e/test_operator/operator_test.go
Correct version check for automatic tester process removal
-
Added unit tests.
-
-
> Correct version check for automatic tester process removal

- pkg/fdbstatus/status_checks.go
- pkg/fdbstatus/status_checks_test.go
The log line for the bounce check does not report the current uptime.
Is it okay to leave the imports change, or do you prefer me to undo that?
Pre-existing test has been updated.
No changes needed.
No follow-up needed.
> Report correct current uptime in log line for safe bounce check

- controllers/cluster_controller.go
- internal/configmap_helper.go
- internal/configmap_helper_test.go
- internal/monitor_conf.go
- internal/monitor_conf_test.go
Move regex compilation to the `init()` function of the module, freeing up an unused error return value.
- Other
It is a trivial change to make functions a bit nicer to use.
Pre-existing tests were updated.
Does not apply.
No follow-up needed.
> Remove an unnecessary error return value by compiling the regex

- kubectl-fdb/cmd/cordon.go
- kubectl-fdb/cmd/cordon_test.go
- kubectl-fdb/cmd/k8s_client.go
- kubectl-fdb/cmd/k8s_client_test.go
- kubectl-fdb/cmd/remove_process_group.go
- kubectl-fdb/cmd/restart.go
- kubectl-fdb/cmd/root.go
This PR adds the ability to select pods/processGroups by label selection.  This still requires a cluster name to be provided as I felt that would reduce the risk of accidental selection.
It also improves the error message of the `cordon` command for when no pods are found to be running on a node.
This solves https://github.com/FoundationDB/fdb-kubernetes-operator/issues/597
t
*If this change is adding or removing subreconcilers, have we updated the core technical …
> Label selection for pods/processGroups

- controllers/maintenance_mode_checker.go
- internal/maintenance/maintenance.go
Only log `Cluster in maintenance mode` if the maintenance zone is actually set. Allow the operator to remove processes that are restarted from the `underMaintenance` list, even if they are running in a different zone. For clusters using disaggregated storage this could happen.
-
Ran manual e2e tests.
-
-
> Correct log line for maintenance check and remove process if restarted in different zone

- e2e/test_operator_upgrades_variations/operator_upgrades_variations_test.go
Test case for: https://github.com/FoundationDB/fdb-kubernetes-operator/issues/1991 
- Other
Ran the e2e test manually.
-
-
> Add additional variation test with dedicated coordinators and service IP

- controllers/update_status.go
Changes to correct the logged fields and make sure we use a consistent set of fields in the logger.
I labeled this as a bug as some logged values used the wrong "format".
Ran unit tests and CI will run e2e tests.
-
-
> Small logging improvements and code restructure for the taint feature

- controllers/cluster_controller.go
- e2e/fixtures/fdb_operator_client.go
- internal/node_predicate.go
- setup/setup.go
Fixes: https://github.com/FoundationDB/fdb-kubernetes-operator/issues/1629
-
Ran some manual tests, I have to check how to test this in an e2e test or unit test.
Will be updated before marking this PR ready.
-
> Allow the operator to trigger a reconciliation if a node changes

- controllers/maintenance_mode_checker_test.go
- controllers/replace_failed_process_groups_test.go
- controllers/update_status.go
- controllers/update_status_test.go
We copied some things around that are pointers anyway, so we can stop copying things.
There are some other things we can do to improve the update status code and hopefully reduce the code complexity. I will create some radars with ideas later.
I ran and updated the unit tests. CI will run e2e tests.
-
-
> Improve some code paths in the update status code

- controllers/update_status.go
- docs/manual/replacements_and_deletions.md
Add additional log statements for the taint feature.
- Other
I updated the way how the timestamp of a taint is handled.
Run manually the e2e tests.
Removed the deprecated and unused `--enable-node-index` flag.
-
> Add additional log statements for taint feature

- Makefile
If the `container-build` target is used, we don't want to build everything, as the build container will take care of that.
This is a relict from the past when we didn't use the multi-stage build.
CI pipeline is running.
-
-
> Make sure that only the container is build

- e2e/fixtures/fdb_operator_fixtures.go
- e2e/fixtures/kubernetes_fixtures.go
Fixes: https://github.com/FoundationDB/fdb-kubernetes-operator/issues/2006
-
Ran a manual test:
```bash
$ kubectl get ns
NAME                             STATUS   AGE
jscheuermann-primary             Active   39s
jscheuermann-primary-satellite   Active   27s
jscheuermann-remote              Active   15s
jscheuermann-remote-satellite    Active   3s
```
-
-
> Make sure that the provided namespace will be used for HA tests

- .golangci.yml
- errcheck_excludes.txt
Fix warning of deprecated setting in golangci-lint
-
Ran  `make lint` locally:
```bash
$ make fmt lint
make: Nothing to be done for `fmt'.
/Users/jscheuermann/go/bin/golangci-lint run ./...
```
-
-
> Fix warning of deprecated setting in golangci-lint

- controllers/update_status.go
- controllers/update_status_test.go
- e2e/test_operator/operator_test.go
- e2e/test_operator_upgrades/operator_upgrades_test.go
If a process group is under maintenance we shouldn't update the conditions. it's expected that the process group related resources will be unavailable for some time.
- Other
-
Added a new e2e upgrade test and added an additional unit test.
-
-
> Make sure to skip process groups that are under maintenance

- controllers/remove_process_groups.go
Improving operator logging around pvc deletion from debug to info. 
- Other
no
N/A
N/A
N/A
> updating logging level from debug to info

- .github/workflows/pull_request.yml
Only run the trivy check for the operator image.
The previous configuration had issues which caused the actions to fail.
This PR.
-
-
> Run trivy only for the operator image

- api/v1beta2/foundationdbcluster_types.go
- api/v1beta2/foundationdbcluster_types_test.go
- controllers/change_coordinators.go
- controllers/change_coordinators_test.go
- controllers/choose_removals.go
- internal/locality/locality.go
- internal/locality/locality_test.go
Fixes: https://github.com/FoundationDB/fdb-kubernetes-operator/issues/2015
As mentioned in the referenced issue, during an upgrade it can happen that the operator chooses new coordinators for the Pod that is currently "updated" (deleted and created). In the previous setup the operator didn't differentiate between upgraded processes and processes to be upgraded. Choosing preferable upgraded processes as coordinators should reduce the overall recoveries caused by coordinator changes.
In addition we opted to prefer log/transaction processes as coordinators as those are not going though the rolling recreation phase but instead all are replaced. 
Updated unit tests and current e2e test should …
> Prefer upgraded processes for coordinators when the operator chooses the coordinators

- api/v1beta2/foundationdb_status.go
- controllers/check_client_compatibility.go
- controllers/check_client_compatibility_test.go
Fixes: https://github.com/FoundationDB/fdb-kubernetes-operator/issues/1991
We can ignore clients that share the same machine address as the FoundationDB processes. In most (if not all) cases that will be an `fdbcli` command that was manually ran to e.g. get the cluster status.
Updated the unit tests and CI will run e2e tests.
-
-
> Make sure we ignore clients that share the same machine address as a process from the FoundationDB cluster

- internal/pod_models.go
- internal/pod_models_test.go
Fix DNS setup for unified image and make sure env variable is set
-
Ran the DNS related e2e tests manually:
```text
Coordination servers:
jdev-log-10.jdev.jscheuermann.svc.cluster.local:4500:tls  (reachable)
jdev-log-6.jdev.jscheuermann.svc.cluster.local:4500:tls  (reachable)
jdev-log-7.jdev.jscheuermann.svc.cluster.local:4500:tls  (reachable)
jdev-log-8.jdev.jscheuermann.svc.cluster.local:4500:tls  (reachable)
jdev-log-9.jdev.jscheuermann.svc.cluster.local:4500:tls  (reachable)
Client time: 05/17/24 15:35:55
```
Test output:
```text
[AfterSuite]
/Users/jscheuermann/go/src/github.com/FoundationDB/fdb-kubernetes-operator/e2e/test_operator/operator_test.go:97 …
```
> Fix DNS setup for unified image and make sure env variable is set

- controllers/cluster_controller.go
- e2e/test_operator/operator_test.go
- internal/configmap_helper.go
- internal/configmap_helper_test.go
- internal/monitor_conf.go
- internal/monitor_conf_test.go
Fixes: https://github.com/FoundationDB/fdb-kubernetes-operator/issues/1032
-
Added a new test and ran it with the unified image.
-
-
> Add support for env variables in custom parameters for the unified image

- e2e/Makefile
- e2e/fixtures/factory.go
- e2e/fixtures/fdb_operator_client.go
- e2e/fixtures/options.go
Adding support to override the image tag for specific FDB versions. This can be useful if someone want to run the e2e test suite with a custom set of images.
-
Ran manually an upgrade test for the unified image.
Added in the makefile.
-
> Allow to override the image tag for specific versions

- api/v1beta2/foundationdbbackup_types.go
- api/v1beta2/foundationdbcluster_types.go
- api/v1beta2/zz_generated.deepcopy.go
- config/crd/bases/apps.foundationdb.org_foundationdbbackups.yaml
- config/crd/bases/apps.foundationdb.org_foundationdbclusters.yaml
- controllers/cluster_controller_test.go
- docs/backup_spec.md
- docs/cluster_spec.md
- docs/manual/customization.md
- e2e/fixtures/fdb_operator_fixtures.go
- e2e/test_operator/operator_test.go
- internal/configmap_helper_test.go
- internal/deprecations.go
- internal/deprecations_test.go
- internal/monitor_conf.go
- internal/monitor_conf_test.go
- internal/pod_client.go
- internal/pod_helper.go
- internal/pod_models.go
- internal/pod_models_test.go
Following the best practices from: https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#primitive-types
This is a breaking change but since the feature is currently not usable I think it's fine to change it anyways. We should make sure to announce it in the release notes but from my point of view the risk is minimal as we haven't released the unified image yet.
Unit tests.
-
-
> Change the useUnifiedImage setting to a more generic imageType

- e2e/fixtures/test_runner.go
This should help a bit when running all test suites at the "same time".
- Other
-
CI will be running the tests. I run a test locally by setting the environment variable manually:
```text
=== RUN   TestOperator
"level"=0 "msg"="waiting for" "1m51s"="before executing test suite"
Running Suite: Operator test suite - /Users/jscheuermann/go/src/github.com/FoundationDB/fdb-kubernetes-operator/e2e/test_operator
=================================================================================================================================
Random Seed: 1717434974
```
N/A
-
> Add wait time for CI runs to reduce congestion

- api/v1beta2/foundationdb_database_configuration.go
- controllers/change_coordinators.go
- controllers/change_coordinators_test.go
- controllers/generate_initial_cluster_file.go
- internal/locality/locality.go
- internal/locality/locality_test.go
- internal/test_helper.go
Fixes: https://github.com/FoundationDB/fdb-kubernetes-operator/issues/2034
Most of the code changes are adjustments for the testing code, to make sure we add some randomness.
Added additional unit tests and modified them.
-
-
> Prefer processes in coordinator selection for multi-region clusters

- controllers/update_pod_config.go
- e2e/Makefile
- e2e/fixtures/cluster_config.go
- e2e/fixtures/factory.go
- e2e/fixtures/fdb_cluster_specs.go
- e2e/fixtures/fdb_data_loader.go
- e2e/fixtures/fdb_operator_client.go
- e2e/fixtures/fdb_operator_fixtures.go
- e2e/fixtures/options.go
- e2e/test_operator/operator_test.go
- e2e/test_operator_migrate_image_type/operator_migate_image_type_test.go
- e2e/test_operator_migrate_image_type/suite_test.go
Adding e2e test cases for converting a cluster from split image to unified and from the unified to the split image.
- Other
I adjusted the e2e testing code to make sure we can test those migrations.
Manually tested:
```text
tail -f /Users/jscheuermann/go/src/github.com/FoundationDB/fdb-kubernetes-operator/e2e/../logs/test_operator_migrate_image_type.log
[ReportAfterSuite] PASSED [0.003 seconds]
Ran 2 of 2 Specs in 1011.427 seconds
SUCCESS! -- 2 Passed | 0 Failed | 0 Pending | 0 Skipped
--- PASS: TestOperator (1011.43s)
PASS
ok      github.com/FoundationDB/fdb-kubernetes-operator/e2e/test_operator_migrate_image_type …
```
> Add e2e migration test from split to unified image

- e2e/test_operator_upgrades/operator_upgrades_test.go
The test is disruptive by design, so doing an availability check is providing false signals.
As the test case is deleting pods outside of the operators scope, it's expected that this can cause disruptions, especially for those small clusters.
-
-
> Disable availability check for upgrade test

- api/v1beta2/foundationdb_env_variables.go
- api/v1beta2/foundationdbcluster_types.go
- controllers/cluster_controller.go
- controllers/update_sidecar_versions.go
- controllers/update_status.go
- internal/configmap_helper.go
- internal/configmap_helper_test.go
- internal/monitor_conf.go
- internal/monitor_conf_test.go
- internal/pod_client.go
- internal/pod_models.go
- internal/pod_models_test.go
- internal/replacements/replacements.go
- internal/replacements/replacements_test.go
Fixes: https://github.com/FoundationDB/fdb-kubernetes-operator/issues/2043
We changed the disk layout with the unified image, if only a single storage server per pod is used, then the data directory is still suffixed with `/1`. This would break the transition to the unified image for cluster with a single storage server per pod.
I also made sure we remove some internal method duplications.
Updated the unit tests and CI will run e2e tests.
-
-
> Unified image code clean up and make use of the same constant

- .github/workflows/pull_request.yml
- .github/workflows/release.yaml
- Dockerfile
- e2e/fixtures/fdb_data_loader.go
Update go version to 1.22.4 to include the latest security fixes: https://groups.google.com/g/golang-announce/c/XbxouI9gY7k
- Other
I also updated the RockyLinux version to the more recent 9.3.
-
-
> Update the go version to 1.22.4

- controllers/bounce_processes.go
- controllers/bounce_processes_test.go
- e2e/test_operator_upgrades/operator_upgrades_test.go
The previous calculation didn't account  properly for missing processes and processes that were marked for removal in the case of multiple servers per pod.
-
Updated the unit tests and ran a manual test.
-
-
> Fix the calculation of expected processes during upgrades for multiple servers per pod

- e2e/test_operator/operator_test.go
Corrects the test setup for the unified image when it's partitioned from the Kubernetes API.
-
Ran locally:
```text
• [183.633 seconds]
[AfterSuite]
/Users/jscheuermann/go/src/github.com/FoundationDB/fdb-kubernetes-operator/e2e/test_operator/operator_test.go:98
[ReportAfterSuite] PASSED [0.006 seconds]
Ran 1 of 52 Specs in 408.297 seconds
SUCCESS! -- 1 Passed | 0 Failed | 9 Pending | 42 Skipped
PASS | FOCUSED
FAIL    github.com/FoundationDB/fdb-kubernetes-operator/e2e/test_opera …
```
> Make sure we update the correct process class

- e2e/fixtures/factory.go
- e2e/fixtures/fdb_cluster.go
- e2e/fixtures/fdb_cluster_specs.go
- e2e/fixtures/fdb_data_loader.go
- e2e/fixtures/fdb_operator_client.go
- e2e/fixtures/fixtures.go
- e2e/test_operator_upgrades/operator_upgrades_test.go
- e2e/test_operator_upgrades_with_chaos/operator_upgrades_with_chaos_test.go
Some of the e2e upgrade tests with chaos had some assumption that were only true for the split image approach.
-
I ran those tests manually with the fix from https://github.com/FoundationDB/fdb-kubernetes-operator/pull/2056.
-
-
> Fix e2e upgrade tests with chaos for unified image

- controllers/cluster_controller.go
- controllers/maintenance_mode_checker.go
- controllers/replace_failed_process_groups.go
- controllers/replace_failed_process_groups_test.go
- controllers/update_database_configuration.go
- e2e/fixtures/fdb_cluster_specs.go
- pkg/fdbstatus/status_checks.go
If the cluster is not available we shouldn't perform automatic replacements as the operator is not able to make any good decision. The operator will not replace more than `MaxConcurrentReplacements` in the worst case, but I still think it's better to skip this feature at all if the cluster is unavailable.
-
-
-
> Make sure we skip the automatic replacements if the cluster is unavailable

- api/v1beta2/foundationdbcluster_types.go
- internal/monitor_conf.go
- internal/pod_models.go
- internal/pod_models_test.go
fixes https://github.com/FoundationDB/fdb-kubernetes-operator/issues/245
N/A
Unit tests, 
spun up e2e tests and checked that the logs are sent to the directory specified by the env variable, and that they all included the expected log group (cluster.spec.logGroup) incl. the logs from fdbcli
Don't think so, no
I don't think documentation change is needed, I think the issue is that there is nothing passively allowing logging to work and that this shouldn't be intrusive.  Do let me know if that sounds wrong!
N/A
> Set log dir and log group through environment variables for unified image

- api/v1beta2/foundationdb_env_variables.go
- api/v1beta2/foundationdb_labels.go
- controllers/cluster_controller_test.go
- controllers/update_metadata.go
- controllers/update_metadata_test.go
- e2e/test_operator_migrate_image_type/operator_migate_image_type_test.go
- internal/pod_client.go
- internal/pod_models.go
- internal/pod_models_test.go
- internal/replacements/replacements_test.go
It's probably better and more flexible to use an annotation instead of an env variable on the Pod.
-
I'm running the migration test suite manually (will update the result here).
-
-
> Change the image type from an env variable to an annotation

- internal/pod_models.go
- internal/pod_models_test.go
this helps avoid collisions in the case that a variable is declared in the cluster spec already (collisions will prevent Patch()s and prevent Operator from functioning normally)
- minor improvement
*If this change is adding new safety checks or new …
> use extendEnv instead of append to container.Env

- e2e/fixtures/fdb_cluster.go
- e2e/fixtures/kubernetes_fixtures.go
- e2e/test_operator/operator_test.go
- e2e/test_operator_ha/operator_ha_test.go
- e2e/test_operator_upgrades_with_chaos/operator_upgrades_with_chaos_test.go
The test is in pending mode as there is no way right now to recover the loss of the majority of coordinators. The idea for this test case is to have a repeatable way to test different recovery strategies.
- Other
-
Ran manually.
-
-
> Add a test case for a multi-region cluster where the majority of coordinators fail

- e2e/fixtures/status.go
- e2e/test_operator_upgrades/operator_upgrades_test.go
- internal/buggify/buggify.go
Return the actual command that failed. Also remove the `Eventually` statement as that one was flaky, there was a race condition where the test detected the process and then the operator updated that Pod with the new version, which would cause the test to fail (as the process would be missing and `MustPassRepeatedly(5)` was set).
- Other
-
Ran the tests manually.
-
-
> Add better error message when command failed and remove flaky check

- e2e/fixtures/chaos_common.go
- e2e/fixtures/factory.go
- e2e/fixtures/fdb_cluster.go
- e2e/fixtures/fdb_data_loader.go
- e2e/fixtures/fdb_operator_client.go
- e2e/fixtures/fdb_operator_fixtures.go
- e2e/fixtures/ha_fdb_cluster.go
- e2e/fixtures/kubernetes_fixtures.go
- e2e/fixtures/pods.go
- e2e/fixtures/singleton.go
- e2e/test_operator/operator_test.go
- e2e/test_operator_ha_upgrades/operator_ha_upgrade_test.go
- e2e/test_operator_maintenance_mode/operator_maintenance_mode_test.go
- e2e/test_operator_migrate_image_type/operator_migate_image_type_test.go
- e2e/test_operator_migrations/operator_migration_test.go
We have seen a few cases where the same namespace name is used when the e2e tests are running, so we should be waiting in the test setup until the namespace is deleted before using it. Waiting for it to be deleted will recreate the namespace and all required resources.
Some test  set a custom finalizer, this change checks for pods with a finalizer and resets them if one is set.
-
CI will be running.
-
-
> Make sure to wait until the namespace is completely deleted

- api/v1beta2/foundationdbcluster_types.go
- controllers/add_pods_test.go
- controllers/add_process_groups.go
- controllers/add_process_groups_test.go
- controllers/add_pvcs_test.go
- controllers/add_services_test.go
- controllers/admin_client_test.go
- controllers/bounce_processes_test.go
- controllers/change_coordinators_test.go
- controllers/choose_removals_test.go
- controllers/cluster_controller_test.go
- controllers/delete_pods_for_buggification_test.go
- controllers/exclude_processes_test.go
- controllers/maintenance_mode_checker_test.go
- controllers/remove_process_groups_test.go
- controllers/replace_failed_process_groups_test.go
- controllers/update_pod_config_test.go
- controllers/update_pods_test.go
- controllers/update_status_test.go
- docs/manual/resources.md
- e2e/fixtures/factory.go
- e2e/fixtures/fdb_cluster.go
- e2e/test_operator/operator_test.go
- e2e/test_operator_ha/operator_ha_test.go
- e2e/test_operator_upgrades_with_chaos/operator_upgrades_with_chaos_test.go
- internal/test_helper.go
Fixes: https://github.com/FoundationDB/fdb-kubernetes-operator/issues/2071. The issue was talking about another option, but I thought a bit more about it and using a randomized approach should be the best to prevent potential conflicts.
The PR is split in two commits: 1.) The actual code changes 2.) Test changes for all tests that assumed a deterministic setup.
As described in the issue, reusing the same process group ID, can be confusing in cases where a new process group is created with a process group ID that was just recently used.
Updated all unit tests and CI will run e2e tests.
I will screen the docs to see if we have to adjust them.
-
> Randomize process group ids

- e2e/Makefile
- e2e/fixtures/certificate_generator.go
- e2e/fixtures/chaos_disk.go
- e2e/fixtures/chaos_http.go
- e2e/fixtures/chaos_network.go
- e2e/fixtures/chaos_pod.go
- e2e/fixtures/factory.go
- e2e/fixtures/fdb_operator_fixtures.go
- e2e/fixtures/kubernetes_fixtures.go
- e2e/fixtures/pods.go
- e2e/fixtures/random_string.go
- e2e/fixtures/singleton.go
- e2e/fixtures/status.go
- e2e/test_operator/operator_test.go
- e2e/test_operator_ha_upgrades/operator_ha_upgrade_test.go
- e2e/test_operator_maintenance_mode/operator_maintenance_mode_test.go
- e2e/test_operator_stress/operator_stress_test.go
- e2e/test_operator_upgrades/operator_upgrades_test.go
- e2e/test_operator_upgrades_with_chaos/operator_upgrades_with_chaos_test.go
- e2e/test_operator_velocity/operator_velocity_test.go
Fix a few minor bugs in the e2e test suite where some global variables were used instead of the factory scoped variables. This caused that some tests reused the same namespace and in some rare cases it could cause independent test suites to use the same namespace, which obviously caused conflicts.
-
Ran tests manually.
-
-
> Minor bug fixes for the e2e test suite

- api/v1beta2/foundationdbcluster_types.go
- controllers/cluster_controller.go
- controllers/update_status.go
Fixes: https://github.com/FoundationDB/fdb-kubernetes-operator/issues/873
Before that we would reset the generation to 0 which can be confusing in many cases when the reconciliation drops from a precious number to 0.
Ran unit tests and an e2e test suite.
Not needed.
-
> Don't reset the last reconciled generation

- e2e/test_operator_upgrades/operator_upgrades_test.go
As expected the upgrade will be stuck until the fdb-kubernetes-monitor can communicate to the K8s API again.
- Other
-
Ran the test manually:
```text
• [377.644 seconds]
[AfterSuite]
/Users/jscheuermann/go/src/github.com/FoundationDB/fdb-kubernetes-operator/e2e/test_operator_upgrades/operator_upgrades_test.go:55
[ReportAfterSuite] PASSED [0.004 seconds]
Ran 1 of 11 Specs in 377.644 seconds
SUCCESS! -- 1 Passed | 0 Failed | 0 Pending | 10 Skipped
PASS | FOCUSED
FAIL    github.com/FoundationDB/fdb-kubernetes-operator/e2e/test_operat …
```
> Add an upgrade test case where a single fdb-kubernetes-monitor is not able to connect to the Kubernetes API

- api/v1beta2/foundationdb_labels.go
- controllers/remove_process_groups.go
- controllers/remove_process_groups_test.go
- docs/manual/debugging.md
- e2e/test_operator/operator_test.go
Fixes: https://github.com/FoundationDB/fdb-kubernetes-operator/issues/1906
Operator support for https://github.com/apple/foundationdb/pull/11464.
-
Added a new e2e test for that and ran it manually:
```text
ReportAfterSuite] Autogenerated ReportAfterSuite for --junit-report
[ReportAfterSuite] PASSED [0.003 seconds]
Ran 1 of 54 Specs in 424.461 seconds
SUCCESS! -- 1 Passed | 0 Failed | 10 Pending | 43 Skipped
PASS | FOCUSED
FAIL    github.com/FoundationDB/fdb-kubernetes-operator/e2e/test_operator       424.992s
FAIL
```
Added the documentation for this new feature.
-
> Add support for isolating a process group in the operator

- controllers/cluster_controller.go
- e2e/Makefile
- e2e/fixtures/fdb_operator_client.go
- e2e/fixtures/options.go
There have been some issues in the past when we tested SSA in the current implementation with default values and it's also a known issue with the controller-runtime, e.g.: https://github.com/kubernetes-sigs/controller-runtime/issues/1669 (only to link one issue).
This will add some more cpu cycles to the operator when pushing the patch but I think this is the simplest way to approach this issue right now. Once the controller-runtime has a better approach we can remove this workaround.
Ran a manual e2e test.
CI will run all e2e tests with the SSA feature as I enabled it in the operator deployment.
-
-
> Make use of unstructured when using SSA to prevent default values causing issues

- e2e/test_operator/operator_test.go
We have seen a few failures for those test cases where the default 5 min timeout was not enough. The failures were observed when multiple test suites were running in parallel.
-
-
-
-
> Increase the replacement wait time

- controllers/cluster_controller.go
Since our e2e tests cases are now running (randomly) with server-side apply enabled, we observed a bug in the operator where the operator is not able to reclaim the ownership:
```text
Apply failed with 1 conflict: conflict with \"test_operator.test\" with subresource \"status\" using apps.foundationdb.org/v1beta2: .status.processGroups 
```
The fix for this is to force the ownership again.
I ran the affected test case manually and I didn't observe the issue.
-
-
> Make sure the fdb-kubernetes-operator is forcing the ownership of the status subresource

- e2e/test_operator/operator_test.go
- e2e/test_operator_upgrades/operator_upgrades_test.go
One fix for a test case that could hit https://github.com/apple/foundationdb/issues/11222 in rare cases and an increase in the timeout time for the crash-looping setup.
-
Ran those test manually but CI will also run them.
-
-
> Minor fixes for our e2e tests to improve reliability

- api/v1beta2/foundationdbcluster_types.go
- controllers/add_process_groups.go
- controllers/add_process_groups_test.go
Fix a bug where the same process group ID could be generated.
0
Added an additional test case for this. Without the fix the test case failed.
-
-
> Fix a bug where a process group with the same ID could be generated

- e2e/fixtures/fdb_data_loader.go
- e2e/test_operator/operator_test.go
- e2e/test_operator_velocity/operator_velocity_test.go
- internal/node_predicate.go
Disable some unified image tests that use features that are not yet present in the image used by the nightlies. 
I sneaked in some minor changes to the test reliability, e.g. to print the status of the data loader pods and increase the wait time.
-
-
-
-
> Disable unified image tests until image is updated

- controllers/update_pods.go
- controllers/update_pods_test.go
- docs/manual/operations.md
Fixes: https://github.com/FoundationDB/fdb-kubernetes-operator/issues/1876
-
-
Updated.
-
> Document the delay shutdown feature and check in update Pods if pod is missing

- e2e/test_operator_upgrades_variations/operator_upgrades_variations_test.go
Add more logging for missing processes in upgrade variations.
- Other
Those additional logs hopefully help to better debug some of the failures during the upgrade variations.
-
-
> Add more logging for missing processes in upgrade variations

- e2e/fixtures/fdb_cluster.go
- e2e/test_operator/operator_test.go
- e2e/test_operator_upgrades/operator_upgrades_test.go
- e2e/test_operator_upgrades_with_chaos/operator_upgrades_with_chaos_test.go
Fix race condition in e2e test suite when checking if a pod is deleted. The race condition can happen when a pod is deleted and in between those checks the operator was recreating the pod quick enough. The additional check for the pod's UID will fix that, if the fetched pod has a new UID, we know that the fetched pod is a different pod.
-
Manually ran tests.
-
-
> Fix race condition in e2e test suite when checking if a pod is deleted

- .github/workflows/pull_request.yml
- .github/workflows/release.yaml
- Dockerfile
Update go version: https://go.dev/doc/devel/release#go1.22.5
- Other
-
-
-
> Update go version to 1.22.5

- controllers/remove_process_groups.go
- controllers/remove_process_groups_test.go
In most cases this check is not harmful, only in cases where someone would implement their own pod manager and that one would return a `nil` instead of a pointer to an empty pod struct.
-
Ran unit tests locally.
-
-
> Make sure to only check the isolate process group annotation if a pod was returned

- e2e/fixtures/kubernetes_fixtures.go
- e2e/fixtures/test_runner.go
- e2e/test_operator/suite_test.go
- e2e/test_operator_creation_velocity/suite_test.go
- e2e/test_operator_ha/suite_test.go
- e2e/test_operator_ha_flaky_upgrades/suite_test.go
- e2e/test_operator_ha_upgrades/suite_test.go
- e2e/test_operator_maintenance_mode/suite_test.go
- e2e/test_operator_migrate_image_type/suite_test.go
- e2e/test_operator_migrations/suite_test.go
- e2e/test_operator_stress/suite_test.go
- e2e/test_operator_upgrades/suite_test.go
- e2e/test_operator_upgrades_variations/suite_test.go
- e2e/test_operator_upgrades_with_chaos/suite_test.go
Prevent cases where two concurrent test suites will choose the same random namespace and cluster name. This change will make sure that only one test suite will take the namespace and the other test suite will generate a new random name. This will prevent cases where those two concurrent test suites use the same namespace, which will cause a failure of both test cases.
-
Ran a manual test (the test suite was picking the same namespace as I defined it with the according environment variable):
```text
Operator Stress when creating and deleting a cluster multiple times should create a healthy and available cluster [e2e]
/Users/jscheuermann/go/src/github.com/FoundationDB/fdb-kubernetes-operator/e2e/te …
```
> Check if the namespace is created by the same test suite

- controllers/cluster_controller.go
- e2e/test_operator_ha_upgrades/operator_ha_upgrade_test.go
- fdbclient/admin_client.go
- fdbclient/admin_client_test.go
- fdbclient/common.go
- pkg/fdbadminclient/admin_client.go
- pkg/fdbadminclient/mock/admin_client_mock.go
We sometimes see that the test case `Operator HA Upgrades when no remote storage processes are restarted` fails where the coordinators are reporting in the new upgraded version but the cluster is stuck with the following message:
```json
"messages": [
{
"name": "status_incomplete_timeout",
"description": "Timed out fetching cluster status."
}
]
```
The idea for this change is to get the running version based on the reachable coordinators. If a quorum of coordinators can be reached with a specific `fdbcli` version the operator will assume that the cluster is running in that version. Doing that will unblock the operator and will allow the operator to move forward. If the running version is not updated to the new desired version the reconciler `checkClientCompatibility` will block (as the …
> Try to get the running version based on the reachable coordinators during an upgrade

- charts/fdb-operator/templates/rbac/rbac_role.yaml
- charts/fdb-operator/templates/rbac/rbac_role_binding.yaml
- charts/fdb-operator/values.yaml
These changes add `get`, `watch`, and `list` permissions to the `fdb-operator` helm chart. These permissions are required to detect `taints` on nodes and enable  the rotation of `FDB` cluster pods when `taintReplacementOptions` are used.
We tested these changes on our various Kubernetes clusters.
> Adding permissions for "nodes" resources to the helm chart (#2091)

- docs/manual/fault_domains.md
`databaseConfiguration.redundancy_mode` is the correct reference; updated in a few places in `fault_domains.md`.
> Fix typo in documentation mention of redundancy_mode

- controllers/update_status.go
- e2e/test_operator_migrate_image_type/operator_migate_image_type_test.go
- internal/monitor_conf.go
- internal/monitor_conf_test.go
- pkg/fdbadminclient/mock/admin_client_mock.go
The `GetStartCommandWithSubstitutions` method needs to create the command line based on the image type of the current pod, no the desired image type.
-
e2e tests:
```text 
Ran 1 of 3 Specs in 969.974 seconds
SUCCESS! -- 1 Passed | 0 Failed | 0 Pending | 2 Skipped
PASS | FOCUSED
FAIL    github.com/FoundationDB/fdb-kubernetes-operator/e2e/test_operator_migrate_image_type    970.545s
FAIL
```
-
-
> Fix the update status setup when a different image type is used

- api/v1beta2/foundationdb_constants.go
- api/v1beta2/image_config_test.go
- controllers/cluster_controller_test.go
- e2e/fixtures/options.go
- internal/deprecations.go
- internal/deprecations_test.go
- internal/pod_models_test.go
Correcting the default base image for the unified image.
-
Added unit tests and e2e test will be running.
-
-
> Correct the base image for the unified image and increase the memory for the FDB pods to 8GiB

- controllers/update_status.go
- controllers/update_status_test.go
Fixes: https://github.com/FoundationDB/fdb-kubernetes-operator/issues/2105
I think the update status is the best place as we have to check the command line with the substituted env variables.
Added a new unit test and CI will run e2e tests. I don't think an additional e2e test is required
-
-
> Make sure the operator provides an error message when the command line is too long

- api/v1beta2/foundationdbcluster_types.go
- controllers/update_status.go
- e2e/fixtures/chaos_disk.go
- e2e/test_operator/operator_test.go
Allow the operator to replace process groups with an I/O error.
Performed testing with the e2e tests. Modified an existing test for this use case.
-
-
> Allow the operator to replace process groups with an I/O error

- e2e/Makefile
Make sure the e2e tests are running with different storage engines
-
Ran a manual test with it.
-
-
> Make sure the e2e tests are running with different storage engines

- controllers/bounce_processes.go
- controllers/change_coordinators.go
- controllers/check_client_compatibility.go
- controllers/choose_removals.go
- controllers/cluster_controller.go
- controllers/cluster_controller_test.go
- controllers/exclude_processes.go
- controllers/maintenance_mode_checker.go
- controllers/remove_incompatible_processes.go
- controllers/remove_process_groups.go
- controllers/replace_failed_process_groups.go
- controllers/update_database_configuration.go
- controllers/update_lock_configuration.go
- controllers/update_pods.go
- controllers/update_status.go
- fdbclient/admin_client.go
- fdbclient/common.go
- internal/locality/locality.go
- pkg/fdbadminclient/database_provider.go
- pkg/fdbadminclient/mock/database_provider.go
- pkg/fdbstatus/status_checks.go
Those changes make use of the same logger that the (sub)reconciler uses, that way it's easier to track back which reconciler issued the command. In addition I added a trace ID field to make it easier to track a single reconcile run.
Fixes: https://github.com/FoundationDB/fdb-kubernetes-operator/issues/2118
-
Ran unit tests and e2e test will be running.
-
-
> Improve logging for fdbclient and lock client to see what subreconciler issued the command

- controllers/bounce_processes.go
- controllers/change_coordinators.go
- controllers/exclude_processes.go
- controllers/maintenance_mode_checker.go
- controllers/remove_process_groups.go
- controllers/update_database_configuration.go
- controllers/update_pods.go
- fdbclient/lock_client.go
In the past we added code to release the lock when the operation was performed. Doing that increases the risk of race conditions when multiple operator instances are managing a multi-region (or three data hall) FDB cluster. In order to reduce the risk of those race conditions the operator is releasing the lock only when the cluster is reconciled (or when the lock is timed out).
The general idea of the locking mechanism is to reduce the operations executed in parallel on the FDB cluster. When the lock is directly released after the operation we have the risk that another operator instance is directly doing another operation that could be disruptive, e.g. excluding processes.
e2e test will be …
> Only release the lock when the cluster is reconciled

- Dockerfile
- Makefile
- e2e/fixtures/factory.go
- e2e/fixtures/singleton.go
- e2e/test_operator_plugin/operator__plugin_test.go
- e2e/test_operator_plugin/operator_plugin_test.go
- e2e/test_operator_plugin/suite_test.go
- e2e/test_operator_upgrades_variations/operator_upgrades_variations_test.go
- internal/kubernetes/kubernetes.go
- kubectl-fdb/cmd/analyze.go
- kubectl-fdb/cmd/buggify_crash_loop.go
- kubectl-fdb/cmd/buggify_crash_loop_test.go
- kubectl-fdb/cmd/buggify_no_schedule.go
- kubectl-fdb/cmd/exclusion_status.go
- kubectl-fdb/cmd/exclusion_status_test.go
- kubectl-fdb/cmd/exec.go
- kubectl-fdb/cmd/exec_test.go
- kubectl-fdb/cmd/fix_coordinator_ips.go
- kubectl-fdb/cmd/fix_coordinator_ips_test.go
- kubectl-fdb/cmd/k8s_client.go
- kubectl-fdb/cmd/k8s_client_test.go
- kubectl-fdb/cmd/plugin_version_checker.go
- kubectl-fdb/cmd/restart.go
- kubectl-fdb/cmd/suite_test.go
Refactored the code to execute a command inside a Pod to use the same code in the plugin and the test suite and added an e2e test suite for the plugin.
Fixes: https://github.com/FoundationDB/fdb-kubernetes-operator/issues/1352 (more test will be implemented in the future).
Ran the test manually:
```text
[ReportAfterSuite] PASSED [0.002 seconds]
Ran 1 of 1 Specs in 69.951 seconds
SUCCESS! -- 1 Passed | 0 Failed | 0 Pending | 0 Skipped
--- PASS: TestOperator (69.95s)
PASS
ok      github.com/FoundationDB/fdb-kubernetes-operator/e2e/test_oper …
```
> Refactor exec code to share same code and add plugin e2e test suite

- controllers/bounce_processes.go
- controllers/bounce_processes_test.go
- e2e/fixtures/fdb_cluster.go
- e2e/test_operator_ha_upgrades/operator_ha_upgrade_test.go
- go.mod
A cluster that contains tester processes can block the upgrade. The changes in this PR will change this and ignore tester processes in the pending upgrade check as those processes are reporting to the cluster but cannot be restarted with `fdbcli`.
I added a new e2e test for this setup.
-
-
> Improve the tester handling when a cluster is upgraded

- e2e/fixtures/fdb_cluster.go
- e2e/test_operator_ha_upgrades/operator_ha_upgrade_test.go
I saw a few times test failing at the team tracker where the teams tracker check timed out. Increasing the timeout will probably help there. 
-
-
-
> Change timeout for health tracker test

- e2e/fixtures/factory.go
- e2e/fixtures/fdb_operator_client.go
- e2e/test_operator/operator_test.go
- internal/kubernetes/kubernetes.go
Fix the get logs from pod setup (`GET` vs. `POST` 🙄 )
-
I added an additional test statement to make sure logs are received.
-
-
> Fix the get logs from Pod set

- e2e/fixtures/chaos_network.go
- e2e/test_operator/operator_test.go
- e2e/test_operator_ha/operator_ha_test.go
Add a new e2e test to see how exclusions behave if a log process in the remote region has high latencies.
- Other
-
CI will run the test and I'm running it manually.
Will be added to the test case.
-
> Add an operator e2e exclusion tests when a single log process has high latency

- e2e/fixtures/factory.go
- e2e/fixtures/fdb_data_loader.go
- e2e/fixtures/options.go
Fix issues in the e2e test suite when only a single version mapping it provided (but not a mapping for the primary version) and fix an issue in the data loader.
-
I manually ran those tests with the new config.
-
-
> Fix some bugs in the e2e test suite when only one version mapping is provided and fix the setup of the data loader

- README.md
- docs/manual/customization.md
- docs/manual/technical_design.md
- e2e/README.md
Fixes: https://github.com/FoundationDB/fdb-kubernetes-operator/issues/1036.
Images are pushed to: https://hub.docker.com/r/foundationdb/fdb-kubernetes-monitor
We already had some e2e tests for the unified image.
-
-
> Update docs unified image

- controllers/remove_process_groups.go
- controllers/remove_process_groups_test.go
- setup/setup.go
Fixes a bug where the process group gets removed from the `FoundationDBCluster` status without getting the addresses included. The side effect of this bug is that some addresses in the cluster are not included again. The issue will only happen if multiple process groups should be replaced across different zones.
-
Updated the test cases and ran the e2e test for this with an extended inclusion delay.
-
-
> Fix the case where the process group gets removed without the addresses being included

- .github/workflows/pull_request.yml
- .github/workflows/release.yaml
- Dockerfile
Fixes: https://github.com/FoundationDB/fdb-kubernetes-operator/issues/2151
- Other
-
Ran unit tests and CI will run e2e tests.
-
-
> Update go version to 1.22.8

- e2e/test_operator_plugin/operator_plugin_test.go
- kubectl-fdb/cmd/recover_multi_region_cluster.go
Setting the remove cluster into the skip mode, should make the tests more reliable and reduce the risk of a race condition.
-
Ran the e2e test for the plugin manually.
0
https://github.com/FoundationDB/fdb-kubernetes-operator/issues/2153 (will e fixed in another PR).
> Make sure that the remove cluster is skipped too and add more debugging output for the plugin

- controllers/generate_initial_cluster_file.go
- e2e/fixtures/cluster_config.go
- e2e/fixtures/fdb_cluster_specs.go
- e2e/test_operator_upgrades_variations/operator_upgrades_variations_test.go
- internal/coordinator/coordinator.go
- internal/locality/locality.go
- internal/locality/locality_test.go
- internal/pod_client.go
Fixes: https://github.com/FoundationDB/fdb-kubernetes-operator/issues/2155
-
Created a new test setup. I decided to add the new test case to the upgrade test as this includes creating a new cluster.
-
-
> Fix the unified image setup during bootstrap when a custom environment variable is used for the zone

- controllers/exclude_processes.go
- controllers/exclude_processes_test.go
The changes of this PR try to batch the exclusions of transaction system processes together, e.g. stateless and transaction processes. This should reduce the number of exclusions (and recoveries). This change will be useful as the stateless pods are normally scheduled faster than the transaction/log pods as they have to wait for the volume to be provisioned.
It's not a correctness bug but the operator will be issuing more exclusions than required.
-
Added new unit tests and CI will run the e2e tests.
Added docs in the code.
-
> Try to batch the exclusions of transaction system processes together

- controllers/cluster_controller_test.go
- controllers/suite_test.go
- pkg/fdbadminclient/mock/admin_client_mock.go
Fixes a testing bug that was introduced in https://github.com/FoundationDB/fdb-kubernetes-operator/pull/2158/files#diff-d0ad2e8f0d701fc00f8cd16ca0799d0e7e3a6a508245c60e122770680d3498a5R897. The `clusterReconciler` is a global struct, so the value was never set back to `true`, which causes failures in some test cases.
-
Ran unit test manually with the race flag.
-
-
> Ensure the the cluster reconciler status is set to be in simulation after each test

- controllers/bounce_processes.go
- e2e/test_operator/operator_test.go
- fdbclient/admin_client.go
- fdbclient/admin_client_test.go
- pkg/fdbadminclient/admin_client.go
- pkg/fdbadminclient/mock/admin_client_mock.go
- pkg/fdbstatus/status_checks.go
- pkg/fdbstatus/status_checks_test.go
Fixes: https://github.com/FoundationDB/fdb-kubernetes-operator/issues/2161
-
I added a new operator test and performed some manual tests and monitored the fdb-monitor-log:
```text
Time="1731500867.138682" Severity="10" LogGroup="jscheuermann-jdev" Process="fdbmonitor": Could not remove inotify conf file watch, continuing...
Time="1731500867.138731" Severity="10" LogGroup="jscheuermann-jdev" Process="fdbmonitor": Watching conf file /var/dynamic-conf/fdbmonitor.conf
Time="1731500867.138742" Severity="10" LogGroup="jscheuermann-jdev" Process="fdbmonitor": Watching conf dir /var/dynamic-conf/ (10)
Time="1731500867.138749" Severity="10" LogGroup="jscheuermann-jdev" Process="fdbmonitor": Loading …
```
> Restart processes only once when doing a setting rollout and include uptime from processes

- controllers/exclude_processes.go
- fdbclient/admin_client.go
- pkg/fdbadminclient/admin_client.go
- pkg/fdbadminclient/mock/admin_client_mock.go
Always make use of the no_wait flag in the exclude controller to reduce the noise from exclusions that timeout.
-
-
-
> Always make use of the no_wait flag in the exclude controller to reduce the noise from exclusions that timeout

- e2e/fixtures/fixtures.go
- e2e/test_operator_ha_upgrades/operator_ha_upgrade_test.go
Fix the error reporting for the unavailability checker in cases where the cluster gets available again, e.g.:
```text
2024/11/29 01:48:16 invariant InvariantClusterStatusAvailableWithThreshold failed for the first time
2024/11/29 01:48:16 invariant InvariantClusterStatusAvailableWithThreshold failed: cluster is not available
2024/11/29 01:48:31 invariant InvariantClusterStatusAvailableWithThreshold failed after: 15.223519039s
2024/11/29 01:48:37 invariant InvariantClusterStatusAvailableWithThreshold failed after: 20.467108341s
2024/11/29 01:48:44 invariant InvariantClusterStatusAvailableWithThreshold true again
...
Operator Upgrades [AfterEach] upgrading a cluster with a pending pod Upgrade from 7.1.57 to 7.1.63 with a pending pod [e2e, pr]
[AfterEach] …
```
> Correct the failure duration for unavailable checks

- e2e/fixtures/fdb_cluster.go
- e2e/test_operator/operator_test.go
- e2e/test_operator_maintenance_mode/operator_maintenance_mode_test.go
- e2e/test_operator_upgrades/operator_upgrades_test.go
Improve the reliability of the pod pending test case. We sometimes see that the test is timing out and it seems like the test is failing because the reconciliation is requeue:
```text
2024/11/26 01:41:00 Failed (unscheduled) Pod: operator-test-fdnhokqf-stateless-42898 , Pod to replace: operator-test-fdnhokqf-stateless-93723
...
{"level":"debug","ts":"2024-11-26T01:47:47Z","logger":"events","msg":"cannot: exclude processes, clusters last recovery was 0.00 seconds ago, wait until the last recovery was 1 seconds ago" ....}
{"level":"debug","ts":"2024-11-26T01:51:08Z","logger":"controller","msg":"Deleting pod","namespace":"nightly-2002-operator-test-irgo4uxk","cluster":"operator-test-fdnhokqf","traceID":"9ba8d86f-3d1d-4b79-ba60-09fef6771a49","reconciler":"controllers.removeProcessGroups","name …
```
> Improve the reliability of the pod pending test case

- internal/pod_models.go
- internal/pod_models_test.go
Correct init container setup for unified image with backups.
-
Ran the backup e2e test manually:
```text
[ReportAfterSuite] PASSED [0.001 seconds]
Ran 1 of 1 Specs in 182.198 seconds
SUCCESS! -- 1 Passed | 0 Failed | 0 Pending | 0 Skipped
--- PASS: TestOperator (182.20s)
PASS
ok      github.com/FoundationDB/fdb-kubernetes-operator/e2e/test_operator_backups       182.750s
```
-
-
> Correct init container setup for unified image with backups

- docs/design/better_coordination_multi_operator.md
Add design for better coordination for multi operator setup. This design takes a few ideas from the lock client that we use for the minor and major version upgrades when the operator has to perform a restart all fdb server processes at "the same time".
- Other
Those changes should minimize the disruption of upgrades and settings roll-outs. 
There is still a chance that more exclusions are trigger than required e.g. if some operator instances are very slow.
-
Added for the design.
-
> Add design for better coordination for multi operator setup

- .github/workflows/pull_request.yml
- .github/workflows/release.yaml
- Dockerfile
Update go version to 1.22.10 and RockyLinux to 9.5
- Other
-
-
-
> Update go version to 1.22.10 and RockyLinux to 9.5

- e2e/fixtures/factory.go
- e2e/fixtures/fixtures.go
- e2e/test_operator_plugin/operator_plugin_test.go
Otherwise I saw cases where the clusters where not properly recreated.
-
Ran e2e tests for the plugin manually.
-
-
> Fix the plugin e2e test setup

- e2e/test_operator_ha_upgrades/operator_ha_upgrade_test.go
See: https://github.com/FoundationDB/fdb-kubernetes-operator/issues/2196
- Other
Marking the test as pending until we fixed the test setup or the operator to reliably pass.
-
-
-
> Mark the HA upgrade test where no remote processes are restarted as pending until it passes reliably

- internal/pod_models.go
- internal/pod_models_test.go
Fixes an issue with the unified image if an init container with the name `foundationdb-kubernetes-init` is present. The `foundationdb-kubernetes-init` init container is used in the split image but not the unified image, so we should ensure that if an init container with that name is present, it is removed.
-
Ran the test suite with an init container and the unified image.
-
-
> Ensure the init container is removed if the unified image should be used

- api/v1beta2/foundationdbrestore_types.go
- config/crd/bases/apps.foundationdb.org_foundationdbrestores.yaml
- controllers/restore_controller.go
- controllers/start_restore.go
- controllers/update_restore_status.go
- controllers/update_restore_status_test.go
- docs/manual/backup.md
- docs/restore_spec.md
- e2e/fixtures/fdb_restore.go
Adding some additional visibility to the restore state and add additional docs on how to debug a stuck restore.
-
Updated the e2e test and ran it manually:
```text
[ReportAfterSuite] PASSED [0.003 seconds]
Ran 1 of 1 Specs in 222.060 seconds
SUCCESS! -- 1 Passed | 0 Failed | 0 Pending | 0 Skipped
--- PASS: TestOperator (222.06s)
PASS
ok      github.com/FoundationDB/fdb-kubernetes-operator/e2e/test_operator_backups       222.673s
```
-
-
> Add the restore state to the restore CRD

- e2e/fixtures/cluster_config.go
- e2e/fixtures/fdb_cluster_specs.go
Allow to set the peer verification string in the cluster config for testing different peer verification strings.
- Other
-
Ran unit tests CI will run e2e tests.
-
-
> Allow to modify the e2e peer verification string

- controllers/admin_client_test.go
- controllers/restore_controller.go
- controllers/restore_controller_test.go
- e2e/fixtures/fdb_restore.go
- pkg/fdbadminclient/mock/admin_client_mock.go
Ensure the the restore controller requeues the restore resource if the restore is not completed.
-
Ran the backup e2e tests manually.
-
-
> Ensure reconcilation is requeued for restore controller if the restore is not completed

- api/v1beta2/foundationdbcluster_types.go
- api/v1beta2/foundationdbcluster_types_test.go
- controllers/add_process_groups.go
- controllers/add_process_groups_test.go
Fixes:  https://github.com/FoundationDB/fdb-kubernetes-operator/issues/1862
This change improves the add process group subreconciler to not pick an already excluded process group ID. In general those cases should be rare but it's better to not use the process group ID if the locality was already excluded, e.g. manually, otherwise the new process group will be created and then replaced.
Added new unit tests.
N/A
-
> Check if the newly added process group ID is already excluded

- e2e/fixtures/options.go
Ensure that the tag suffix is only added when it is missing. This should prevent cases like `sidecar-1-1`.
-
Ran some manual e2e tests for this.
-
-
> Ensure that the tag suffix is only added when it is missing

- internal/configmap_helper.go
- internal/configmap_helper_test.go
- internal/pod_models.go
- internal/pod_models_test.go
Ensure that the ConfigMap name for the cluster can't be modified. Before this change the `ConfigMap` name could be changed but those changes had a few issues and bugs, so it's better to completely remote this option and ensure that the `ConfigMap` name is always the same. Also fixed a small bug in the `imageConfig` for backup.
Part of 2.0 release.
Unit tests + CI will run e2e tests.
Will be updated in a follow up PR.
-
> Ensure that the ConfigMap name for the cluster can't be modified

- docs/manual/warnings.md
Fix typo "storagerServersPerPod" -> "storageServersPerPod" in docs.
> Fix typo storagerServersPerPod

- controllers/bounce_processes.go
- controllers/change_coordinators.go
- controllers/cluster_controller.go
- controllers/exclude_processes.go
- controllers/maintenance_mode_checker.go
- controllers/remove_process_groups.go
- controllers/update_database_configuration.go
- controllers/update_pods.go
- fdbclient/lock_client.go
- pkg/fdbadminclient/lock_client.go
- pkg/fdbadminclient/mock/lock_client.go
- pkg/fdbadminclient/mock/lock_client_test.go
This PR changes the lock client interface and not getting a lock will result in an error too. We could create a dedicated error type for this, but I think it's easier to work with the lock client this way instead of having two values which were checked differently.
Based on https://github.com/FoundationDB/fdb-kubernetes-operator/pull/2212
-
Unit tests + CI e2e
-
-
> Streamline lock client usage

- e2e/Makefile
- e2e/test_operator_upgrades_variations/operator_upgrades_variations_test.go
Adding a new Ginkgo label for running a single test (right now) to perform an upgrade/downgrade test. In the future we could be adding more test cases.
- Other
-
Manually ran the tests with an e2e test selector.
-
-
> Add a new label for running a quick upgrade test case

- controllers/add_process_groups.go
- controllers/add_services.go
- e2e/Makefile
- e2e/fixtures/cluster_config.go
- e2e/fixtures/factory.go
- e2e/fixtures/fdb_cluster.go
- e2e/fixtures/fdb_cluster_specs.go
- e2e/fixtures/fdb_operator_client.go
- e2e/test_operator/operator_test.go
- e2e/test_operator_ha/operator_ha_test.go
- e2e/test_operator_ha_upgrades/operator_ha_upgrade_test.go
- e2e/test_operator_three_data_hall/operator_three_data_hall_test.go
- e2e/test_operator_upgrades/operator_upgrades_test.go
- e2e/test_operator_upgrades_variations/operator_upgrades_variations_test.go
- e2e/test_operator_upgrades_with_chaos/operator_upgrades_with_chaos_test.go
- e2e/test_operator_velocity/operator_velocity_test.go
- pkg/fdbstatus/status_checks.go
Update the e2e tests to reflect the new defaults.
- Other
Make sure we use the same defaults in the e2e tests as we use in the operator.
CI will be running e2e tests.
-
-
> Update the e2e tests to reflect the new defaults

- controllers/controllers.go
- controllers/controllers_test.go
This checks that the target maps when merging custom annotations/labels are not `nil`, thereby avoiding panics. It fixes #2226.
> Avoid panics when merging custom annotation/labels

- e2e/test_operator_three_data_hall/operator_three_data_hall_test.go
Remove the 3DH setup from e2e pipeline to reduce required resources. The main idea is to reduce the required resources for our e2e test pipelines, we eventually enable those tests again. If someone changes things related to 3DH we can run those tests manually.
- Other
-
-
-
-
> Remove the 3DH setup from e2e pipeline to reduce required resources

- controllers/choose_removals.go
- e2e/fixtures/cluster_config.go
- e2e/fixtures/cluster_config_test.go
Allow to modify the default CPU and memory for pods, e.g. to perform tests with different CPU/memory settings.
-
Updated unit tests and CI will run e2e tests.
-
-
> Allow to modify the default CPU and memory for pods

- controllers/exclude_processes.go
- internal/locality/locality.go
Change the ordering of the coordinator change and the exclusion. It's better to first run the exclusion and then change the coordinators, this should ensure that the processes are excluded faster, e.g. in a case where the coordinator change causes a long recovery. We previously implemented with the coordinators change first because we waited for the exclusion to complete, since we use the `no_wait` option now per default, the exclude command shouldn't timeout, expect in cases where the FDB cluster is in a bad state. So doing the exclude first and then the coordinator change seems like the better choice to ensure that the processes are quickly excluded.
I labeled this as a bug but arguably this is not a bug.
-
-
> Change the ordering of the coordinator change and the exclusion

- e2e/Makefile
- e2e/README.md
- e2e/fixtures/cluster_config.go
- e2e/fixtures/factory.go
- e2e/fixtures/options.go
- e2e/test_operator/operator_test.go
This PR includes more detailed documentation for running e2e tests, as well as one customization know that helped me start the tests in my environment, and a minor fix for a bug that prevents running e2e tests in a cluster without storage class labels.
n/a
Manually tested the code changes.
PR includes documentation of the new setting.
n/a
> Improvements to e2e tests and documentation

- api/v1beta2/foundationdb_process_address.go
- api/v1beta2/foundationdbcluster_types.go
- api/v1beta2/foundationdbcluster_types_test.go
- controllers/cluster_controller.go
- controllers/generate_initial_cluster_file.go
Fix a bug in the connection string parser when a cluster has a single letter as name. Before that the `ParseConnectionString` method would return an error. In addition we will validate the initial cluster file before creating it.
-
Added unit tests and CI will run e2e tests.
-
-
> Fix a bug in the connection string parser when a cluster has a single letter as name

- api/v1beta2/foundationdb_labels.go
- api/v1beta2/foundationdbcluster_types.go
- docs/cluster_spec.md
- e2e/test_operator/operator_test.go
- internal/pod_helper.go
- internal/pod_helper_test.go
- internal/pod_models.go
- internal/replacements/replacements.go
- internal/replacements/replacements_test.go
Fixes: https://github.com/FoundationDB/fdb-kubernetes-operator/issues/2243
With the previous behaviour it could happen that the coordinators went unreachable because they were listening on the wrong IP family and then the operator would get stuck. This change prevents it by spinning up a new set of pods.
Added a new e2e test to convert from `nil` family to `v4`. I run some tests in a dual-stack cluster.
-
https://github.com/FoundationDB/fdb-kubernetes-operator/issues/834 the idea here would be to listen on both addresses for some time.
> Ensure that pods are replaced if we change the Pod IP family

- controllers/update_pods.go
- controllers/update_pods_test.go
Ensure that the operator checks if the processes for newly created pods are up and running for the update pod config reconciler. This would handle the case where the operator did update a pod, which is already running with the new configuration but the process is not yet running. In the previous implementation the operator would be allowed to proceed with the updates if the fault tolerance metrics allow to proceed, in cases where the deletion and recreation of the pod would be fairly quick (less than 60 seconds) we could hit cases where the operator is taking down pods in another zone, even thought not all processes are up and running in the previous zone (and potentially never come up).
-
Added unit tests. Adding an e2e test for this …
> Ensure that the operator checks if the processes for newly created pods are up and running for the update pod config reconciler

- controllers/cluster_controller.go
- controllers/update_config_map.go
- controllers/update_status.go
- docs/manual/debugging.md
- fdbclient/admin_client.go
- fdbclient/admin_client_test.go
- fdbclient/common.go
- fdbclient/common_test.go
- kubectl-fdb/cmd/root.go
- kubectl-fdb/cmd/suite_test.go
- kubectl-fdb/cmd/update.go
- kubectl-fdb/cmd/update_connection_string.go
- kubectl-fdb/cmd/update_connection_string_test.go
- pkg/fdbadminclient/admin_client.go
Make use of dedicated cluster file for the fdb client lib and ensure to reuse it. The cli tooling will get a temp cluster file which will be deleted after the command was used.
Ran e2e tests related to HA clusters.
I have to add another test in the e2e setup to see what happens when an operator is partitioned and all coordinators change (and no old coordinator is around) and how to resolve this case, in the previous setup a user could just update the `SeedConnectionString`.
Will be updated before merging.
We should add a command in the kubectl plugin to update the connection string in the `FoundationDBCluster` status.
> Update cluster file usage.

- kubectl-fdb/cmd/cordon.go
- kubectl-fdb/cmd/cordon_test.go
The previous behaviour was bad in cases where a few hosts where not hosting any pods, in this case the whole command would be aborted. I think it's better to just print a warning instead of returning an error and stop everything. In some cases when enough nodes are selected (e.g. with a node selector) the chances that a single node not hosting any pods, is fairly high.
-
Adjusted unit tests and ran some manual tests.
-
-
> Ensure that the cordon command doesn't stop when a node doesn't host any pods

- api/v1beta2/foundationdbcluster_types.go
- api/v1beta2/foundationdbcluster_types_test.go
- controllers/bounce_processes.go
- controllers/exclude_processes.go
- controllers/exclude_processes_test.go
- controllers/remove_process_groups.go
- controllers/remove_process_groups_test.go
- controllers/update_status.go
- docs/manual/fault_domains.md
- e2e/Makefile
- e2e/fixtures/fdb_cluster.go
- e2e/test_operator/operator_test.go
- e2e/test_operator_ha/operator_ha_test.go
- e2e/test_operator_ha_upgrades/operator_ha_upgrade_test.go
- fdbclient/admin_client.go
- fdbclient/admin_client_test.go
- fdbclient/fdb_client.go
- internal/coordination/coordination.go
- internal/coordination/coordination_test.go
- pkg/fdbadminclient/admin_client.go
- pkg/fdbadminclient/mock/admin_client_mock.go
- pkg/fdbadminclient/mock/admin_client_mock_test.go
Test case fix for multi-cluster coordination setup and reduce log level for multi-cluster coordination.  Fixed some other minor bugs in the global coordination setup that I detected during debugging.
-
Ran some test manually.
-
-
> Update test case to set correct resource quota and work with multi-cluster setup

- Dockerfile
Add support for the operator to run on ARM.
Right now only 7.3 and newer is supported as the previous versions don't have the client packages for arm.
Build and ran the image locally.
Added some notes to the Dockerfile.
-
> Add support for the operator to run on ARM

- controllers/cluster_controller.go
- controllers/cluster_controller_test.go
- controllers/suite_test.go
When the operator is executed with `cluster-label-key-for-node-trigger` flag in global mode it goes to crash loop, because the namespace is empty and in `FoundationDBClusterReconciler.findFoundationDBClusterForNode` a null pointer is passed to k8s-client Lister. We fix this issue by passing the variable only if namespace is not empty.
X Bug fix (non-breaking change which fixes an issue)
- Other
N/A
We ran it in different environments. 
No
*Did you update relevant …
> Fix crash in findFoundationDBClusterForNode when in global mode

- controllers/maintenance_mode_checker.go
- internal/maintenance/maintenance.go
- internal/maintenance/maintenance_test.go
If the operator finds maintenance information for a process group that doesn't exist, the operator should mark this information as stale. Otherwise the operator has to wait until the information is marked as stale (exists for more than 4h).
- Other
-
Updated the unit tests.
-
-
> Remove maintenance information if process group doesn't exist

- controllers/add_pods.go
- controllers/cluster_controller.go
- controllers/update_status.go
- e2e/test_operator/operator_test.go
Otherwise this could lead to the operator crashing with:
```text
Error determining public address.
SIGSEGV: segmentation violation
PC=0x7fc6699c41fa m=16 sigcode=1 addr=0x40
signal arrived during cgo execution
```
Fixes: https://github.com/FoundationDB/fdb-kubernetes-operator/issues/2286 (seems like a bug caused by the previous behaviour).
-
Updated the e2e test + an it locally.
-
-
> Run the addPods reconciler before connecting to FDB in case we use DNS entries in the cluster file

- e2e/fixtures/test_runner.go
- e2e/test_operator/operator_test.go
Without this change we get the following stack trace (which is not an error but confusing):
```text
[controller-runtime] log.SetLogger(...) was never called; logs will not be displayed.
Detected at:
>  goroutine 62 [running]:
>  runtime/debug.Stack()
>  	/codebuild/output/src3086599534/pkg/mod/golang.org/toolchain@v0.0.1-go1.24.4.linux-amd64/src/runtime/debug/stack.go:26 +0x5e
>  sigs.k8s.io/controller-runtime/pkg/log.eventuallyFulfillRoot()
>  	/codebuild/output/src3086599534/pkg/mod/sigs.k8s.io/controller-runtime@v0.21.0/pkg/log/log.go:60 +0xcd
>  sigs.k8s.io/controller-runtime/pkg/log.(*delegatingLogSink).WithValues(0xc000314840, {0x0, 0x0, 0x0})
>  	/codebuild/output/src3086599534/pkg/mod/sigs.k8s.io/controller-runtime@v0.21.0/pkg/log/deleg.go:168 +0x49
> …
```
> Set logger in e2e tests to remove the stack trace

- e2e/fixtures/fdb_cluster.go
- e2e/test_operator/operator_test.go
Enable TLS conversion for e2e tests to get a signal about the stability of the conversion.
- Other
I ran the test multiple times with the unified image and the split image (with the local client disabled) and it always passed (ran roughly 3/3).
See above.
-
-
> Enable TLS conversion for e2e tests

- e2e/fixtures/fdb_operator_client.go
- e2e/fixtures/pods.go
This should reduce the cases where the e2e test framework picks a terminating pod randomly. We run enough e2e test cases that we sometimes hit this issue.
-
Ran a test suite manually.
-
-
> Only pick running pods and pods with an empty deletion timestamp

- Dockerfile
- controllers/cluster_controller.go
- e2e/Makefile
- e2e/fixtures/factory.go
- e2e/fixtures/ha_fdb_cluster.go
- e2e/fixtures/options.go
- e2e/fixtures/status.go
- e2e/test_operator/operator_test.go
- e2e/test_operator_ha/operator_ha_test.go
- e2e/test_operator_ha_flaky_upgrades/operator_ha_flaky_upgrade_test.go
- e2e/test_operator_ha_upgrades/operator_ha_upgrade_test.go
- e2e/test_operator_plugin/operator_plugin_test.go
- e2e/test_operator_upgrades/operator_upgrades_test.go
- e2e/test_operator_upgrades_variations/operator_upgrades_variations_test.go
- e2e/test_operator_upgrades_with_chaos/operator_upgrades_with_chaos_test.go
- e2e/test_operator_velocity/operator_velocity_test.go
Related: https://github.com/FoundationDB/fdb-kubernetes-operator/issues/2311 (not really fixed, only a workaround is added).
Interestingly the issue doesn't happen always but only sometimes.
Ran the e2e test from the issue manually multiple times.
Added in code.
Fix the actual underlying issue.
> Add workaround for cases where the operator gets stuck because of coordinator restarts

- .gitignore
- controllers/cluster_controller.go
- e2e/fixtures/fdb_operator_client.go
- e2e/test_operator_ha_upgrades/operator_ha_upgrade_test.go
- e2e/test_operator_upgrades/operator_upgrades_test.go
- fdbclient/lock_client.go
Fixed a few typos and changed the way hoe the operator pods are recreated in the test suite. Instead of deleting them we add a new annotation in the template (similar to `kubectl rollout restart ..`). I also added a new log entry for the lock client when the lock is released to log how long the lock was held.
- Other
-
Ran the e2e tests manually.
-
-
> Update typos and change the rollout strategy for the operator pods

- api/v1beta2/foundationdbcluster_types.go
- controllers/replace_misconfigured_process_groups.go
- controllers/replace_misconfigured_process_groups_test.go
- controllers/update_pods.go
- controllers/update_pods_test.go
- controllers/update_sidecar_versions.go
- controllers/update_status.go
- controllers/update_status_test.go
- docs/manual/warnings.md
- e2e/fixtures/fdb_cluster.go
- e2e/test_operator_upgrades/operator_upgrades_test.go
- internal/replacements/replacements.go
- internal/restarts/restarts.go
- internal/restarts/restarts_test.go
Fixes: https://github.com/FoundationDB/fdb-kubernetes-operator/issues/2292
The issue in the reported GitHub issue was, that the upgrade was triggered with a change to the Pod spec, which caused the operator to replace some pods. Those new pods came up with the new version and caused issues (as the older pods should be removed). I changed the operator logic to wait with Pod spec related changes until all processes are running on the new version (this doesn't wait for the rolling recreation/bounce phase).
I added a new e2e test case for this.
Added a note in our `warnings.md` that doing an upgrade and Pod spec changes is something that brings some risk and should be prevented if possible.
-
> Improve the pod spec change handling during version incompatible upgrades

- e2e/Makefile
Enable global sync mode in e2e tests again.
- Other
-
-
-
> Enable global sync mode in e2e tests again

- e2e/Makefile
- e2e/fixtures/factory.go
- e2e/test_operator_upgrades_with_chaos/operator_upgrades_with_chaos_test.go
The unified image doesn't have a check if a file is present (it does in a sense that it checks the binary before starting the binary but not an external check from the operator side).
- Other
Disabling the test for now. If we don't disable this test we will see some spontaneous failures, e.g. because the upgrades moves forward and in cases where a transaction or stateless pod is picked the test could fail with:
```text
[FAILED] Timed out after 120.000s.
Unexpected error:
<*errors.StatusError | 0x14000871400>:
pods "jdev-stateless-59937" not found
{
ErrStatus: {
TypeMeta: {Kind: "", APIVersion: ""},
ListMeta: {
SelfLink: "",
ResourceVersion: "",
Continue: "",
RemainingItemCount: nil,
},
Status: "Failure",
Message: "pods \"jdev-stateless-59937\" not found",
Reason: "NotFound",
Details: { …
```
> Disable test for unified image, since the unified image doesn't have a check for this

- api/v1beta2/foundationdbcluster_types.go
- controllers/check_client_compatibility.go
- controllers/check_client_compatibility_test.go
- controllers/cluster_controller_test.go
- pkg/fdbadminclient/mock/admin_client_mock.go
When a client has a newer version present, this will be the max protocol version and therefore the current checks would fail. 
-
Updated the unit tests.
-
-
> Update the client compatibility check to support cases where the clients have a newer version

- internal/monitor_conf.go
- internal/monitor_conf_test.go
- internal/pod_client_test.go
In cases where the Pod IP Family was set and the `FDB_PUBLIC_IP` was used as an environment variables, the operator created the wrong configuration, which could result in the cluster being stuck.
-
Added unit tests and will do some additional manual testing.
-
-
> Ensure that IP based environment variables are passed down as the correct argument type

- controllers/update_pods.go
- e2e/test_operator/operator_test.go
- internal/restarts/restarts.go
- internal/restarts/restarts_test.go
Fixes: https://github.com/FoundationDB/fdb-kubernetes-operator/issues/871
-
Ran the e2e test case manually (made it pending to reduce the running time, we probably should move this into a dedicated test suite).
```text
Operator when Changing the TLS setting when the pod spec stays the same should update the TLS setting  and keep the cluster available [e2e, pr]
...
2025/07/16 09:20:04 reconciled name=jdev, namespace=jscheuermann, generation:3
• [313.651 seconds]
Operator when Changing the TLS setting when the pod spec is changed should update the TLS setting  and keep the cluster available [e2e, pr]
...
2025/07/16 09:26:56 reconciled name=jdev, namespace=jscheuermann, …
```
> Fix stuck tls migration

- e2e/test_operator/operator_test.go
- e2e/test_operator_ha_upgrades/operator_ha_upgrade_test.go
- e2e/test_operator_upgrades/operator_upgrades_test.go
- e2e/test_operator_velocity/operator_velocity_test.go
- internal/coordination/coordination.go
- internal/restarts/restarts.go
In our e2e tests we have seen a few cases where the process groups were not removed if they are stuck in terminating. If the process is missing or stuck in terminating we should remove it from the pending restart set.
-
Ran the unit tests, CI will run the e2e tests.
-
-
> Ensure process groups are removed from the pending restart list if they are stuck in terminating or the process is missing

- controllers/check_client_compatibility.go
- controllers/check_client_compatibility_test.go
Update the compatibility check for multiple newer versions
-
Added in code.
-
> Update the compatibility check for multiple newer versions

- api/v1beta2/foundationdbcluster_types.go
- controllers/generate_initial_cluster_file.go
- controllers/replace_misconfigured_process_groups.go
- controllers/update_pods.go
- docs/manual/tls.md
- e2e/fixtures/chaos_common.go
- e2e/fixtures/factory.go
- e2e/fixtures/fdb_cluster.go
- e2e/fixtures/status.go
- e2e/test_operator/operator_test.go
- e2e/test_operator_migrations/operator_migration_test.go
- e2e/test_operator_upgrades/operator_upgrades_test.go
- internal/restarts/restarts.go
- internal/restarts/restarts_test.go
Restructure of our e2e tests, to balance the tests between the different test suites to achieve higher concurrency.
- Other
I deleted a test case that was pending for multiple years now with a feature that we probably will never use.
Ran some test manually and CI is running all of them.
Not needed.
-
> Restructure e2e test suite for better run times

- api/v1beta2/foundationdbcluster_types.go
- e2e/fixtures/fdb_cluster.go
- e2e/test_operator_migrations/operator_migration_test.go
Improve migration test case to reduce runtime, otherwise the migration will take a long  eventually timeout with the global sync mode.
I changed the migration test to only update log processes and not all processes, that should be good enough for what we are testing.
Ran the test case manually.
-
-
> Improve migration test case to reduce runtime

- .github/workflows/pull_request.yml
- .github/workflows/release.yaml
- Dockerfile
Update to the latest go 1.24.5 release (https://go.dev/doc/devel/release#go1.24.5)
- Other
-
Ran `make fmt lint test` locally.
-
-
> Update the go version to 1.24.5

- e2e/fixtures/fdb_operator_client.go
In one of the recent changes, we changed the logic to only fetch running operator pods. For most cases this is a true assumption, but in the case of the initial operator setup, some operator pods might be stuck in pending and those wouldn't be fetched. The changes in this PR changed the logic to return all pods for the operator deployment in the initial setup phase.
- Other
I changed the logging style to print out the json representation of the status fields for better readability.
Ran a test with a missing operator image and I saw the log output.
-
-
> Add more logging operator not running

- api/v1beta2/foundationdbcluster_types.go
- controllers/update_sidecar_versions.go
- controllers/update_status.go
- controllers/update_status_test.go
- e2e/test_operator_upgrades_variations/operator_upgrades_variations_test.go
Before this change the runningVersion would be updated before the updateStatus reconciler ends its work. This would lead to cases where the operator things that the cluster is reconciled after an upgrade, even thought the cluster shouldn't be marked as reconciled. In the next iteration the operator notice that the reconciliation is not done and would update it accordingly. 
The issue above could only be a problem if another system was waiting for the operator to mark the cluster as reconciled.
Ran e2e test and made sure we don't see the behaviour mentioned above. I will add an additional test or extend a test case.
-
-
> Correct the reconciliation status after the initial run after the cluster wide bounce

- e2e/Makefile
- e2e/fixtures/cluster_config.go
- e2e/fixtures/fdb_cluster_specs.go
- e2e/fixtures/options.go
Fixes: https://github.com/FoundationDB/fdb-kubernetes-operator/issues/2285
- Other
-
Ran test suite manually.
-
-
> Enable management API e2e test cases

- .github/workflows/pull_request.yml
- .github/workflows/release.yaml
- Dockerfile
Update the go and the Rocky version
- Other
-
Build a new image an ran the e2e tests.
-
-
> Update the go and the Rocky version

- api/v1beta2/foundationdb_custom_parameter.go
- api/v1beta2/foundationdb_custom_parameter_test.go
- controllers/backup_controller.go
- controllers/restore_controller.go
CustomParameters in `FoundationDBBackup` and `FoundationDBRestore` CRDs are meant to be passed to `backup_agent`. 
However, they are also passed to `fdbbackup` and `fdbrestore` commands when `admincli` object is built. An incompatible `backup_agent` parameter will be rejected by `fdbbackup/restore`, causing the operator to never reconcile the backup. We filter out the parameters that are exclusive to `backup_agents`.
X Bug fix (non-breaking change which fixes an issue)
- Other
*Please describe the tests …
> Fix passing incompatible parameters to fdbbackup and fdbrestore via CustomParameters

- Dockerfile
The default golang image changed the base image from `bookworm` to `trixie` and seems like this breaks the build, so switching back to `bookworm`.
-
Build the image locally (the `trixie` one also worked).
-
-
> Make sure we use the bookworm version of the go container

- controllers/update_metadata.go
- controllers/update_pod_config.go
- controllers/update_status.go
- e2e/test_operator/operator_test.go
- internal/coordination/coordination.go
Allow the pod metadata updater to update the metdadata for Pods marked as removal. This allows to update the knobs for process groups that are marked for removal. Otherwise a long running exclusion could lead to multiple restarts of the excluded process.
Added a new e2e test and ran different configurations.
-
-
> Allow the pod metadata updater to update the metdadata for Pods marked as removal

- api/v1beta2/foundationdbbackup_types.go
- api/v1beta2/foundationdbcluster_types.go
- api/v1beta2/foundationdbrestore_types.go
- charts/fdb-operator/Chart.yaml
- charts/fdb-operator/values.yaml
- config/crd/bases/apps.foundationdb.org_foundationdbbackups.yaml
- config/crd/bases/apps.foundationdb.org_foundationdbclusters.yaml
- config/crd/bases/apps.foundationdb.org_foundationdbrestores.yaml
- config/deployment/manager.yaml
- config/samples/deployment.yaml
- docs/changelog/v2.12.0.md
Update files for release 2.12.0
> Prepare release 2.12.0

- api/v1beta2/foundationdb_status.go
- api/v1beta2/foundationdb_status_test.go
- api/v1beta2/foundationdbcluster_types.go
- controllers/cluster_controller.go
- controllers/replace_failed_process_groups_test.go
- controllers/suite_test.go
- controllers/update_status.go
- controllers/update_status_test.go
- internal/replacements/replace_failed_process_groups.go
- pkg/fdbadminclient/mock/admin_client_mock.go
- setup/setup.go
Allow to replace process groups with a high run loop busy value
In some scenarios problems in the infrastructure might not result in unavailability and may not be caught by grey failure system, so this would be an additional check. A process with a high run loop busy value could indicate issues with the process of the node where it's currently running on.
Added unit tests and ran the e2e tests. I'll test how I can increase the run loop busy value for a dedicated test, but this test might not be reliable, depending on the feature in chaos-mesh that we can use.
-
-
> Allow to replace process groups with a high run loop busy value

- e2e/fixtures/factory.go
- e2e/fixtures/fdb_backup.go
- e2e/fixtures/fdb_cluster.go
- e2e/fixtures/fdb_restore.go
- e2e/fixtures/kubernetes_fixtures.go
- e2e/fixtures/pods.go
- e2e/scripts/remove_namespaces
- e2e/test_operator_backups/operator_backup_test.go
Before those changes only one backup and restore worked. Since we are adding more tests we have to improve the test suite for the backup and restore part of the operator.
- Other
-
Ran the e2e tests.
-
-
> Improve the backup e2e tests to allow multiple tests
